// content-company.js — Company marketing pages (about, contact, careers, blog
// teaser) plus the legal set, which lives in ./content-legal.js. Split from
// content.js so each content domain can be translated independently. Every
// company page ends with the shared CTA block passed in by content.js — the
// legal pages deliberately do not carry one.

import { buildLegalPages } from "./content-legal.js";

export function buildCompanyLegal(lang, cta) {
  const t = (m) => m[lang] ?? m.en;
  return {
    about: {
      hero: {
        eyebrow: t({ uk: "Про Klarnote", en: "About Klarnote", pl: "O Klarnote", de: "Über Klarnote", ro: "Despre Klarnote", cs: "O Klarnote", sr: "O Klarnoteu", hu: "A Klarnote-ról", ar: "حول Klarnote", es: "Sobre Klarnote", pt: "Sobre o Klarnote" }),
        title: t({
          uk: "Ми повертаємо лікарям час для пацієнтів",
          en: "We give clinicians their time back",
          pl: "Oddajemy lekarzom ich czas",
          de: "Wir geben Ärztinnen und Ärzten ihre Zeit zurück",
          ro: "Le redăm medicilor timpul lor",
          cs: "Vracíme lékařům jejich čas",
          sr: "Vraćamo lekarima njihovo vreme",
          hu: "Visszaadjuk az orvosok idejét",
          ar: "نُعيد للأطباء وقتهم",
          es: "Devolvemos su tiempo a los médicos",
          pt: "Devolvemos o tempo aos médicos",
        }),
        sub: t({
          uk: "Klarnote народився з простого спостереження: лікарі витрачають години на документацію замість того, щоб лікувати. Ми будуємо голосову платформу, яка пише нотатки за них.",
          en: "Klarnote began with a simple observation: clinicians spend hours on paperwork instead of care. We build the voice platform that writes the notes for them.",
          pl: "Klarnote zaczął się od prostej obserwacji: lekarze spędzają godziny na papierologii zamiast leczyć. Budujemy głosową platformę, która pisze notatki za nich.",
          de: "Klarnote begann mit einer einfachen Beobachtung: Ärztinnen und Ärzte verbringen Stunden mit Papierkram statt mit Behandlung. Wir bauen die Sprachplattform, die die Notizen für sie schreibt.",
          ro: "Klarnote a pornit de la o observație simplă: medicii petrec ore întregi cu birocrația în loc să îngrijească pacienți. Construim platforma vocală care scrie notele în locul lor.",
          cs: "Klarnote vznikl z prostého pozorování: lékaři tráví hodiny papírováním místo péče o pacienty. Stavíme hlasovou platformu, která poznámky píše za ně.",
          sr: "Klarnote je nastao iz jednostavnog zapažanja: lekari provode sate na papirologiji umesto na lečenju. Gradimo glasovnu platformu koja beleške piše umesto njih.",
          hu: "A Klarnote egy egyszerű megfigyelésből született: az orvosok órákat töltenek papírmunkával a gyógyítás helyett. Olyan hangalapú platformot építünk, amely megírja helyettük a jegyzeteket.",
          ar: "بدأت Klarnote من ملاحظة بسيطة: يقضي الأطباء ساعات في الأعمال الورقية بدلاً من رعاية المرضى. نحن نبني المنصة الصوتية التي تكتب الملاحظات نيابةً عنهم.",
          es: "Klarnote nació de una observación sencilla: los médicos dedican horas al papeleo en lugar de a la asistencia. Construimos la plataforma de voz que escribe las notas por ellos.",
          pt: "O Klarnote nasceu de uma observação simples: os médicos passam horas com papelada em vez de cuidar dos doentes. Construímos a plataforma de voz que escreve as notas por eles.",
        }),
      },
      blocks: [
        { type: "stats", items: t({
          uk: [{ v: "2024", l: "рік заснування" }, { v: "98%", l: "точність розпізнавання" }, { v: "2 мови", l: "українська та англійська" }, { v: "12+", l: "клінічних спеціальностей" }],
          en: [{ v: "2024", l: "founded" }, { v: "98%", l: "recognition accuracy" }, { v: "2 langs", l: "Ukrainian & English" }, { v: "12+", l: "clinical specialties" }],
          pl: [{ v: "2024", l: "rok założenia" }, { v: "98%", l: "dokładność rozpoznawania" }, { v: "2 języki", l: "ukraiński i angielski" }, { v: "12+", l: "specjalizacji klinicznych" }],
          de: [{ v: "2024", l: "gegründet" }, { v: "98%", l: "Erkennungsgenauigkeit" }, { v: "2 Sprachen", l: "Ukrainisch & Englisch" }, { v: "12+", l: "klinische Fachrichtungen" }],
          ro: [{ v: "2024", l: "anul înființării" }, { v: "98%", l: "acuratețea recunoașterii" }, { v: "2 limbi", l: "ucraineană și engleză" }, { v: "12+", l: "specialități clinice" }],
          cs: [{ v: "2024", l: "rok založení" }, { v: "98%", l: "přesnost rozpoznávání" }, { v: "2 jazyky", l: "ukrajinština a angličtina" }, { v: "12+", l: "klinických oborů" }],
          sr: [{ v: "2024", l: "godina osnivanja" }, { v: "98%", l: "tačnost prepoznavanja" }, { v: "2 jezika", l: "ukrajinski i engleski" }, { v: "12+", l: "kliničkih specijalnosti" }],
          hu: [{ v: "2024", l: "alapítás éve" }, { v: "98%", l: "felismerési pontosság" }, { v: "2 nyelv", l: "ukrán és angol" }, { v: "12+", l: "klinikai szakterület" }],
          ar: [{ v: "2024", l: "سنة التأسيس" }, { v: "98%", l: "دقة التعرّف" }, { v: "لغتان", l: "الأوكرانية والإنجليزية" }, { v: "12+", l: "تخصصاً سريرياً" }],
          es: [{ v: "2024", l: "fundación" }, { v: "98%", l: "precisión de reconocimiento" }, { v: "2 idiomas", l: "ucraniano e inglés" }, { v: "12+", l: "especialidades clínicas" }],
          pt: [{ v: "2024", l: "fundação" }, { v: "98%", l: "precisão de reconhecimento" }, { v: "2 idiomas", l: "ucraniano e inglês" }, { v: "12+", l: "especialidades clínicas" }],
        }) },
        { type: "prose", heading: t({ uk: "Наша місія", en: "Our mission", pl: "Nasza misja", de: "Unsere Mission", ro: "Misiunea noastră", cs: "Naše mise", sr: "Naša misija", hu: "Küldetésünk", ar: "مهمتنا", es: "Nuestra misión", pt: "A nossa missão" }),
          paragraphs: t({
            uk: ["Кожна хвилина, яку лікар витрачає на друк, — це хвилина, відібрана у пацієнта. Ми хочемо, щоб документація відбувалася сама собою — точно, безпечно та зрозумілою мовою.",
                 "Klarnote поєднує потокове розпізнавання медичної мови, структуровані шаблони та електронний підпис в одному робочому процесі, створеному разом із лікарями.",
                 "Наш головний принцип незмінний: система готує чернетку, але не ставить діагноз. Жоден документ не фіналізується без лікаря — а всі моделі розпізнавання та генерації працюють на власному, self-hosted обладнанні, тож дані пацієнтів не залишають вашого розгортання."],
            en: ["Every minute a clinician spends typing is a minute taken from the patient. We want documentation to happen on its own — accurately, securely, and in plain language.",
                 "Klarnote combines streaming medical speech recognition, structured templates and e-signature into one workflow, built together with clinicians.",
                 "Our core principle never changes: the system drafts, it does not diagnose. Nothing is finalized without a clinician — and every recognition and generation model runs on self-hosted hardware, so patient data never leaves your deployment."],
            pl: ["Każda minuta, którą lekarz spędza na pisaniu, to minuta odebrana pacjentowi. Chcemy, aby dokumentacja powstawała sama — dokładnie, bezpiecznie i zrozumiałym językiem.",
                 "Klarnote łączy strumieniowe rozpoznawanie mowy medycznej, ustrukturyzowane szablony i podpis elektroniczny w jeden przepływ pracy, stworzony wspólnie z lekarzami.",
                 "Nasza podstawowa zasada się nie zmienia: system tworzy szkic, ale nie stawia diagnozy. Nic nie jest finalizowane bez lekarza — a wszystkie modele rozpoznawania i generowania działają na własnym, self-hosted sprzęcie, więc dane pacjentów nigdy nie opuszczają Twojego wdrożenia."],
            de: ["Jede Minute, die eine Ärztin oder ein Arzt mit Tippen verbringt, ist eine Minute, die dem Patienten fehlt. Wir wollen, dass Dokumentation von selbst entsteht — präzise, sicher und in klarer Sprache.",
                 "Klarnote vereint streamende medizinische Spracherkennung, strukturierte Vorlagen und elektronische Signatur in einem Workflow — gemeinsam mit Ärztinnen und Ärzten entwickelt.",
                 "Unser Grundprinzip bleibt unverändert: Das System entwirft, es diagnostiziert nicht. Nichts wird ohne Ärztin oder Arzt finalisiert — und alle Erkennungs- und Generierungsmodelle laufen auf selbst gehosteter Hardware, sodass Patientendaten Ihre Umgebung nie verlassen."],
            ro: ["Fiecare minut pe care un medic îl petrece tastând este un minut luat pacientului. Ne dorim ca documentația să se scrie de la sine — precis, sigur și într-un limbaj clar.",
                 "Klarnote combină recunoașterea vocală medicală în timp real, șabloane structurate și semnătura electronică într-un singur flux de lucru, construit împreună cu medicii.",
                 "Principiul nostru de bază nu se schimbă: sistemul redactează, nu pune diagnostice. Nimic nu este finalizat fără un medic — iar toate modelele de recunoaștere și generare rulează pe hardware self-hosted, astfel încât datele pacienților nu părăsesc niciodată infrastructura dumneavoastră."],
            cs: ["Každá minuta, kterou lékař stráví psaním, je minuta vzatá pacientovi. Chceme, aby dokumentace vznikala sama — přesně, bezpečně a srozumitelným jazykem.",
                 "Klarnote spojuje streamované rozpoznávání lékařské řeči, strukturované šablony a elektronický podpis do jednoho pracovního postupu, vytvořeného společně s lékaři.",
                 "Náš základní princip se nemění: systém vytváří koncept, nediagnostikuje. Nic není finalizováno bez lékaře — a všechny modely rozpoznávání i generování běží na vlastním, self-hosted hardwaru, takže data pacientů nikdy neopustí vaše nasazení."],
            sr: ["Svaki minut koji lekar provede kucajući jeste minut oduzet pacijentu. Želimo da dokumentacija nastaje sama od sebe — tačno, bezbedno i jasnim jezikom.",
                 "Klarnote objedinjuje strimovano prepoznavanje medicinskog govora, strukturirane šablone i elektronski potpis u jedan radni tok, izgrađen zajedno sa lekarima.",
                 "Naš osnovni princip se ne menja: sistem piše nacrt, ne postavlja dijagnozu. Ništa se ne finalizuje bez lekara — a svi modeli prepoznavanja i generisanja rade na sopstvenom, self-hosted hardveru, pa podaci pacijenata nikada ne napuštaju vaše okruženje."],
            hu: ["Minden perc, amelyet az orvos gépeléssel tölt, a betegtől elvett perc. Azt szeretnénk, hogy a dokumentáció magától készüljön el — pontosan, biztonságosan és közérthető nyelven.",
                 "A Klarnote a valós idejű orvosi beszédfelismerést, a strukturált sablonokat és az elektronikus aláírást egyetlen munkafolyamatba egyesíti, amelyet orvosokkal közösen építettünk.",
                 "Alapelvünk változatlan: a rendszer vázlatot készít, nem diagnosztizál. Semmi sem véglegesíthető orvos nélkül — és minden felismerő és generáló modell saját, self-hosted hardveren fut, így a betegadatok soha nem hagyják el az Ön környezetét."],
            ar: ["كل دقيقة يقضيها الطبيب في الكتابة هي دقيقة مأخوذة من المريض. نريد أن تتم عملية التوثيق من تلقاء نفسها — بدقة وأمان وبلغة واضحة.",
                 "تجمع Klarnote بين التعرّف المتدفق على الكلام الطبي والقوالب المنظَّمة والتوقيع الإلكتروني في سير عمل واحد، بُني بالتعاون مع الأطباء.",
                 "مبدؤنا الأساسي لا يتغير: النظام يُعدّ المسودة، لكنه لا يُشخّص. لا يُعتمد أي مستند دون طبيب — وتعمل جميع نماذج التعرّف والتوليد على عتاد ذاتي الاستضافة (self-hosted)، لذا لا تغادر بيانات المرضى بيئة تشغيلك أبداً."],
          es: ["Cada minuto que un médico pasa tecleando es un minuto que se le quita al paciente. Queremos que la documentación se escriba sola: con precisión, con seguridad y en lenguaje claro.", "Klarnote reúne en un solo flujo el reconocimiento de voz médico en streaming, las plantillas estructuradas y la firma electrónica, construido junto a los propios médicos.", "Nuestro principio de fondo no cambia: el sistema redacta, no diagnostica. Nada se cierra sin un médico, y todos los modelos de reconocimiento y generación se ejecutan en hardware autoalojado, de modo que los datos del paciente nunca salen de su instalación."],
          pt: ["Cada minuto que um médico passa a escrever é um minuto retirado ao doente. Queremos que a documentação se escreva sozinha — com rigor, com segurança e em linguagem clara.", "O Klarnote reúne num só fluxo o reconhecimento de voz médico em streaming, os modelos estruturados e a assinatura eletrónica, construído em conjunto com os próprios médicos.", "O nosso princípio de base não muda: o sistema redige, não diagnostica. Nada é fechado sem um médico — e todos os modelos de reconhecimento e geração correm em hardware auto-alojado, pelo que os dados do doente nunca saem da sua instalação."],
          }) },
        { type: "grid", heading: t({ uk: "Наші цінності", en: "Our values", pl: "Nasze wartości", de: "Unsere Werte", ro: "Valorile noastre", cs: "Naše hodnoty", sr: "Naše vrednosti", hu: "Értékeink", ar: "قيمنا", es: "Nuestros valores", pt: "Os nossos valores" }), cols: 3, items: t({
          uk: [
              { icon: "heart", title: "Пацієнт понад усе", desc: "Кожне рішення оцінюємо за тим, чи дає воно лікарю більше часу з пацієнтом." },
              { icon: "shield", title: "Безпека за замовчуванням", desc: "Дані пацієнтів захищені на кожному етапі — від запису до архіву." },
              { icon: "sparkle", title: "Точність важливіша за хайп", desc: "Ми вимірюємо реальну якість розпізнавання, а не обіцянки." },
              { icon: "users", title: "Створено з лікарями", desc: "Продукт формують ті, хто щодня веде прийоми." },
              { icon: "check", title: "Прозорість", desc: "Зрозуміло, як обробляються дані та як працює модель." },
              { icon: "history", title: "Надійність", desc: "Незмінний аудит і повна історія змін кожного документа." },
            ],
          en: [
              { icon: "heart", title: "Patient first", desc: "Every decision is judged by whether it gives clinicians more time with patients." },
              { icon: "shield", title: "Secure by default", desc: "Patient data is protected at every step — from recording to archive." },
              { icon: "sparkle", title: "Accuracy over hype", desc: "We measure real recognition quality, not promises." },
              { icon: "users", title: "Built with clinicians", desc: "The product is shaped by the people running visits every day." },
              { icon: "check", title: "Transparency", desc: "Clear about how data is processed and how the model works." },
              { icon: "history", title: "Reliability", desc: "Immutable audit and a full change history for every document." },
            ],
          pl: [
              { icon: "heart", title: "Pacjent przede wszystkim", desc: "Każdą decyzję oceniamy po tym, czy daje lekarzom więcej czasu z pacjentami." },
              { icon: "shield", title: "Bezpieczeństwo domyślnie", desc: "Dane pacjentów są chronione na każdym etapie — od nagrania po archiwum." },
              { icon: "sparkle", title: "Dokładność ponad szum", desc: "Mierzymy rzeczywistą jakość rozpoznawania, a nie obietnice." },
              { icon: "users", title: "Tworzone z lekarzami", desc: "Produkt kształtują ludzie, którzy codziennie prowadzą wizyty." },
              { icon: "check", title: "Przejrzystość", desc: "Jasno mówimy, jak przetwarzane są dane i jak działa model." },
              { icon: "history", title: "Niezawodność", desc: "Niezmienny audyt i pełna historia zmian każdego dokumentu." },
            ],
          de: [
              { icon: "heart", title: "Der Patient zuerst", desc: "Jede Entscheidung wird daran gemessen, ob sie Ärztinnen und Ärzten mehr Zeit mit Patienten gibt." },
              { icon: "shield", title: "Sicher per Voreinstellung", desc: "Patientendaten sind in jedem Schritt geschützt — von der Aufnahme bis zum Archiv." },
              { icon: "sparkle", title: "Genauigkeit statt Hype", desc: "Wir messen echte Erkennungsqualität, keine Versprechen." },
              { icon: "users", title: "Mit Ärzten entwickelt", desc: "Das Produkt wird von Menschen geprägt, die täglich Sprechstunden führen." },
              { icon: "check", title: "Transparenz", desc: "Klar darüber, wie Daten verarbeitet werden und wie das Modell funktioniert." },
              { icon: "history", title: "Zuverlässigkeit", desc: "Unveränderliches Audit und vollständige Änderungshistorie für jedes Dokument." },
            ],
          ro: [
              { icon: "heart", title: "Pacientul pe primul loc", desc: "Fiecare decizie este judecată după cât timp le oferă medicilor cu pacienții." },
              { icon: "shield", title: "Securitate implicită", desc: "Datele pacienților sunt protejate la fiecare pas — de la înregistrare la arhivă." },
              { icon: "sparkle", title: "Acuratețe în locul hype-ului", desc: "Măsurăm calitatea reală a recunoașterii, nu promisiuni." },
              { icon: "users", title: "Construit cu medicii", desc: "Produsul este modelat de oamenii care fac consultații în fiecare zi." },
              { icon: "check", title: "Transparență", desc: "Explicăm clar cum sunt prelucrate datele și cum funcționează modelul." },
              { icon: "history", title: "Fiabilitate", desc: "Audit imuabil și istoric complet al modificărilor pentru fiecare document." },
            ],
          cs: [
              { icon: "heart", title: "Pacient na prvním místě", desc: "Každé rozhodnutí posuzujeme podle toho, zda dává lékařům více času s pacienty." },
              { icon: "shield", title: "Bezpečnost ve výchozím stavu", desc: "Data pacientů jsou chráněna v každém kroku — od nahrávky po archiv." },
              { icon: "sparkle", title: "Přesnost místo humbuku", desc: "Měříme skutečnou kvalitu rozpoznávání, ne sliby." },
              { icon: "users", title: "Vytvořeno s lékaři", desc: "Produkt formují lidé, kteří denně vedou vyšetření." },
              { icon: "check", title: "Transparentnost", desc: "Srozumitelně o tom, jak se zpracovávají data a jak model funguje." },
              { icon: "history", title: "Spolehlivost", desc: "Neměnný audit a úplná historie změn každého dokumentu." },
            ],
          sr: [
              { icon: "heart", title: "Pacijent na prvom mestu", desc: "Svaku odluku procenjujemo po tome da li lekarima daje više vremena sa pacijentima." },
              { icon: "shield", title: "Bezbednost podrazumevano", desc: "Podaci pacijenata zaštićeni su u svakom koraku — od snimka do arhive." },
              { icon: "sparkle", title: "Tačnost umesto pompe", desc: "Merimo stvarni kvalitet prepoznavanja, a ne obećanja." },
              { icon: "users", title: "Napravljeno sa lekarima", desc: "Proizvod oblikuju ljudi koji svakog dana vode preglede." },
              { icon: "check", title: "Transparentnost", desc: "Jasno o tome kako se obrađuju podaci i kako model radi." },
              { icon: "history", title: "Pouzdanost", desc: "Nepromenljiva revizija i potpuna istorija izmena svakog dokumenta." },
            ],
          hu: [
              { icon: "heart", title: "A beteg az első", desc: "Minden döntést az alapján ítélünk meg, hogy több időt ad-e az orvosoknak a betegeikre." },
              { icon: "shield", title: "Alapértelmezetten biztonságos", desc: "A betegadatok minden lépésben védettek — a felvételtől az archívumig." },
              { icon: "sparkle", title: "Pontosság a hype helyett", desc: "A felismerés valós minőségét mérjük, nem az ígéreteket." },
              { icon: "users", title: "Orvosokkal közösen készült", desc: "A terméket azok formálják, akik nap mint nap rendelnek." },
              { icon: "check", title: "Átláthatóság", desc: "Világosan elmondjuk, hogyan dolgozzuk fel az adatokat és hogyan működik a modell." },
              { icon: "history", title: "Megbízhatóság", desc: "Megmásíthatatlan audit és teljes változásnapló minden dokumentumhoz." },
            ],
          ar: [
              { icon: "heart", title: "المريض أولاً", desc: "يُقاس كل قرار بمدى منحه الأطباء وقتاً أطول مع المرضى." },
              { icon: "shield", title: "آمن افتراضياً", desc: "بيانات المرضى محمية في كل خطوة — من التسجيل إلى الأرشيف." },
              { icon: "sparkle", title: "الدقة قبل الضجيج", desc: "نقيس جودة التعرّف الحقيقية، لا الوعود." },
              { icon: "users", title: "بُني مع الأطباء", desc: "يشكّل المنتجَ من يُجرون المعاينات كل يوم." },
              { icon: "check", title: "الشفافية", desc: "وضوح في كيفية معالجة البيانات وكيفية عمل النموذج." },
              { icon: "history", title: "الموثوقية", desc: "سجل تدقيق غير قابل للتغيير وتاريخ تغييرات كامل لكل مستند." },
            ],
          es: [
            { icon: "heart", title: "El paciente primero", desc: "Cada decisión se juzga por si da al médico más tiempo con el paciente." },
            { icon: "shield", title: "Seguro por defecto", desc: "Los datos del paciente están protegidos en cada paso, desde la grabación hasta el archivo." },
            { icon: "sparkle", title: "Precisión antes que ruido", desc: "Medimos la calidad real del reconocimiento, no las promesas." },
            { icon: "users", title: "Hecho con médicos", desc: "El producto lo moldean quienes pasan consulta cada día." },
            { icon: "check", title: "Transparencia", desc: "Claridad sobre cómo se tratan los datos y cómo funciona el modelo." },
            { icon: "history", title: "Fiabilidad", desc: "Auditoría inmutable e historial completo de cambios en cada documento." },
          ],
          pt: [
            { icon: "heart", title: "O doente primeiro", desc: "Cada decisão é avaliada pelo tempo que devolve ao médico junto do doente." },
            { icon: "shield", title: "Seguro por predefinição", desc: "Os dados do doente estão protegidos em cada passo — da gravação ao arquivo." },
            { icon: "sparkle", title: "Rigor acima do ruído", desc: "Medimos a qualidade real do reconhecimento, não promessas." },
            { icon: "users", title: "Feito com médicos", desc: "O produto é moldado por quem dá consultas todos os dias." },
            { icon: "check", title: "Transparência", desc: "Clareza sobre como os dados são tratados e como o modelo funciona." },
            { icon: "history", title: "Fiabilidade", desc: "Auditoria imutável e histórico completo de alterações em cada documento." },
          ],
        }) },
        { type: "prose", heading: t({ uk: "Наша історія", en: "Our story", pl: "Nasza historia", de: "Unsere Geschichte", ro: "Povestea noastră", cs: "Náš příběh", sr: "Naša priča", hu: "Történetünk", ar: "قصتنا", es: "Nuestra historia", pt: "A nossa história" }),
          paragraphs: t({
            uk: ["Команда Klarnote складається з інженерів та лікарів, які втомилися від нескінченної паперової роботи. Ми почали з прототипу для радіологів і швидко зрозуміли, що проблема — універсальна.",
                 "Сьогодні Klarnote обслуговує амбулаторні прийоми та класичне диктування звітів, підтримує українську та англійську мови й інтегрується з електронним підписом Дія."],
            en: ["The Klarnote team is engineers and clinicians tired of endless paperwork. We started with a prototype for radiologists and quickly saw the problem was universal.",
                 "Today Klarnote powers ambient encounters and classic report dictation, supports Ukrainian and English, and integrates with the Дія e-signature."],
            pl: ["Zespół Klarnote to inżynierowie i lekarze zmęczeni niekończącą się papierologią. Zaczęliśmy od prototypu dla radiologów i szybko zobaczyliśmy, że problem jest uniwersalny.",
                 "Dziś Klarnote obsługuje wizyty w trybie ambient oraz klasyczne dyktowanie raportów, wspiera język ukraiński i angielski oraz integruje się z podpisem elektronicznym Дія (Diia)."],
            de: ["Das Klarnote-Team besteht aus Ingenieuren und Ärzten, die endlose Papierarbeit satthaben. Wir begannen mit einem Prototyp für Radiologen und sahen schnell, dass das Problem universell ist.",
                 "Heute unterstützt Klarnote Ambient-Sprechstunden und klassisches Befund-Diktat, beherrscht Ukrainisch und Englisch und integriert die elektronische Signatur Дія (Diia)."],
            ro: ["Echipa Klarnote este formată din ingineri și medici sătui de birocrația fără sfârșit. Am început cu un prototip pentru radiologi și am văzut rapid că problema este universală.",
                 "Astăzi Klarnote susține consultații ambient și dictarea clasică de rapoarte, acceptă ucraineana și engleza și se integrează cu semnătura electronică Дія (Diia)."],
            cs: ["Tým Klarnote tvoří inženýři a lékaři unavení nekonečným papírováním. Začali jsme prototypem pro radiology a rychle jsme zjistili, že problém je univerzální.",
                 "Dnes Klarnote pokrývá ambientní vyšetření i klasické diktování zpráv, podporuje ukrajinštinu a angličtinu a integruje elektronický podpis Дія (Diia)."],
            sr: ["Tim Klarnotea čine inženjeri i lekari umorni od beskrajne papirologije. Počeli smo prototipom za radiologe i brzo uvideli da je problem univerzalan.",
                 "Danas Klarnote pokreće ambijentalne preglede i klasično diktiranje izveštaja, podržava ukrajinski i engleski i integriše se sa elektronskim potpisom Дія (Diia)."],
            hu: ["A Klarnote csapata mérnökökből és orvosokból áll, akik belefáradtak a végtelen papírmunkába. Egy radiológusoknak készült prototípussal indultunk, és hamar láttuk, hogy a probléma egyetemes.",
                 "Ma a Klarnote az ambient vizitek és a klasszikus leletdiktálás motorja, támogatja az ukrán és az angol nyelvet, és integrálódik a Дія (Diia) elektronikus aláírással."],
            ar: ["يتكوّن فريق Klarnote من مهندسين وأطباء سئموا الأعمال الورقية التي لا تنتهي. بدأنا بنموذج أولي لأطباء الأشعة وسرعان ما أدركنا أن المشكلة عامة.",
                 "اليوم تُشغّل Klarnote المعاينات المحيطية والإملاء الكلاسيكي للتقارير، وتدعم الأوكرانية والإنجليزية، وتتكامل مع التوقيع الإلكتروني Дія."],
          es: ["El equipo de Klarnote son ingenieros y médicos cansados del papeleo interminable. Empezamos con un prototipo para radiólogos y enseguida vimos que el problema era universal.", "Hoy Klarnote impulsa las consultas con escriba ambiental y el dictado clásico de informes, admite ucraniano e inglés y se integra con la firma electrónica Дія."],
          pt: ["A equipa do Klarnote é feita de engenheiros e médicos cansados da papelada sem fim. Começámos com um protótipo para radiologistas e depressa vimos que o problema era universal.", "Hoje o Klarnote suporta consultas com escriba ambiental e o ditado clássico de relatórios, funciona em ucraniano e inglês e integra-se com a assinatura eletrónica Дія."],
          }) },
        cta,
      ],
    },

    contact: {
      hero: {
        eyebrow: t({ uk: "Контакти", en: "Contact", pl: "Kontakt", de: "Kontakt", ro: "Contact", cs: "Kontakt", sr: "Kontakt", hu: "Kapcsolat", ar: "التواصل", es: "Contacto", pt: "Contacto" }),
        title: t({ uk: "Поговоримо", en: "Let's talk", pl: "Porozmawiajmy", de: "Sprechen wir", ro: "Să vorbim", cs: "Pojďme si promluvit", sr: "Razgovarajmo", hu: "Beszéljünk", ar: "لنتحدث", es: "Hablemos", pt: "Vamos conversar" }),
        sub: t({
          uk: "Питання про продукт, демо для вашої клініки чи партнерство — ми відповідаємо швидко.",
          en: "Product questions, a demo for your clinic, or a partnership — we reply fast.",
          pl: "Pytania o produkt, demo dla Twojej kliniki czy partnerstwo — odpowiadamy szybko.",
          de: "Fragen zum Produkt, eine Demo für Ihre Klinik oder eine Partnerschaft — wir antworten schnell.",
          ro: "Întrebări despre produs, un demo pentru clinica dumneavoastră sau un parteneriat — răspundem rapid.",
          cs: "Dotazy k produktu, demo pro vaši kliniku nebo partnerství — odpovídáme rychle.",
          sr: "Pitanja o proizvodu, demo za vašu kliniku ili partnerstvo — odgovaramo brzo.",
          hu: "Kérdések a termékről, demó a klinikájának vagy partnerség — gyorsan válaszolunk.",
          ar: "أسئلة عن المنتج، أو عرض توضيحي لعيادتك، أو شراكة — نردّ بسرعة.",
          es: "Dudas sobre el producto, una demo para su clínica o una alianza: respondemos rápido.",
          pt: "Dúvidas sobre o produto, uma demonstração para a sua clínica ou uma parceria — respondemos depressa.",
        }),
      },
      blocks: [
        // The mailbox grid and the office list were removed 2026-08-11. Both
        // competed with the form for the same decision: four addresses ask a
        // visitor to route their own message, and two street addresses answer
        // a question nobody arrives at a contact page with. What is left is one
        // way in — the form, which now carries a reason dropdown that does the
        // routing the four mailboxes were doing by hand.
        //
        // The addresses still exist and are still ours; they are simply not the
        // front door. Support has its own entry in /settings (About → Support).
        { type: "form" },
      ],
    },

    careers: {
      hero: {
        eyebrow: t({ uk: "Кар'єра", en: "Careers", pl: "Kariera", de: "Karriere", ro: "Cariere", cs: "Kariéra", sr: "Karijera", hu: "Karrier", ar: "الوظائف", es: "Empleo", pt: "Carreiras" }),
        title: t({
          uk: "Будуйте майбутнє медичної документації",
          en: "Build the future of medical documentation",
          pl: "Buduj przyszłość dokumentacji medycznej",
          de: "Gestalten Sie die Zukunft der medizinischen Dokumentation",
          ro: "Construiește viitorul documentației medicale",
          cs: "Budujte budoucnost lékařské dokumentace",
          sr: "Gradite budućnost medicinske dokumentacije",
          hu: "Építsd velünk az orvosi dokumentáció jövőjét",
          ar: "ابنِ مستقبل التوثيق الطبي",
          es: "Construya el futuro de la documentación clínica",
          pt: "Construa o futuro da documentação clínica",
        }),
        sub: t({
          uk: "Ми невелика команда з великою місією. Якщо вам близька ідея повернути лікарям час — приєднуйтесь.",
          en: "We're a small team with a big mission. If giving clinicians their time back resonates with you — join us.",
          pl: "Jesteśmy małym zespołem z wielką misją. Jeśli idea oddania lekarzom ich czasu jest Ci bliska — dołącz do nas.",
          de: "Wir sind ein kleines Team mit einer großen Mission. Wenn es Sie anspricht, Ärztinnen und Ärzten ihre Zeit zurückzugeben — kommen Sie zu uns.",
          ro: "Suntem o echipă mică, cu o misiune mare. Dacă ideea de a le reda medicilor timpul rezonează cu tine — alătură-te nouă.",
          cs: "Jsme malý tým s velkou misí. Pokud vám myšlenka vrátit lékařům čas dává smysl — přidejte se k nám.",
          sr: "Mali smo tim sa velikom misijom. Ako vam je bliska ideja da lekarima vratimo vreme — pridružite nam se.",
          hu: "Kis csapat vagyunk nagy küldetéssel. Ha közel áll hozzád a gondolat, hogy visszaadjuk az orvosok idejét — csatlakozz hozzánk.",
          ar: "نحن فريق صغير بمهمة كبيرة. إن كانت فكرة إعادة الوقت للأطباء تلقى صدى لديك — انضمّ إلينا.",
          es: "Somos un equipo pequeño con una misión grande. Si devolver su tiempo a los médicos le dice algo, únase a nosotros.",
          pt: "Somos uma equipa pequena com uma missão grande. Se devolver o tempo aos médicos lhe diz alguma coisa, junte-se a nós.",
        }),
      },
      blocks: [
        { type: "grid", heading: t({ uk: "Чому Klarnote", en: "Why Klarnote", pl: "Dlaczego Klarnote", de: "Warum Klarnote", ro: "De ce Klarnote", cs: "Proč Klarnote", sr: "Zašto Klarnote", hu: "Miért a Klarnote", ar: "لماذا Klarnote", es: "Por qué Klarnote", pt: "Porquê o Klarnote" }), cols: 3, items: t({
          uk: [
              { icon: "heart", title: "Реальний вплив", desc: "Ваша робота щодня економить години лікарям." },
              { icon: "home", title: "Віддалено", desc: "Гнучкий графік і робота з будь-якої точки." },
              { icon: "sparkle", title: "Сучасний стек", desc: "Передові моделі розпізнавання мови та чистий код." },
              { icon: "book", title: "Навчання", desc: "Бюджет на конференції, книги та курси." },
              { icon: "calendar", title: "Відпустка", desc: "Достатньо часу, щоб відновитися." },
              { icon: "users", title: "Сильна команда", desc: "Інженери та лікарі, які поважають одне одного." },
            ],
          en: [
              { icon: "heart", title: "Real impact", desc: "Your work saves clinicians hours every day." },
              { icon: "home", title: "Remote-first", desc: "Flexible hours and work from anywhere." },
              { icon: "sparkle", title: "Modern stack", desc: "State-of-the-art speech models and clean code." },
              { icon: "book", title: "Learning", desc: "Budget for conferences, books and courses." },
              { icon: "calendar", title: "Time off", desc: "Enough time to actually recharge." },
              { icon: "users", title: "Great team", desc: "Engineers and clinicians who respect each other." },
            ],
          pl: [
              { icon: "heart", title: "Realny wpływ", desc: "Twoja praca codziennie oszczędza lekarzom godziny." },
              { icon: "home", title: "Praca zdalna", desc: "Elastyczne godziny i praca z dowolnego miejsca." },
              { icon: "sparkle", title: "Nowoczesny stack", desc: "Najnowocześniejsze modele rozpoznawania mowy i czysty kod." },
              { icon: "book", title: "Rozwój", desc: "Budżet na konferencje, książki i kursy." },
              { icon: "calendar", title: "Urlop", desc: "Wystarczająco czasu, żeby naprawdę odpocząć." },
              { icon: "users", title: "Świetny zespół", desc: "Inżynierowie i lekarze, którzy się nawzajem szanują." },
            ],
          de: [
              { icon: "heart", title: "Echte Wirkung", desc: "Ihre Arbeit spart Ärztinnen und Ärzten täglich Stunden." },
              { icon: "home", title: "Remote-first", desc: "Flexible Arbeitszeiten und Arbeit von überall." },
              { icon: "sparkle", title: "Moderner Stack", desc: "Modernste Sprachmodelle und sauberer Code." },
              { icon: "book", title: "Weiterbildung", desc: "Budget für Konferenzen, Bücher und Kurse." },
              { icon: "calendar", title: "Urlaub", desc: "Genug Zeit, um wirklich aufzutanken." },
              { icon: "users", title: "Starkes Team", desc: "Ingenieure und Ärzte, die einander respektieren." },
            ],
          ro: [
              { icon: "heart", title: "Impact real", desc: "Munca ta le economisește medicilor ore în fiecare zi." },
              { icon: "home", title: "Remote-first", desc: "Program flexibil și lucru de oriunde." },
              { icon: "sparkle", title: "Stack modern", desc: "Modele de vorbire de ultimă generație și cod curat." },
              { icon: "book", title: "Învățare", desc: "Buget pentru conferințe, cărți și cursuri." },
              { icon: "calendar", title: "Concediu", desc: "Suficient timp ca să te refaci cu adevărat." },
              { icon: "users", title: "Echipă excelentă", desc: "Ingineri și medici care se respectă reciproc." },
            ],
          cs: [
              { icon: "heart", title: "Skutečný dopad", desc: "Vaše práce denně šetří lékařům hodiny." },
              { icon: "home", title: "Remote-first", desc: "Flexibilní pracovní doba a práce odkudkoli." },
              { icon: "sparkle", title: "Moderní stack", desc: "Špičkové modely rozpoznávání řeči a čistý kód." },
              { icon: "book", title: "Vzdělávání", desc: "Rozpočet na konference, knihy a kurzy." },
              { icon: "calendar", title: "Dovolená", desc: "Dost času na skutečný odpočinek." },
              { icon: "users", title: "Skvělý tým", desc: "Inženýři a lékaři, kteří se navzájem respektují." },
            ],
          sr: [
              { icon: "heart", title: "Stvaran uticaj", desc: "Vaš rad svakog dana štedi lekarima sate." },
              { icon: "home", title: "Remote-first", desc: "Fleksibilno radno vreme i rad sa bilo kog mesta." },
              { icon: "sparkle", title: "Moderan stek", desc: "Najsavremeniji modeli prepoznavanja govora i čist kod." },
              { icon: "book", title: "Učenje", desc: "Budžet za konferencije, knjige i kurseve." },
              { icon: "calendar", title: "Odmor", desc: "Dovoljno vremena za pravi oporavak." },
              { icon: "users", title: "Sjajan tim", desc: "Inženjeri i lekari koji poštuju jedni druge." },
            ],
          hu: [
              { icon: "heart", title: "Valódi hatás", desc: "A munkád naponta órákat spórol az orvosoknak." },
              { icon: "home", title: "Remote-first", desc: "Rugalmas munkaidő, munka bárhonnan." },
              { icon: "sparkle", title: "Modern stack", desc: "Élvonalbeli beszédfelismerő modellek és tiszta kód." },
              { icon: "book", title: "Tanulás", desc: "Keret konferenciákra, könyvekre és kurzusokra." },
              { icon: "calendar", title: "Szabadság", desc: "Elég idő az igazi feltöltődéshez." },
              { icon: "users", title: "Remek csapat", desc: "Mérnökök és orvosok, akik tisztelik egymást." },
            ],
          ar: [
              { icon: "heart", title: "أثر حقيقي", desc: "عملك يوفّر على الأطباء ساعات كل يوم." },
              { icon: "home", title: "العمل عن بُعد أولاً", desc: "ساعات مرنة وعمل من أي مكان." },
              { icon: "sparkle", title: "بنية تقنية حديثة", desc: "نماذج كلام متطورة وشيفرة نظيفة." },
              { icon: "book", title: "التعلّم", desc: "ميزانية للمؤتمرات والكتب والدورات." },
              { icon: "calendar", title: "إجازات", desc: "وقت كافٍ لاستعادة النشاط فعلاً." },
              { icon: "users", title: "فريق رائع", desc: "مهندسون وأطباء يحترم بعضهم بعضاً." },
            ],
          es: [
            { icon: "heart", title: "Impacto real", desc: "Su trabajo ahorra horas a los médicos cada día." },
            { icon: "home", title: "Remoto primero", desc: "Horario flexible y trabajo desde cualquier lugar." },
            { icon: "sparkle", title: "Stack moderno", desc: "Modelos de voz punteros y código limpio." },
            { icon: "book", title: "Aprendizaje", desc: "Presupuesto para congresos, libros y cursos." },
            { icon: "calendar", title: "Vacaciones", desc: "Tiempo suficiente para desconectar de verdad." },
            { icon: "users", title: "Buen equipo", desc: "Ingenieros y médicos que se respetan." },
          ],
          pt: [
            { icon: "heart", title: "Impacto real", desc: "O seu trabalho poupa horas aos médicos todos os dias." },
            { icon: "home", title: "Remoto primeiro", desc: "Horário flexível e trabalho a partir de qualquer lugar." },
            { icon: "sparkle", title: "Stack moderna", desc: "Modelos de voz de ponta e código limpo." },
            { icon: "book", title: "Aprendizagem", desc: "Orçamento para conferências, livros e cursos." },
            { icon: "calendar", title: "Férias", desc: "Tempo suficiente para descansar a sério." },
            { icon: "users", title: "Boa equipa", desc: "Engenheiros e médicos que se respeitam." },
          ],
        }) },
        { type: "roles", heading: t({ uk: "Відкриті вакансії", en: "Open roles", pl: "Otwarte stanowiska", de: "Offene Stellen", ro: "Poziții deschise", cs: "Otevřené pozice", sr: "Otvorene pozicije", hu: "Nyitott pozíciók", ar: "الوظائف الشاغرة", es: "Vacantes abiertas", pt: "Vagas abertas" }), items: t({
          uk: [
              { title: "Senior ML Engineer (Speech)", team: "Дослідження", location: "Віддалено", type: "Повна зайнятість" },
              { title: "Full-Stack Engineer (React)", team: "Продукт", location: "Київ / Віддалено", type: "Повна зайнятість" },
              { title: "Clinical Product Specialist", team: "Продукт", location: "Віддалено", type: "Повна зайнятість" },
              { title: "Security Engineer", team: "Платформа", location: "Віддалено", type: "Повна зайнятість" },
            ],
          en: [
              { title: "Senior ML Engineer (Speech)", team: "Research", location: "Remote", type: "Full-time" },
              { title: "Full-Stack Engineer (React)", team: "Product", location: "Kyiv / Remote", type: "Full-time" },
              { title: "Clinical Product Specialist", team: "Product", location: "Remote", type: "Full-time" },
              { title: "Security Engineer", team: "Platform", location: "Remote", type: "Full-time" },
            ],
          pl: [
              { title: "Senior ML Engineer (Speech)", team: "Badania", location: "Zdalnie", type: "Pełny etat" },
              { title: "Full-Stack Engineer (React)", team: "Produkt", location: "Kijów / Zdalnie", type: "Pełny etat" },
              { title: "Clinical Product Specialist", team: "Produkt", location: "Zdalnie", type: "Pełny etat" },
              { title: "Security Engineer", team: "Platforma", location: "Zdalnie", type: "Pełny etat" },
            ],
          de: [
              { title: "Senior ML Engineer (Speech)", team: "Forschung", location: "Remote", type: "Vollzeit" },
              { title: "Full-Stack Engineer (React)", team: "Produkt", location: "Kiew / Remote", type: "Vollzeit" },
              { title: "Clinical Product Specialist", team: "Produkt", location: "Remote", type: "Vollzeit" },
              { title: "Security Engineer", team: "Plattform", location: "Remote", type: "Vollzeit" },
            ],
          ro: [
              { title: "Senior ML Engineer (Speech)", team: "Cercetare", location: "Remote", type: "Normă întreagă" },
              { title: "Full-Stack Engineer (React)", team: "Produs", location: "Kiev / Remote", type: "Normă întreagă" },
              { title: "Clinical Product Specialist", team: "Produs", location: "Remote", type: "Normă întreagă" },
              { title: "Security Engineer", team: "Platformă", location: "Remote", type: "Normă întreagă" },
            ],
          cs: [
              { title: "Senior ML Engineer (Speech)", team: "Výzkum", location: "Vzdáleně", type: "Plný úvazek" },
              { title: "Full-Stack Engineer (React)", team: "Produkt", location: "Kyjev / Vzdáleně", type: "Plný úvazek" },
              { title: "Clinical Product Specialist", team: "Produkt", location: "Vzdáleně", type: "Plný úvazek" },
              { title: "Security Engineer", team: "Platforma", location: "Vzdáleně", type: "Plný úvazek" },
            ],
          sr: [
              { title: "Senior ML Engineer (Speech)", team: "Istraživanje", location: "Na daljinu", type: "Puno radno vreme" },
              { title: "Full-Stack Engineer (React)", team: "Proizvod", location: "Kijev / Na daljinu", type: "Puno radno vreme" },
              { title: "Clinical Product Specialist", team: "Proizvod", location: "Na daljinu", type: "Puno radno vreme" },
              { title: "Security Engineer", team: "Platforma", location: "Na daljinu", type: "Puno radno vreme" },
            ],
          hu: [
              { title: "Senior ML Engineer (Speech)", team: "Kutatás", location: "Távmunka", type: "Teljes munkaidő" },
              { title: "Full-Stack Engineer (React)", team: "Termék", location: "Kijev / Távmunka", type: "Teljes munkaidő" },
              { title: "Clinical Product Specialist", team: "Termék", location: "Távmunka", type: "Teljes munkaidő" },
              { title: "Security Engineer", team: "Platform", location: "Távmunka", type: "Teljes munkaidő" },
            ],
          ar: [
              { title: "Senior ML Engineer (Speech)", team: "الأبحاث", location: "عن بُعد", type: "دوام كامل" },
              { title: "Full-Stack Engineer (React)", team: "المنتج", location: "كييف / عن بُعد", type: "دوام كامل" },
              { title: "Clinical Product Specialist", team: "المنتج", location: "عن بُعد", type: "دوام كامل" },
              { title: "Security Engineer", team: "المنصة", location: "عن بُعد", type: "دوام كامل" },
            ],
          es: [
            { title: "Ingeniero/a sénior de ML (voz)", team: "Investigación", location: "En remoto", type: "Jornada completa" },
            { title: "Ingeniero/a full-stack (React)", team: "Producto", location: "Kiev / En remoto", type: "Jornada completa" },
            { title: "Especialista de producto clínico", team: "Producto", location: "En remoto", type: "Jornada completa" },
            { title: "Ingeniero/a de seguridad", team: "Plataforma", location: "En remoto", type: "Jornada completa" },
          ],
          pt: [
            { title: "Engenheiro(a) sénior de ML (voz)", team: "Investigação", location: "Remoto", type: "Tempo inteiro" },
            { title: "Engenheiro(a) full-stack (React)", team: "Produto", location: "Kiev / Remoto", type: "Tempo inteiro" },
            { title: "Especialista de produto clínico", team: "Produto", location: "Remoto", type: "Tempo inteiro" },
            { title: "Engenheiro(a) de segurança", team: "Plataforma", location: "Remoto", type: "Tempo inteiro" },
          ],
        }) },
        { type: "prose", heading: t({ uk: "Не бачите своєї ролі?", en: "Don't see your role?", pl: "Nie widzisz swojej roli?", de: "Ihre Rolle ist nicht dabei?", ro: "Nu îți găsești rolul?", cs: "Nevidíte svou roli?", sr: "Ne vidite svoju ulogu?", hu: "Nem találod a szerepkörödet?", ar: "لا تجد وظيفتك؟", es: "¿No ve su puesto?", pt: "Não vê a sua função?" }),
          paragraphs: t({
            uk: ["Ми завжди раді талановитим людям. Напишіть нам на careers@klarnote.com — розкажіть, чим хочете займатися."],
            en: ["We're always glad to meet talented people. Write to careers@klarnote.com and tell us what you'd love to work on."],
            pl: ["Zawsze chętnie poznajemy utalentowanych ludzi. Napisz na careers@klarnote.com i opowiedz, czym chcesz się zajmować."],
            de: ["Wir freuen uns immer über talentierte Menschen. Schreiben Sie an careers@klarnote.com und erzählen Sie uns, woran Sie gern arbeiten möchten."],
            ro: ["Ne bucurăm mereu să cunoaștem oameni talentați. Scrie-ne la careers@klarnote.com și spune-ne la ce ți-ar plăcea să lucrezi."],
            cs: ["Talentované lidi rádi poznáme kdykoli. Napište nám na careers@klarnote.com a řekněte, čemu byste se chtěli věnovat."],
            sr: ["Uvek nam je drago da upoznamo talentovane ljude. Pišite nam na careers@klarnote.com i recite nam na čemu biste voleli da radite."],
            hu: ["Mindig örülünk a tehetséges embereknek. Írj a careers@klarnote.com címre, és meséld el, min dolgoznál szívesen."],
            ar: ["يسعدنا دائماً لقاء الموهوبين. راسلنا على careers@klarnote.com وأخبرنا بما تودّ العمل عليه."],
          es: ["Siempre nos alegra conocer gente con talento. Escriba a careers@klarnote.com y cuéntenos en qué le encantaría trabajar."],
          pt: ["Ficamos sempre contentes por conhecer pessoas talentosas. Escreva para careers@klarnote.com e diga-nos em que gostaria de trabalhar."],
          }) },
        cta,
      ],
    },

    blog: {
      hero: {
        eyebrow: t({ uk: "Блог", en: "Blog", pl: "Blog", de: "Blog", ro: "Blog", cs: "Blog", sr: "Blog", hu: "Blog", ar: "المدوّنة", es: "Blog", pt: "Blogue" }),
        title: t({
          uk: "Ідеї, оновлення та дослідження",
          en: "Ideas, updates and research",
          pl: "Pomysły, aktualności i badania",
          de: "Ideen, Updates und Forschung",
          ro: "Idei, noutăți și cercetare",
          cs: "Nápady, novinky a výzkum",
          sr: "Ideje, novosti i istraživanja",
          hu: "Ötletek, hírek és kutatás",
          ar: "أفكار وتحديثات وأبحاث",
          es: "Ideas, novedades e investigación",
          pt: "Ideias, novidades e investigação",
        }),
        sub: t({
          uk: "Як ми будуємо голосову документацію для медицини — без води.",
          en: "How we build voice documentation for healthcare — no fluff.",
          pl: "Jak budujemy głosową dokumentację dla medycyny — bez lania wody.",
          de: "Wie wir Sprachdokumentation für das Gesundheitswesen bauen — ohne Floskeln.",
          ro: "Cum construim documentația vocală pentru sănătate — fără vorbe goale.",
          cs: "Jak stavíme hlasovou dokumentaci pro zdravotnictví — bez omáčky.",
          sr: "Kako gradimo glasovnu dokumentaciju za zdravstvo — bez praznih priča.",
          hu: "Így építünk hangalapú dokumentációt az egészségügynek — felesleges körítés nélkül.",
          ar: "كيف نبني التوثيق الصوتي للرعاية الصحية — دون حشو.",
          es: "Cómo construimos la documentación por voz para la sanidad, sin rodeos.",
          pt: "Como construímos a documentação por voz para a saúde — sem rodeios.",
        }),
      },
      blocks: [
        { type: "posts", items: t({
          uk: [
              { tag: "Продукт", title: "Як амбулаторний скрайб змінює прийом", excerpt: "Розбираємо, що відбувається від першого слова пацієнта до структурованої нотатки.", date: "12 трав. 2026", read: "6 хв" },
              { tag: "Дослідження", title: "Чому ми підсвічуємо слова низької впевненості", excerpt: "Прозорість моделі робить перевірку швидшою та безпечнішою.", date: "28 квіт. 2026", read: "8 хв" },
              { tag: "Безпека", title: "Незмінний аудит на практиці", excerpt: "Як ми гарантуємо цілісність кожного запису в журналі подій.", date: "9 квіт. 2026", read: "5 хв" },
              { tag: "Інженерія", title: "Потокове ASR із низькою затримкою", excerpt: "Архітектура, що дає розпізнавання в реальному часі без втрати точності.", date: "21 бер. 2026", read: "10 хв" },
              { tag: "Продукт", title: "Шаблони, які економлять години", excerpt: "Як структури нотаток адаптуються під спеціальність.", date: "3 бер. 2026", read: "4 хв" },
              { tag: "Компанія", title: "Чому ми починали з радіології", excerpt: "Історія першого прототипу Klarnote і чому він спрацював.", date: "15 лют. 2026", read: "7 хв" },
            ],
          en: [
              { tag: "Product", title: "How the ambient scribe changes a visit", excerpt: "What happens from the patient's first word to a structured note.", date: "May 12, 2026", read: "6 min" },
              { tag: "Research", title: "Why we highlight low-confidence words", excerpt: "Model transparency makes review faster and safer.", date: "Apr 28, 2026", read: "8 min" },
              { tag: "Security", title: "Immutable audit in practice", excerpt: "How we guarantee the integrity of every entry in the event log.", date: "Apr 9, 2026", read: "5 min" },
              { tag: "Engineering", title: "Low-latency streaming ASR", excerpt: "The architecture behind real-time recognition without losing accuracy.", date: "Mar 21, 2026", read: "10 min" },
              { tag: "Product", title: "Templates that save hours", excerpt: "How note structures adapt to your specialty.", date: "Mar 3, 2026", read: "4 min" },
              { tag: "Company", title: "Why we started with radiology", excerpt: "The story of Klarnote's first prototype and why it worked.", date: "Feb 15, 2026", read: "7 min" },
            ],
          pl: [
              { tag: "Produkt", title: "Jak ambient scribe zmienia wizytę", excerpt: "Co dzieje się od pierwszego słowa pacjenta do ustrukturyzowanej notatki.", date: "12 maja 2026", read: "6 min" },
              { tag: "Badania", title: "Dlaczego podświetlamy słowa o niskiej pewności", excerpt: "Przejrzystość modelu sprawia, że weryfikacja jest szybsza i bezpieczniejsza.", date: "28 kwietnia 2026", read: "8 min" },
              { tag: "Bezpieczeństwo", title: "Niezmienny audyt w praktyce", excerpt: "Jak gwarantujemy integralność każdego wpisu w dzienniku zdarzeń.", date: "9 kwietnia 2026", read: "5 min" },
              { tag: "Inżynieria", title: "Strumieniowe ASR o niskiej latencji", excerpt: "Architektura rozpoznawania w czasie rzeczywistym bez utraty dokładności.", date: "21 marca 2026", read: "10 min" },
              { tag: "Produkt", title: "Szablony, które oszczędzają godziny", excerpt: "Jak struktury notatek dopasowują się do Twojej specjalizacji.", date: "3 marca 2026", read: "4 min" },
              { tag: "Firma", title: "Dlaczego zaczęliśmy od radiologii", excerpt: "Historia pierwszego prototypu Klarnote i tego, dlaczego zadziałał.", date: "15 lutego 2026", read: "7 min" },
            ],
          de: [
              { tag: "Produkt", title: "Wie der Ambient Scribe die Sprechstunde verändert", excerpt: "Was vom ersten Wort des Patienten bis zur strukturierten Notiz passiert.", date: "12. Mai 2026", read: "6 Min." },
              { tag: "Forschung", title: "Warum wir Wörter mit niedriger Konfidenz hervorheben", excerpt: "Modelltransparenz macht die Durchsicht schneller und sicherer.", date: "28. April 2026", read: "8 Min." },
              { tag: "Sicherheit", title: "Unveränderliches Audit in der Praxis", excerpt: "Wie wir die Integrität jedes Eintrags im Ereignisprotokoll garantieren.", date: "9. April 2026", read: "5 Min." },
              { tag: "Engineering", title: "Streaming-ASR mit niedriger Latenz", excerpt: "Die Architektur hinter Echtzeit-Erkennung ohne Genauigkeitsverlust.", date: "21. März 2026", read: "10 Min." },
              { tag: "Produkt", title: "Vorlagen, die Stunden sparen", excerpt: "Wie sich Notizstrukturen an Ihre Fachrichtung anpassen.", date: "3. März 2026", read: "4 Min." },
              { tag: "Unternehmen", title: "Warum wir mit der Radiologie begonnen haben", excerpt: "Die Geschichte des ersten Klarnote-Prototyps und warum er funktionierte.", date: "15. Februar 2026", read: "7 Min." },
            ],
          ro: [
              { tag: "Produs", title: "Cum schimbă scribul ambient o consultație", excerpt: "Ce se întâmplă de la primul cuvânt al pacientului până la o notă structurată.", date: "12 mai 2026", read: "6 min" },
              { tag: "Cercetare", title: "De ce evidențiem cuvintele cu încredere scăzută", excerpt: "Transparența modelului face verificarea mai rapidă și mai sigură.", date: "28 aprilie 2026", read: "8 min" },
              { tag: "Securitate", title: "Auditul imuabil în practică", excerpt: "Cum garantăm integritatea fiecărei intrări din jurnalul de evenimente.", date: "9 aprilie 2026", read: "5 min" },
              { tag: "Inginerie", title: "ASR în flux cu latență redusă", excerpt: "Arhitectura din spatele recunoașterii în timp real, fără pierdere de acuratețe.", date: "21 martie 2026", read: "10 min" },
              { tag: "Produs", title: "Șabloane care economisesc ore", excerpt: "Cum se adaptează structurile notelor la specialitatea ta.", date: "3 martie 2026", read: "4 min" },
              { tag: "Companie", title: "De ce am început cu radiologia", excerpt: "Povestea primului prototip Klarnote și de ce a funcționat.", date: "15 februarie 2026", read: "7 min" },
            ],
          cs: [
              { tag: "Produkt", title: "Jak ambientní scribe mění vyšetření", excerpt: "Co se děje od prvního slova pacienta po strukturovanou poznámku.", date: "12. května 2026", read: "6 min" },
              { tag: "Výzkum", title: "Proč zvýrazňujeme slova s nízkou jistotou", excerpt: "Díky transparentnosti modelu je kontrola rychlejší a bezpečnější.", date: "28. dubna 2026", read: "8 min" },
              { tag: "Bezpečnost", title: "Neměnný audit v praxi", excerpt: "Jak garantujeme integritu každého záznamu v protokolu událostí.", date: "9. dubna 2026", read: "5 min" },
              { tag: "Inženýrství", title: "Streamované ASR s nízkou latencí", excerpt: "Architektura rozpoznávání v reálném čase bez ztráty přesnosti.", date: "21. března 2026", read: "10 min" },
              { tag: "Produkt", title: "Šablony, které šetří hodiny", excerpt: "Jak se struktury poznámek přizpůsobují vašemu oboru.", date: "3. března 2026", read: "4 min" },
              { tag: "Firma", title: "Proč jsme začali radiologií", excerpt: "Příběh prvního prototypu Klarnote a proč fungoval.", date: "15. února 2026", read: "7 min" },
            ],
          sr: [
              { tag: "Proizvod", title: "Kako ambijentalni skrajb menja pregled", excerpt: "Šta se dešava od prve reči pacijenta do strukturirane beleške.", date: "12. maj 2026.", read: "6 min" },
              { tag: "Istraživanje", title: "Zašto ističemo reči niske pouzdanosti", excerpt: "Transparentnost modela čini proveru bržom i bezbednijom.", date: "28. april 2026.", read: "8 min" },
              { tag: "Bezbednost", title: "Nepromenljiva revizija u praksi", excerpt: "Kako garantujemo integritet svakog unosa u dnevniku događaja.", date: "9. april 2026.", read: "5 min" },
              { tag: "Inženjering", title: "Strimovani ASR niske latencije", excerpt: "Arhitektura koja omogućava prepoznavanje u realnom vremenu bez gubitka tačnosti.", date: "21. mart 2026.", read: "10 min" },
              { tag: "Proizvod", title: "Šabloni koji štede sate", excerpt: "Kako se strukture beležaka prilagođavaju vašoj specijalnosti.", date: "3. mart 2026.", read: "4 min" },
              { tag: "Kompanija", title: "Zašto smo počeli od radiologije", excerpt: "Priča o prvom prototipu Klarnotea i zašto je uspeo.", date: "15. februar 2026.", read: "7 min" },
            ],
          hu: [
              { tag: "Termék", title: "Hogyan alakítja át a vizitet az ambient scribe", excerpt: "Mi történik a beteg első szavától a strukturált jegyzetig.", date: "2026. máj. 12.", read: "6 perc" },
              { tag: "Kutatás", title: "Miért emeljük ki az alacsony megbízhatóságú szavakat", excerpt: "A modell átláthatósága gyorsabbá és biztonságosabbá teszi az ellenőrzést.", date: "2026. ápr. 28.", read: "8 perc" },
              { tag: "Biztonság", title: "Megmásíthatatlan audit a gyakorlatban", excerpt: "Így garantáljuk az eseménynapló minden bejegyzésének sértetlenségét.", date: "2026. ápr. 9.", read: "5 perc" },
              { tag: "Mérnökség", title: "Alacsony késleltetésű streaming ASR", excerpt: "A valós idejű felismerés architektúrája pontosságvesztés nélkül.", date: "2026. márc. 21.", read: "10 perc" },
              { tag: "Termék", title: "Sablonok, amelyek órákat spórolnak", excerpt: "Hogyan igazodnak a jegyzetstruktúrák a szakterületedhez.", date: "2026. márc. 3.", read: "4 perc" },
              { tag: "Cég", title: "Miért a radiológiával kezdtük", excerpt: "A Klarnote első prototípusának története, és hogy miért működött.", date: "2026. febr. 15.", read: "7 perc" },
            ],
          ar: [
              { tag: "المنتج", title: "كيف يغيّر المدوّن المحيطي المعاينة", excerpt: "ما يحدث من كلمة المريض الأولى إلى ملاحظة منظَّمة.", date: "12 مايو 2026", read: "6 دقائق" },
              { tag: "الأبحاث", title: "لماذا نُبرز الكلمات منخفضة الثقة", excerpt: "شفافية النموذج تجعل المراجعة أسرع وأكثر أماناً.", date: "28 أبريل 2026", read: "8 دقائق" },
              { tag: "الأمان", title: "التدقيق غير القابل للتغيير في الممارسة العملية", excerpt: "كيف نضمن سلامة كل إدخال في سجل الأحداث.", date: "9 أبريل 2026", read: "5 دقائق" },
              { tag: "الهندسة", title: "ASR متدفق منخفض الكمون", excerpt: "البنية وراء التعرّف الفوري دون فقدان الدقة.", date: "21 مارس 2026", read: "10 دقائق" },
              { tag: "المنتج", title: "قوالب توفّر ساعات", excerpt: "كيف تتكيّف بنى الملاحظات مع تخصصك.", date: "3 مارس 2026", read: "4 دقائق" },
              { tag: "الشركة", title: "لماذا بدأنا بالأشعة", excerpt: "قصة أول نموذج أولي من Klarnote ولماذا نجح.", date: "15 فبراير 2026", read: "7 دقائق" },
            ],
          es: [
            { tag: "Producto", title: "Cómo el escriba ambiental cambia una consulta", excerpt: "Qué ocurre desde la primera palabra del paciente hasta una nota estructurada.", date: "12 de mayo de 2026", read: "6 min" },
            { tag: "Investigación", title: "Por qué resaltamos las palabras de baja confianza", excerpt: "La transparencia del modelo hace la revisión más rápida y segura.", date: "28 de abril de 2026", read: "8 min" },
            { tag: "Seguridad", title: "La auditoría inmutable en la práctica", excerpt: "Cómo garantizamos la integridad de cada entrada del registro de eventos.", date: "9 de abril de 2026", read: "5 min" },
            { tag: "Ingeniería", title: "ASR en streaming de baja latencia", excerpt: "La arquitectura tras el reconocimiento en tiempo real sin perder precisión.", date: "21 de marzo de 2026", read: "10 min" },
            { tag: "Producto", title: "Plantillas que ahorran horas", excerpt: "Cómo las estructuras de nota se adaptan a su especialidad.", date: "3 de marzo de 2026", read: "4 min" },
            { tag: "Empresa", title: "Por qué empezamos por la radiología", excerpt: "La historia del primer prototipo de Klarnote y por qué funcionó.", date: "15 de febrero de 2026", read: "7 min" },
          ],
          pt: [
            { tag: "Produto", title: "Como o escriba ambiental muda uma consulta", excerpt: "O que acontece desde a primeira palavra do doente até uma nota estruturada.", date: "12 de maio de 2026", read: "6 min" },
            { tag: "Investigação", title: "Porque destacamos as palavras de baixa confiança", excerpt: "A transparência do modelo torna a revisão mais rápida e segura.", date: "28 de abril de 2026", read: "8 min" },
            { tag: "Segurança", title: "A auditoria imutável na prática", excerpt: "Como garantimos a integridade de cada entrada do registo de eventos.", date: "9 de abril de 2026", read: "5 min" },
            { tag: "Engenharia", title: "ASR em streaming de baixa latência", excerpt: "A arquitetura por trás do reconhecimento em tempo real sem perder precisão.", date: "21 de março de 2026", read: "10 min" },
            { tag: "Produto", title: "Modelos que poupam horas", excerpt: "Como as estruturas de nota se adaptam à sua especialidade.", date: "3 de março de 2026", read: "4 min" },
            { tag: "Empresa", title: "Porque começámos pela radiologia", excerpt: "A história do primeiro protótipo do Klarnote e porque resultou.", date: "15 de fevereiro de 2026", read: "7 min" },
          ],
        }) },
      ],
    },

    /* ───────────────────────── Legal ─────────────────────────
       The four legal documents moved to ./content-legal.js when they grew
       from six-paragraph placeholders into the real thing. Same reason this
       file exists at all: one content domain per module. */
    ...buildLegalPages(lang),
  };
}
