// content-product.js — Product-side marketing pages (features hub, security,
// product/scribe, product/dictate). Split from content.js; shared CTA block is
// passed in by content.js.

export function buildProductPages(lang, cta) {
  const t = (m) => m[lang] ?? m.en;
  return {
    /* ─────────────────────── Features overview ─────────────────────── */
    features: {
      hero: {
        eyebrow: t({
          uk: "Можливості",
          en: "Features",
          pl: "Funkcje",
          de: "Funktionen",
          ro: "Funcționalități",
          cs: "Funkce",
          sr: "Funkcije",
          hu: "Funkciók",
          ar: "الميزات",
        }),
        title: t({
          uk: "Усе для впевненої документації",
          en: "Everything for confident documentation",
          pl: "Wszystko dla pewnej dokumentacji",
          de: "Alles für eine sichere Dokumentation",
          ro: "Totul pentru o documentare sigură",
          cs: "Vše pro spolehlivou dokumentaci",
          sr: "Sve za pouzdanu dokumentaciju",
          hu: "Minden a magabiztos dokumentációhoz",
          ar: "كل ما يلزم لتوثيق واثق",
        }),
        sub: t({
          uk: "Від розпізнавання мови до підпису — повний цикл в одному застосунку.",
          en: "From speech recognition to signature — the full cycle in one app.",
          pl: "Od rozpoznawania mowy po podpis — pełny cykl w jednej aplikacji.",
          de: "Von der Spracherkennung bis zur Signatur — der gesamte Zyklus in einer App.",
          ro: "De la recunoașterea vorbirii până la semnătură — ciclul complet într-o singură aplicație.",
          cs: "Od rozpoznávání řeči po podpis — celý cyklus v jedné aplikaci.",
          sr: "Od prepoznavanja govora do potpisa — ceo ciklus u jednoj aplikaciji.",
          hu: "A beszédfelismeréstől az aláírásig — a teljes ciklus egyetlen alkalmazásban.",
          ar: "من التعرّف على الكلام إلى التوقيع — الدورة الكاملة في تطبيق واحد.",
        }),
      },
      blocks: [
        { type: "grid", cols: 3, link: true, items: t({
          uk: [
              { icon: "mic", title: "Розпізнавання в реальному часі", desc: "Потокове ASR на self-hosted Whisper із підсвічуванням слів низької впевненості.", path: "/features/recognition" },
              { icon: "keyboard", title: "Голосові команди", desc: "Понад 30 інтентів: нові абзаци, пунктуація, перехід між секціями, збереження.", path: "/features/commands" },
              { icon: "sliders", title: "Нормалізація медичного тексту", desc: "Тиск, пульс, дози й одиниці перетворюються детерміновано: «сто двадцять на вісімдесят» → «120/80».", path: "/features/normalization" },
              { icon: "sparkle", title: "Розумне автодоповнення", desc: "Контекстні підказки термінів, діагнозів і фраз.", path: "/features/autocomplete" },
              { icon: "layers", title: "Шаблони та структури", desc: "16 системних шаблонів плюс власні версіоновані шаблони закладу.", path: "/features/templates" },
              { icon: "history", title: "Версії та амендменти", desc: "Append-only історія, порівняння діфів, амендменти після підпису.", path: "/features/versions" },
              { icon: "sign", title: "Електронний підпис Дія / ІІТ", desc: "КЕП через Дія або ІІТ, підписаний PADES PDF, публічна перевірка.", path: "/features/signature" },
              { icon: "shield", title: "Аудит і відповідність", desc: "Хеш-ланцюговий журнал, нічна звірка цілісності, рольовий доступ.", path: "/features/audit" },
            ],
          en: [
              { icon: "mic", title: "Real-time recognition", desc: "Streaming ASR on self-hosted Whisper with low-confidence words highlighted.", path: "/features/recognition" },
              { icon: "keyboard", title: "Voice commands", desc: "30+ intents: new paragraph, punctuation, jump between sections, save draft.", path: "/features/commands" },
              { icon: "sliders", title: "Medical text normalization", desc: "Blood pressure, heart rate, doses and units rendered deterministically: \"one twenty over eighty\" → \"120/80\".", path: "/features/normalization" },
              { icon: "sparkle", title: "Smart autocomplete", desc: "Context-aware suggestions for terms, diagnoses and phrases.", path: "/features/autocomplete" },
              { icon: "layers", title: "Templates & structures", desc: "16 system templates plus your tenant's own versioned templates.", path: "/features/templates" },
              { icon: "history", title: "Versions & amendments", desc: "Append-only history, diff comparison, post-signature amendments.", path: "/features/versions" },
              { icon: "sign", title: "Дія / ІІТ e-signature", desc: "Qualified signature via Дія or ІІТ, signed PADES PDF, public verification.", path: "/features/signature" },
              { icon: "shield", title: "Audit & compliance", desc: "Hash-chained log, nightly integrity reconciliation, role-based access.", path: "/features/audit" },
            ],
          pl: [
              { icon: "mic", title: "Rozpoznawanie w czasie rzeczywistym", desc: "Strumieniowe ASR na self-hosted Whisper z wyróżnianiem słów o niskiej pewności.", path: "/features/recognition" },
              { icon: "keyboard", title: "Polecenia głosowe", desc: "Ponad 30 intencji: nowy akapit, interpunkcja, przechodzenie między sekcjami, zapis wersji roboczej.", path: "/features/commands" },
              { icon: "sliders", title: "Normalizacja tekstu medycznego", desc: "Ciśnienie, tętno, dawki i jednostki zapisywane deterministycznie: „sto dwadzieścia na osiemdziesiąt” → „120/80”.", path: "/features/normalization" },
              { icon: "sparkle", title: "Inteligentne autouzupełnianie", desc: "Kontekstowe podpowiedzi terminów, rozpoznań i fraz.", path: "/features/autocomplete" },
              { icon: "layers", title: "Szablony i struktury", desc: "16 szablonów systemowych oraz własne wersjonowane szablony placówki.", path: "/features/templates" },
              { icon: "history", title: "Wersje i poprawki", desc: "Historia append-only, porównywanie różnic, poprawki po podpisie.", path: "/features/versions" },
              { icon: "sign", title: "Podpis elektroniczny Дія / ІІТ", desc: "Kwalifikowany podpis przez Дія lub ІІТ, podpisany PDF PADES, publiczna weryfikacja.", path: "/features/signature" },
              { icon: "shield", title: "Audyt i zgodność", desc: "Dziennik z łańcuchem haszy, nocna weryfikacja integralności, dostęp oparty na rolach.", path: "/features/audit" },
            ],
          de: [
              { icon: "mic", title: "Echtzeit-Erkennung", desc: "Streaming-ASR auf self-hosted Whisper mit Hervorhebung von Wörtern mit geringer Konfidenz.", path: "/features/recognition" },
              { icon: "keyboard", title: "Sprachbefehle", desc: "Über 30 Intents: neuer Absatz, Interpunktion, Wechsel zwischen Abschnitten, Entwurf speichern.", path: "/features/commands" },
              { icon: "sliders", title: "Normalisierung medizinischer Texte", desc: "Blutdruck, Puls, Dosen und Einheiten werden deterministisch umgesetzt: „einhundertzwanzig zu achtzig“ → „120/80“.", path: "/features/normalization" },
              { icon: "sparkle", title: "Intelligente Autovervollständigung", desc: "Kontextabhängige Vorschläge für Begriffe, Diagnosen und Phrasen.", path: "/features/autocomplete" },
              { icon: "layers", title: "Vorlagen & Strukturen", desc: "16 Systemvorlagen plus eigene versionierte Vorlagen Ihrer Einrichtung.", path: "/features/templates" },
              { icon: "history", title: "Versionen & Nachträge", desc: "Append-only-Historie, Diff-Vergleich, Nachträge nach der Signatur.", path: "/features/versions" },
              { icon: "sign", title: "Дія / ІІТ E-Signatur", desc: "Qualifizierte Signatur über Дія oder ІІТ, signiertes PADES-PDF, öffentliche Prüfung.", path: "/features/signature" },
              { icon: "shield", title: "Audit & Compliance", desc: "Hash-verkettetes Protokoll, nächtlicher Integritätsabgleich, rollenbasierter Zugriff.", path: "/features/audit" },
            ],
          ro: [
              { icon: "mic", title: "Recunoaștere în timp real", desc: "ASR în flux pe Whisper self-hosted, cu evidențierea cuvintelor cu încredere scăzută.", path: "/features/recognition" },
              { icon: "keyboard", title: "Comenzi vocale", desc: "Peste 30 de intenții: paragraf nou, punctuație, navigare între secțiuni, salvarea ciornei.", path: "/features/commands" },
              { icon: "sliders", title: "Normalizarea textului medical", desc: "Tensiunea, pulsul, dozele și unitățile sunt redate determinist: „o sută douăzeci cu optzeci” → „120/80”.", path: "/features/normalization" },
              { icon: "sparkle", title: "Autocompletare inteligentă", desc: "Sugestii contextuale pentru termeni, diagnostice și expresii.", path: "/features/autocomplete" },
              { icon: "layers", title: "Șabloane și structuri", desc: "16 șabloane de sistem plus șabloanele versionate proprii ale instituției.", path: "/features/templates" },
              { icon: "history", title: "Versiuni și amendamente", desc: "Istoric append-only, comparare de diferențe, amendamente după semnare.", path: "/features/versions" },
              { icon: "sign", title: "Semnătură electronică Дія / ІІТ", desc: "Semnătură calificată prin Дія sau ІІТ, PDF PADES semnat, verificare publică.", path: "/features/signature" },
              { icon: "shield", title: "Audit și conformitate", desc: "Jurnal cu lanț de hash-uri, reconciliere nocturnă a integrității, acces bazat pe roluri.", path: "/features/audit" },
            ],
          cs: [
              { icon: "mic", title: "Rozpoznávání v reálném čase", desc: "Streamované ASR na self-hosted Whisper se zvýrazněním slov s nízkou jistotou.", path: "/features/recognition" },
              { icon: "keyboard", title: "Hlasové příkazy", desc: "Přes 30 intentů: nový odstavec, interpunkce, přechod mezi sekcemi, uložení konceptu.", path: "/features/commands" },
              { icon: "sliders", title: "Normalizace lékařského textu", desc: "Tlak, tep, dávky a jednotky se převádějí deterministicky: „sto dvacet na osmdesát“ → „120/80“.", path: "/features/normalization" },
              { icon: "sparkle", title: "Chytré automatické doplňování", desc: "Kontextové návrhy termínů, diagnóz a frází.", path: "/features/autocomplete" },
              { icon: "layers", title: "Šablony a struktury", desc: "16 systémových šablon plus vlastní verzované šablony vašeho zařízení.", path: "/features/templates" },
              { icon: "history", title: "Verze a dodatky", desc: "Append-only historie, porovnání rozdílů, dodatky po podpisu.", path: "/features/versions" },
              { icon: "sign", title: "Elektronický podpis Дія / ІІТ", desc: "Kvalifikovaný podpis přes Дія nebo ІІТ, podepsané PADES PDF, veřejné ověření.", path: "/features/signature" },
              { icon: "shield", title: "Audit a compliance", desc: "Hashově řetězený log, noční kontrola integrity, přístup podle rolí.", path: "/features/audit" },
            ],
          sr: [
              { icon: "mic", title: "Prepoznavanje u realnom vremenu", desc: "Striming ASR na self-hosted Whisper modelu sa isticanjem reči niske pouzdanosti.", path: "/features/recognition" },
              { icon: "keyboard", title: "Glasovne komande", desc: "Preko 30 intenta: novi pasus, interpunkcija, prelazak između sekcija, čuvanje nacrta.", path: "/features/commands" },
              { icon: "sliders", title: "Normalizacija medicinskog teksta", desc: "Pritisak, puls, doze i jedinice se zapisuju deterministički: „sto dvadeset sa osamdeset“ → „120/80“.", path: "/features/normalization" },
              { icon: "sparkle", title: "Pametno automatsko dopunjavanje", desc: "Kontekstualni predlozi termina, dijagnoza i fraza.", path: "/features/autocomplete" },
              { icon: "layers", title: "Šabloni i strukture", desc: "16 sistemskih šablona plus sopstveni verzionisani šabloni vaše ustanove.", path: "/features/templates" },
              { icon: "history", title: "Verzije i amandmani", desc: "Append-only istorija, poređenje razlika, amandmani nakon potpisa.", path: "/features/versions" },
              { icon: "sign", title: "Elektronski potpis Дія / ІІТ", desc: "Kvalifikovani potpis preko Дія ili ІІТ, potpisan PADES PDF, javna verifikacija.", path: "/features/signature" },
              { icon: "shield", title: "Revizija i usklađenost", desc: "Heš-lančani dnevnik, noćna provera integriteta, pristup zasnovan na ulogama.", path: "/features/audit" },
            ],
          hu: [
              { icon: "mic", title: "Valós idejű felismerés", desc: "Streaming ASR self-hosted Whisper alapon, az alacsony megbízhatóságú szavak kiemelésével.", path: "/features/recognition" },
              { icon: "keyboard", title: "Hangparancsok", desc: "Több mint 30 intent: új bekezdés, központozás, ugrás a szakaszok között, piszkozat mentése.", path: "/features/commands" },
              { icon: "sliders", title: "Orvosi szöveg normalizálása", desc: "Vérnyomás, pulzus, dózisok és mértékegységek determinisztikus átalakítása: „százhúsz per nyolcvan” → „120/80”.", path: "/features/normalization" },
              { icon: "sparkle", title: "Intelligens automatikus kiegészítés", desc: "Kontextusfüggő javaslatok kifejezésekre, diagnózisokra és fordulatokra.", path: "/features/autocomplete" },
              { icon: "layers", title: "Sablonok és struktúrák", desc: "16 rendszersablon, valamint az intézmény saját verziózott sablonjai.", path: "/features/templates" },
              { icon: "history", title: "Verziók és módosítások", desc: "Append-only előzmények, diff-összehasonlítás, aláírás utáni módosítások.", path: "/features/versions" },
              { icon: "sign", title: "Дія / ІІТ e-aláírás", desc: "Minősített aláírás Дія vagy ІІТ útján, aláírt PADES PDF, nyilvános ellenőrzés.", path: "/features/signature" },
              { icon: "shield", title: "Audit és megfelelőség", desc: "Hash-láncolt napló, éjszakai integritás-egyeztetés, szerepkör-alapú hozzáférés.", path: "/features/audit" },
            ],
          ar: [
              { icon: "mic", title: "التعرّف في الوقت الفعلي", desc: "نظام ASR متدفق على Whisper مستضاف ذاتيًا مع إبراز الكلمات منخفضة الثقة.", path: "/features/recognition" },
              { icon: "keyboard", title: "الأوامر الصوتية", desc: "أكثر من 30 نيّة: فقرة جديدة، وعلامات ترقيم، والتنقل بين الأقسام، وحفظ المسودة.", path: "/features/commands" },
              { icon: "sliders", title: "تطبيع النص الطبي", desc: "ضغط الدم ومعدل النبض والجرعات والوحدات تُحوَّل بشكل حتمي: «مئة وعشرون على ثمانين» → «120/80».", path: "/features/normalization" },
              { icon: "sparkle", title: "الإكمال التلقائي الذكي", desc: "اقتراحات مدركة للسياق للمصطلحات والتشخيصات والعبارات.", path: "/features/autocomplete" },
              { icon: "layers", title: "القوالب والبنى", desc: "16 قالبًا نظاميًا إضافةً إلى قوالب مؤسستك الخاصة ذات الإصدارات.", path: "/features/templates" },
              { icon: "history", title: "الإصدارات والتعديلات", desc: "سجل بالإضافة فقط، ومقارنة الفروق، وتعديلات بعد التوقيع.", path: "/features/versions" },
              { icon: "sign", title: "التوقيع الإلكتروني عبر Дія / ІІТ", desc: "توقيع مؤهَّل عبر Дія أو ІІТ، وملف PADES PDF موقَّع، وتحقق عام.", path: "/features/signature" },
              { icon: "shield", title: "التدقيق والامتثال", desc: "سجل مترابط بسلسلة تجزئة، ومطابقة سلامة ليلية، ووصول قائم على الأدوار.", path: "/features/audit" },
            ],
          }) },
        cta,
      ],
    },

    security: {
      hero: {
        eyebrow: t({
          uk: "Безпека",
          en: "Security",
          pl: "Bezpieczeństwo",
          de: "Sicherheit",
          ro: "Securitate",
          cs: "Bezpečnost",
          sr: "Bezbednost",
          hu: "Biztonság",
          ar: "الأمان",
        }),
        title: t({
          uk: "Безпека та приватність за замовчуванням",
          en: "Security and privacy by default",
          pl: "Bezpieczeństwo i prywatność domyślnie",
          de: "Sicherheit und Datenschutz standardmäßig",
          ro: "Securitate și confidențialitate în mod implicit",
          cs: "Bezpečnost a soukromí ve výchozím nastavení",
          sr: "Bezbednost i privatnost podrazumevano",
          hu: "Biztonság és adatvédelem alapértelmezésben",
          ar: "الأمان والخصوصية افتراضيًا",
        }),
        sub: t({
          uk: "Дані пацієнтів захищені на кожному етапі — від запису до архіву. Не на словах, а конструктивно: ізоляція тенантів у базі даних, незмінний хеш-ланцюговий аудит і моделі, що працюють лише на вашому обладнанні.",
          en: "Patient data is protected at every step — from recording to archive. Not by policy alone but by construction: tenant isolation in the database, an immutable hash-chained audit, and models that run only on your own hardware.",
          pl: "Dane pacjentów są chronione na każdym etapie — od nagrania po archiwum. Nie tylko polityką, lecz konstrukcyjnie: izolacja tenantów w bazie danych, niezmienny audyt z łańcuchem haszy oraz modele działające wyłącznie na własnym sprzęcie.",
          de: "Patientendaten sind in jedem Schritt geschützt — von der Aufnahme bis zum Archiv. Nicht nur per Richtlinie, sondern konstruktiv: Tenant-Isolation in der Datenbank, ein unveränderlicher hash-verketteter Audit-Trail und Modelle, die ausschließlich auf Ihrer eigenen Hardware laufen.",
          ro: "Datele pacienților sunt protejate la fiecare pas — de la înregistrare la arhivă. Nu doar prin politici, ci prin construcție: izolarea tenanților în baza de date, un audit imuabil cu lanț de hash-uri și modele care rulează exclusiv pe propriul hardware.",
          cs: "Data pacientů jsou chráněna v každém kroku — od nahrávky po archiv. Ne jen politikou, ale konstrukčně: izolace tenantů v databázi, neměnný hashově řetězený audit a modely běžící výhradně na vašem vlastním hardwaru.",
          sr: "Podaci pacijenata zaštićeni su u svakom koraku — od snimka do arhive. Ne samo politikom, već konstrukcijom: izolacija tenanata u bazi podataka, nepromenljiva heš-lančana revizija i modeli koji rade isključivo na vašem hardveru.",
          hu: "A betegadatok minden lépésben védettek — a felvételtől az archívumig. Nem csupán szabályzattal, hanem felépítésből adódóan: tenant-izoláció az adatbázisban, megváltoztathatatlan hash-láncolt audit, és kizárólag a saját hardverén futó modellek.",
          ar: "بيانات المرضى محمية في كل خطوة — من التسجيل إلى الأرشفة. ليس بالسياسات وحدها بل بالتصميم: عزل المستأجرين في قاعدة البيانات، وتدقيق غير قابل للتغيير مترابط بسلسلة تجزئة، ونماذج تعمل على أجهزتك الخاصة فقط.",
        }),
      },
      blocks: [
        { type: "grid", heading: t({
            uk: "Непорушні принципи",
            en: "Non-negotiable principles",
            pl: "Zasady bez kompromisów",
            de: "Nicht verhandelbare Prinzipien",
            ro: "Principii nenegociabile",
            cs: "Nepodkročitelné zásady",
            sr: "Principi bez kompromisa",
            hu: "Meg nem alkuvó alapelvek",
            ar: "مبادئ غير قابلة للتفاوض",
          }), cols: 3, items: t({
          uk: [
              { icon: "home", title: "Суверенітет даних", desc: "Жодне аудіо, транскрипт чи нотатка не надсилаються до сторонніх пропрієтарних API. Усе ASR і генерація працюють на self-hosted відкритих моделях." },
              { icon: "user", title: "Лікар у контурі", desc: "Система готує чернетку, але не діагностує й ніколи не фіналізує документ автоматично." },
              { icon: "layers", title: "Ізоляція тенантів", desc: "Код ніколи не фільтрує за тенантом — це робить база даних через row-level security. Відсутній фільтр не може призвести до витоку." },
              { icon: "history", title: "Захищений від підробки аудит", desc: "Append-only, хеш-ланцюговий журнал з контролем незмінності на рівні БД, що звіряється щоночі." },
              { icon: "save", title: "Шифрування", desc: "Аудіо й транскрипти шифруються під час передачі та зберігання." },
            ],
          en: [
              { icon: "home", title: "Data sovereignty", desc: "No audio, transcript or note is sent to any third-party proprietary API. All ASR and generation run on self-hosted, open-licensed models." },
              { icon: "user", title: "Clinician in the loop", desc: "The system drafts, it does not diagnose, and it never auto-finalizes a document." },
              { icon: "layers", title: "Tenant isolation", desc: "Application code never filters by tenant — the database does, via row-level security. A missing filter therefore can't leak data." },
              { icon: "history", title: "Tamper-evident audit", desc: "Append-only, hash-chained log with immutability enforced at the database level and reconciled nightly." },
              { icon: "save", title: "Encryption", desc: "Audio and transcripts are encrypted in transit and at rest." },
            ],
          pl: [
              { icon: "home", title: "Suwerenność danych", desc: "Żadne audio, transkrypcja ani notatka nie są wysyłane do zewnętrznych własnościowych API. Całe ASR i generowanie działają na self-hosted modelach o otwartych licencjach." },
              { icon: "user", title: "Lekarz w pętli decyzyjnej", desc: "System przygotowuje wersję roboczą, nie diagnozuje i nigdy nie finalizuje dokumentu automatycznie." },
              { icon: "layers", title: "Izolacja tenantów", desc: "Kod aplikacji nigdy nie filtruje po tenancie — robi to baza danych poprzez row-level security. Brakujący filtr nie może więc spowodować wycieku danych." },
              { icon: "history", title: "Audyt odporny na manipulacje", desc: "Dziennik append-only z łańcuchem haszy; niezmienność wymuszana na poziomie bazy danych i weryfikowana co noc." },
              { icon: "save", title: "Szyfrowanie", desc: "Audio i transkrypcje są szyfrowane podczas przesyłania i przechowywania." },
            ],
          de: [
              { icon: "home", title: "Datensouveränität", desc: "Kein Audio, Transkript oder keine Notiz wird an proprietäre Dritt-APIs gesendet. Das gesamte ASR und die Generierung laufen auf self-hosted Modellen mit offenen Lizenzen." },
              { icon: "user", title: "Arzt in der Schleife", desc: "Das System entwirft, es diagnostiziert nicht und finalisiert ein Dokument niemals automatisch." },
              { icon: "layers", title: "Tenant-Isolation", desc: "Der Anwendungscode filtert nie nach Tenant — das übernimmt die Datenbank per Row-Level Security. Ein fehlender Filter kann daher keine Daten preisgeben." },
              { icon: "history", title: "Manipulationssicherer Audit-Trail", desc: "Append-only, hash-verkettetes Protokoll; Unveränderlichkeit wird auf Datenbankebene erzwungen und nächtlich abgeglichen." },
              { icon: "save", title: "Verschlüsselung", desc: "Audio und Transkripte werden bei der Übertragung und im Ruhezustand verschlüsselt." },
            ],
          ro: [
              { icon: "home", title: "Suveranitatea datelor", desc: "Niciun fișier audio, transcript sau notă nu este trimis către API-uri proprietare terțe. Întregul ASR și generarea rulează pe modele self-hosted cu licențe deschise." },
              { icon: "user", title: "Medicul în buclă", desc: "Sistemul redactează ciorna, nu pune diagnostice și nu finalizează niciodată automat un document." },
              { icon: "layers", title: "Izolarea tenanților", desc: "Codul aplicației nu filtrează niciodată după tenant — o face baza de date, prin row-level security. Un filtru lipsă nu poate așadar scurge date." },
              { icon: "history", title: "Audit rezistent la falsificare", desc: "Jurnal append-only cu lanț de hash-uri; imuabilitate impusă la nivelul bazei de date și reconciliată în fiecare noapte." },
              { icon: "save", title: "Criptare", desc: "Audio și transcriptele sunt criptate în tranzit și în repaus." },
            ],
          cs: [
              { icon: "home", title: "Suverenita dat", desc: "Žádné audio, přepis ani poznámka se neodesílají do proprietárních API třetích stran. Veškeré ASR a generování běží na self-hosted modelech s otevřenými licencemi." },
              { icon: "user", title: "Lékař v rozhodovací smyčce", desc: "Systém připraví koncept, nediagnostikuje a nikdy dokument automaticky nefinalizuje." },
              { icon: "layers", title: "Izolace tenantů", desc: "Aplikační kód nikdy nefiltruje podle tenanta — dělá to databáze pomocí row-level security. Chybějící filtr proto nemůže způsobit únik dat." },
              { icon: "history", title: "Audit odolný proti manipulaci", desc: "Append-only, hashově řetězený log; neměnnost je vynucena na úrovni databáze a každou noc kontrolována." },
              { icon: "save", title: "Šifrování", desc: "Audio a přepisy jsou šifrovány při přenosu i při uložení." },
            ],
          sr: [
              { icon: "home", title: "Suverenitet podataka", desc: "Nijedan audio zapis, transkript ni beleška ne šalju se vlasničkim API-jima trećih strana. Celokupan ASR i generisanje rade na self-hosted modelima sa otvorenim licencama." },
              { icon: "user", title: "Lekar u petlji odlučivanja", desc: "Sistem priprema nacrt, ne postavlja dijagnoze i nikada automatski ne finalizuje dokument." },
              { icon: "layers", title: "Izolacija tenanata", desc: "Kod aplikacije nikada ne filtrira po tenantu — to radi baza podataka kroz row-level security. Izostavljen filter zato ne može izazvati curenje podataka." },
              { icon: "history", title: "Revizija otporna na izmene", desc: "Append-only, heš-lančani dnevnik; nepromenljivost se sprovodi na nivou baze podataka i proverava svake noći." },
              { icon: "save", title: "Šifrovanje", desc: "Audio i transkripti su šifrovani tokom prenosa i u mirovanju." },
            ],
          hu: [
              { icon: "home", title: "Adatszuverenitás", desc: "Semmilyen hang, átirat vagy jegyzet nem kerül külső, zárt API-khoz. A teljes ASR és a generálás self-hosted, nyílt licencű modelleken fut." },
              { icon: "user", title: "Az orvos a folyamat középpontjában", desc: "A rendszer piszkozatot készít, nem diagnosztizál, és soha nem véglegesít dokumentumot automatikusan." },
              { icon: "layers", title: "Tenant-izoláció", desc: "Az alkalmazáskód soha nem szűr tenant szerint — ezt az adatbázis végzi row-level security révén. Egy hiányzó szűrő így nem okozhat adatszivárgást." },
              { icon: "history", title: "Manipulációt jelző audit", desc: "Append-only, hash-láncolt napló; a megváltoztathatatlanságot az adatbázis szintjén kényszeríti ki, és minden éjjel egyezteti." },
              { icon: "save", title: "Titkosítás", desc: "A hang és az átiratok átvitel közben és tárolás alatt is titkosítva vannak." },
            ],
          ar: [
              { icon: "home", title: "سيادة البيانات", desc: "لا يُرسَل أي صوت أو نص منسوخ أو ملاحظة إلى أي واجهة API خاصة تابعة لطرف خارجي. جميع عمليات ASR والتوليد تعمل على نماذج مستضافة ذاتيًا ومفتوحة الترخيص." },
              { icon: "user", title: "الطبيب ضمن الحلقة", desc: "يُعِدّ النظام المسودة، ولا يُشخّص، ولا يُنهي أي مستند تلقائيًا أبدًا." },
              { icon: "layers", title: "عزل المستأجرين", desc: "لا يُصفّي كود التطبيق حسب المستأجر أبدًا — بل تفعل ذلك قاعدة البيانات عبر أمان مستوى الصفوف. لذا لا يمكن لغياب مُرشّح أن يُسرّب البيانات." },
              { icon: "history", title: "تدقيق يكشف التلاعب", desc: "سجل بالإضافة فقط ومترابط بسلسلة تجزئة، مع فرض عدم القابلية للتغيير على مستوى قاعدة البيانات ومطابقته كل ليلة." },
              { icon: "save", title: "التشفير", desc: "الصوت والنصوص المنسوخة مُشفَّرة أثناء النقل وفي حالة السكون." },
            ],
          }) },
        { type: "grid", heading: t({
            uk: "Ролі та доступ",
            en: "Roles & access",
            pl: "Role i dostęp",
            de: "Rollen & Zugriff",
            ro: "Roluri și acces",
            cs: "Role a přístup",
            sr: "Uloge i pristup",
            hu: "Szerepkörök és hozzáférés",
            ar: "الأدوار والوصول",
          }), sub: t({
            uk: "Доступ — заборонено за замовчуванням і перевіряється за явною матрицею дозволів на кожному ендпоінті. Свідомо немає крос-тенантної ролі суперадміністратора.",
            en: "Access is deny-by-default and checked against an explicit permission matrix on every endpoint. There is deliberately no cross-tenant super-admin role.",
            pl: "Dostęp jest domyślnie zablokowany i sprawdzany względem jawnej macierzy uprawnień na każdym endpoincie. Celowo nie ma roli superadministratora obejmującej wiele tenantów.",
            de: "Der Zugriff ist standardmäßig verweigert und wird an jedem Endpoint gegen eine explizite Berechtigungsmatrix geprüft. Eine tenant-übergreifende Superadmin-Rolle gibt es bewusst nicht.",
            ro: "Accesul este refuzat implicit și verificat pe fiecare endpoint față de o matrice explicită de permisiuni. În mod deliberat nu există un rol de super-admin peste mai mulți tenanți.",
            cs: "Přístup je ve výchozím stavu odepřen a na každém endpointu se ověřuje proti explicitní matici oprávnění. Záměrně neexistuje role superadministrátora napříč tenanty.",
            sr: "Pristup je podrazumevano odbijen i na svakom endpointu se proverava prema eksplicitnoj matrici dozvola. Namerno ne postoji superadministratorska uloga koja obuhvata više tenanata.",
            hu: "A hozzáférés alapértelmezetten tiltott, és minden endpointon explicit jogosultsági mátrix alapján ellenőrzött. Szándékosan nincs tenantokon átívelő szuperadmin szerepkör.",
            ar: "الوصول مرفوض افتراضيًا ويُتحقَّق منه مقابل مصفوفة صلاحيات صريحة في كل نقطة نهاية. ولا يوجد عمدًا دور مسؤول أعلى يمتد عبر المستأجرين.",
          }),
          cols: 3, items: t({
          uk: [
              { icon: "user", title: "Лікар (clinician)", desc: "Диктує, генерує, редагує, фіналізує та підписує нотатки." },
              { icon: "heart", title: "Медсестра (nurse)", desc: "Та сама клінічна поверхня, що й у лікаря, окрім підписання звітів." },
              { icon: "settings", title: "Адміністратор тенанта", desc: "Онбординг і деактивація користувачів, скидання MFA, налаштування, читання аудиту." },
              { icon: "eye", title: "Аудитор (auditor)", desc: "Лише читання аудиту та контексту тенанта — жодних записів." },
              { icon: "bot", title: "Сервіс (service)", desc: "Машинна ідентичність для внутрішніх сервісів; без людських операцій." },
            ],
          en: [
              { icon: "user", title: "Clinician", desc: "Dictate, generate, edit, finalize and sign notes." },
              { icon: "heart", title: "Nurse", desc: "The same clinical surface as a clinician, minus report signing." },
              { icon: "settings", title: "Tenant admin", desc: "User onboarding and deactivation, MFA reset, settings, audit read." },
              { icon: "eye", title: "Auditor", desc: "Read-only audit and tenant context — no writes anywhere." },
              { icon: "bot", title: "Service", desc: "Machine identity for internal services; no human-facing operations." },
            ],
          pl: [
              { icon: "user", title: "Lekarz", desc: "Dyktuje, generuje, edytuje, finalizuje i podpisuje notatki." },
              { icon: "heart", title: "Pielęgniarka", desc: "Ta sama powierzchnia kliniczna co u lekarza, bez podpisywania raportów." },
              { icon: "settings", title: "Administrator tenanta", desc: "Wdrażanie i dezaktywacja użytkowników, reset MFA, ustawienia, odczyt audytu." },
              { icon: "eye", title: "Audytor", desc: "Audyt i kontekst tenanta tylko do odczytu — żadnych zapisów." },
              { icon: "bot", title: "Usługa (service)", desc: "Tożsamość maszynowa dla usług wewnętrznych; żadnych operacji przeznaczonych dla ludzi." },
            ],
          de: [
              { icon: "user", title: "Arzt", desc: "Diktiert, generiert, bearbeitet, finalisiert und signiert Notizen." },
              { icon: "heart", title: "Pflegekraft", desc: "Dieselbe klinische Oberfläche wie beim Arzt, ohne das Signieren von Berichten." },
              { icon: "settings", title: "Tenant-Admin", desc: "Onboarding und Deaktivierung von Benutzern, MFA-Reset, Einstellungen, Lesezugriff auf den Audit." },
              { icon: "eye", title: "Auditor", desc: "Nur-Lese-Zugriff auf Audit und Tenant-Kontext — keinerlei Schreibzugriffe." },
              { icon: "bot", title: "Service", desc: "Maschinenidentität für interne Dienste; keine Operationen mit Benutzerkontakt." },
            ],
          ro: [
              { icon: "user", title: "Medic", desc: "Dictează, generează, editează, finalizează și semnează notele." },
              { icon: "heart", title: "Asistent medical", desc: "Aceeași suprafață clinică precum medicul, fără semnarea rapoartelor." },
              { icon: "settings", title: "Administrator de tenant", desc: "Integrarea și dezactivarea utilizatorilor, resetarea MFA, setări, citirea auditului." },
              { icon: "eye", title: "Auditor", desc: "Audit și context de tenant doar în citire — fără nicio scriere." },
              { icon: "bot", title: "Serviciu (service)", desc: "Identitate de mașină pentru serviciile interne; fără operațiuni destinate utilizatorilor." },
            ],
          cs: [
              { icon: "user", title: "Lékař", desc: "Diktuje, generuje, upravuje, finalizuje a podepisuje poznámky." },
              { icon: "heart", title: "Zdravotní sestra", desc: "Stejné klinické prostředí jako lékař, kromě podepisování zpráv." },
              { icon: "settings", title: "Administrátor tenantu", desc: "Onboarding a deaktivace uživatelů, reset MFA, nastavení, čtení auditu." },
              { icon: "eye", title: "Auditor", desc: "Audit a kontext tenantu pouze pro čtení — žádné zápisy." },
              { icon: "bot", title: "Služba (service)", desc: "Strojová identita pro interní služby; žádné operace určené lidem." },
            ],
          sr: [
              { icon: "user", title: "Lekar", desc: "Diktira, generiše, uređuje, finalizuje i potpisuje beleške." },
              { icon: "heart", title: "Medicinska sestra", desc: "Ista klinička površina kao kod lekara, bez potpisivanja izveštaja." },
              { icon: "settings", title: "Administrator tenanta", desc: "Uvođenje i deaktivacija korisnika, reset MFA, podešavanja, čitanje revizije." },
              { icon: "eye", title: "Revizor", desc: "Revizija i kontekst tenanta samo za čitanje — bez ikakvog upisa." },
              { icon: "bot", title: "Servis (service)", desc: "Mašinski identitet za interne servise; bez operacija namenjenih ljudima." },
            ],
          hu: [
              { icon: "user", title: "Orvos", desc: "Diktál, generál, szerkeszt, véglegesít és aláír jegyzeteket." },
              { icon: "heart", title: "Ápoló", desc: "Ugyanaz a klinikai felület, mint az orvosé, a leletek aláírása nélkül." },
              { icon: "settings", title: "Tenant-adminisztrátor", desc: "Felhasználók bevezetése és deaktiválása, MFA-visszaállítás, beállítások, audit olvasása." },
              { icon: "eye", title: "Auditor", desc: "Csak olvasható audit és tenant-kontextus — sehol semmilyen írás." },
              { icon: "bot", title: "Szolgáltatás (service)", desc: "Gépi identitás a belső szolgáltatásokhoz; emberi műveletek nélkül." },
            ],
          ar: [
              { icon: "user", title: "طبيب", desc: "إملاء الملاحظات وتوليدها وتحريرها وإنهاؤها وتوقيعها." },
              { icon: "heart", title: "ممرّض", desc: "نفس الواجهة السريرية للطبيب، باستثناء توقيع التقارير." },
              { icon: "settings", title: "مسؤول المستأجر", desc: "إعداد المستخدمين وتعطيلهم، وإعادة ضبط MFA، والإعدادات، وقراءة التدقيق." },
              { icon: "eye", title: "مدقّق", desc: "تدقيق وسياق مستأجر للقراءة فقط — دون أي كتابة في أي مكان." },
              { icon: "bot", title: "خدمة", desc: "هوية آلية للخدمات الداخلية؛ دون عمليات موجَّهة للبشر." },
            ],
          }) },
        { type: "prose", heading: t({
            uk: "Доступ до чужих записів",
            en: "Access to colleagues' records",
            pl: "Dostęp do dokumentacji innych lekarzy",
            de: "Zugriff auf Einträge von Kollegen",
            ro: "Accesul la înregistrările colegilor",
            cs: "Přístup k záznamům kolegů",
            sr: "Pristup zapisima kolega",
            hu: "Hozzáférés kollégák dokumentumaihoz",
            ar: "الوصول إلى سجلات الزملاء",
          }),
          paragraphs: t({
            uk: ["Доступ до звіту іншого лікаря вимагає явно задекларованої мети — клінічна спадковість, аудит, юридична потреба, контроль якості чи консультація. Ця мета фіксується в журналі аудиту.",
               "Сніпети, показані будь-кому поза лікувальною командою, очищаються від персональних даних — як другий рубіж захисту за рольовою перевіркою. Записи в журналі аудиту містять лише ідентифікатори, ніколи клінічний зміст, тож сам аудит не може стати джерелом витоку."],
            en: ["Opening a colleague's report requires an explicitly declared purpose — clinical continuity, audit, legal, QA review or consultation. That purpose is captured into the audit trail.",
               "Snippets shown to anyone outside the treatment team are PII-redacted as a second line of defense behind the role check. Audit entries carry IDs only, never clinical content, so the audit trail can't itself become a data leak."],
            pl: ["Otwarcie raportu innego lekarza wymaga jawnie zadeklarowanego celu — ciągłość leczenia, audyt, potrzeba prawna, kontrola jakości lub konsultacja. Cel ten jest zapisywany w dzienniku audytu.",
               "Fragmenty pokazywane komukolwiek spoza zespołu leczącego są oczyszczane z danych osobowych — jako druga linia obrony za kontrolą ról. Wpisy audytu zawierają wyłącznie identyfikatory, nigdy treść kliniczną, więc sam dziennik audytu nie może stać się źródłem wycieku."],
            de: ["Das Öffnen des Berichts eines Kollegen erfordert einen explizit angegebenen Zweck — klinische Kontinuität, Audit, rechtliche Notwendigkeit, Qualitätsprüfung oder Konsultation. Dieser Zweck wird im Audit-Trail festgehalten.",
               "Ausschnitte, die Personen außerhalb des Behandlungsteams angezeigt werden, werden von personenbezogenen Daten bereinigt — als zweite Verteidigungslinie hinter der Rollenprüfung. Audit-Einträge enthalten nur IDs, nie klinische Inhalte, sodass der Audit-Trail selbst nicht zum Datenleck werden kann."],
            ro: ["Deschiderea raportului unui coleg necesită un scop declarat explicit — continuitate clinică, audit, necesitate juridică, control al calității sau consult. Acest scop este consemnat în jurnalul de audit.",
               "Fragmentele afișate oricui din afara echipei de tratament sunt curățate de date personale — ca a doua linie de apărare după verificarea rolului. Intrările de audit conțin doar identificatori, niciodată conținut clinic, astfel încât jurnalul de audit nu poate deveni el însuși o sursă de scurgere."],
            cs: ["Otevření zprávy kolegy vyžaduje výslovně deklarovaný účel — klinickou návaznost, audit, právní potřebu, kontrolu kvality nebo konzultaci. Tento účel se zaznamenává do auditní stopy.",
               "Úryvky zobrazené komukoli mimo ošetřující tým jsou zbaveny osobních údajů — jako druhá linie obrany za kontrolou rolí. Auditní záznamy obsahují pouze identifikátory, nikdy klinický obsah, takže se auditní stopa sama nemůže stát zdrojem úniku."],
            sr: ["Otvaranje izveštaja kolege zahteva izričito deklarisanu svrhu — klinički kontinuitet, reviziju, pravnu potrebu, kontrolu kvaliteta ili konsultaciju. Ta svrha se beleži u revizorski trag.",
               "Isečci prikazani bilo kome van tima koji leči pacijenta očišćeni su od ličnih podataka — kao druga linija odbrane iza provere uloga. Revizorski zapisi sadrže samo identifikatore, nikada klinički sadržaj, pa sam revizorski trag ne može postati izvor curenja podataka."],
            hu: ["Egy kolléga leletének megnyitásához kifejezetten megjelölt cél szükséges — klinikai folytonosság, audit, jogi szükséglet, minőség-ellenőrzés vagy konzultáció. Ez a cél bekerül az auditnaplóba.",
               "A kezelőcsapaton kívül bárkinek megjelenített részletekből eltávolítjuk a személyes adatokat — második védelmi vonalként a szerepkör-ellenőrzés mögött. Az auditbejegyzések csak azonosítókat tartalmaznak, klinikai tartalmat soha, így maga az auditnapló sem válhat adatszivárgás forrásává."],
            ar: ["يتطلب فتح تقرير زميل غرضًا مُعلَنًا صراحةً — الاستمرارية السريرية، أو التدقيق، أو الأسباب القانونية، أو مراجعة ضمان الجودة، أو الاستشارة. ويُسجَّل هذا الغرض في سجل التدقيق.",
               "المقتطفات المعروضة لأي شخص خارج فريق العلاج تُحجب منها البيانات الشخصية كخط دفاع ثانٍ خلف فحص الأدوار. ولا تحمل إدخالات التدقيق سوى المعرّفات، ولا تحمل أبدًا محتوى سريريًا، لذا لا يمكن لسجل التدقيق نفسه أن يصبح مصدر تسرّب للبيانات."],
          }) },
        { type: "faq", heading: t({
            uk: "Часті запитання",
            en: "FAQ",
            pl: "Najczęstsze pytania",
            de: "Häufige Fragen",
            ro: "Întrebări frecvente",
            cs: "Časté dotazy",
            sr: "Česta pitanja",
            hu: "Gyakori kérdések",
            ar: "الأسئلة الشائعة",
          }), items: t({
          uk: [
              { q: "Чи надсилаються дані пацієнтів до зовнішніх AI-сервісів?", a: "Ні. Усе розпізнавання мови та генерація нотаток виконуються на self-hosted моделях з відкритими ліцензіями. Жодне аудіо, транскрипт чи нотатка не залишають вашого розгортання." },
              { q: "Де зберігаються дані пацієнтів?", a: "У межах узгоджених із закладом юрисдикцій (регіон ЄС/України або суверенний хостинг), із шифруванням під час передачі та зберігання." },
              { q: "Як забезпечується ізоляція між клініками?", a: "Через row-level security у базі даних, а не у коді застосунку. Кожна клініка — окремий тенант із жорсткою ізоляцією на рівні БД." },
              { q: "Чи можна перевірити цілісність аудиту?", a: "Так. Журнал append-only та хеш-ланцюговий; нічний звіряльник проходить ланцюг і сповіщає про будь-яке розходження. Цілісність також можна перевірити на сторінці перевірки." },
              { q: "Що з багатофакторною автентифікацією?", a: "Механізм MFA вже вбудовано. Під час пілота він вимкнений політикою; повторне ввімкнення — це конфігурація плюс флоу реєстрації." },
              { q: "Хто має доступ до записів?", a: "Лише авторизовані ролі в межах закладу, за принципом найменших привілеїв; доступ до чужих записів потребує задекларованої мети." },
            ],
          en: [
              { q: "Is patient data sent to external AI services?", a: "No. All speech recognition and note generation run on self-hosted, open-licensed models. No audio, transcript or note leaves your deployment." },
              { q: "Where is patient data stored?", a: "Within jurisdictions agreed with your organization (EU/Ukraine-region or sovereign hosting), encrypted in transit and at rest." },
              { q: "How is isolation between clinics enforced?", a: "Via row-level security in the database, not in application code. Each clinic is a separate tenant with hard isolation at the database layer." },
              { q: "Can audit integrity be verified?", a: "Yes. The log is append-only and hash-chained; a nightly reconciler walks the chain and alerts on any divergence. Integrity can also be checked on the verify page." },
              { q: "What about multi-factor authentication?", a: "MFA is already wired in. It is off by pilot policy today; re-enabling it is a configuration plus an enrollment flow." },
              { q: "Who can access records?", a: "Only authorized roles within your organization, on a least-privilege basis; accessing a colleague's record requires a declared purpose." },
            ],
          pl: [
              { q: "Czy dane pacjentów są wysyłane do zewnętrznych usług AI?", a: "Nie. Całe rozpoznawanie mowy i generowanie notatek działają na self-hosted modelach o otwartych licencjach. Żadne audio, transkrypcja ani notatka nie opuszczają Waszego wdrożenia." },
              { q: "Gdzie przechowywane są dane pacjentów?", a: "W jurysdykcjach uzgodnionych z placówką (region UE/Ukrainy lub hosting suwerenny), z szyfrowaniem podczas przesyłania i przechowywania." },
              { q: "Jak wymuszana jest izolacja między klinikami?", a: "Poprzez row-level security w bazie danych, a nie w kodzie aplikacji. Każda klinika to osobny tenant z twardą izolacją na poziomie bazy danych." },
              { q: "Czy można zweryfikować integralność audytu?", a: "Tak. Dziennik jest append-only i połączony łańcuchem haszy; nocny mechanizm przechodzi łańcuch i alarmuje o każdej rozbieżności. Integralność można też sprawdzić na stronie weryfikacji." },
              { q: "A co z uwierzytelnianiem wieloskładnikowym?", a: "MFA jest już wbudowane. Obecnie jest wyłączone polityką pilotażu; ponowne włączenie to konfiguracja plus proces rejestracji." },
              { q: "Kto ma dostęp do dokumentacji?", a: "Wyłącznie uprawnione role w obrębie placówki, zgodnie z zasadą najmniejszych uprawnień; dostęp do dokumentacji innego lekarza wymaga zadeklarowanego celu." },
            ],
          de: [
              { q: "Werden Patientendaten an externe KI-Dienste gesendet?", a: "Nein. Die gesamte Spracherkennung und Notizgenerierung laufen auf self-hosted Modellen mit offenen Lizenzen. Kein Audio, Transkript oder keine Notiz verlässt Ihre Umgebung." },
              { q: "Wo werden Patientendaten gespeichert?", a: "In mit Ihrer Einrichtung vereinbarten Jurisdiktionen (EU/Ukraine-Region oder souveränes Hosting), verschlüsselt bei Übertragung und im Ruhezustand." },
              { q: "Wie wird die Isolation zwischen Kliniken durchgesetzt?", a: "Über Row-Level Security in der Datenbank, nicht im Anwendungscode. Jede Klinik ist ein eigener Tenant mit harter Isolation auf Datenbankebene." },
              { q: "Kann die Integrität des Audits überprüft werden?", a: "Ja. Das Protokoll ist append-only und hash-verkettet; ein nächtlicher Abgleich durchläuft die Kette und meldet jede Abweichung. Die Integrität lässt sich auch auf der Prüfseite kontrollieren." },
              { q: "Wie steht es um Multi-Faktor-Authentifizierung?", a: "MFA ist bereits eingebaut. Aktuell ist es per Pilot-Richtlinie deaktiviert; die Reaktivierung ist eine Konfiguration plus ein Enrollment-Flow." },
              { q: "Wer hat Zugriff auf die Einträge?", a: "Nur autorisierte Rollen innerhalb Ihrer Einrichtung, nach dem Prinzip der geringsten Rechte; der Zugriff auf den Eintrag eines Kollegen erfordert einen angegebenen Zweck." },
            ],
          ro: [
              { q: "Sunt trimise datele pacienților către servicii AI externe?", a: "Nu. Toată recunoașterea vorbirii și generarea notelor rulează pe modele self-hosted cu licențe deschise. Niciun fișier audio, transcript sau notă nu părăsește instalarea dumneavoastră." },
              { q: "Unde sunt stocate datele pacienților?", a: "În jurisdicțiile convenite cu instituția dumneavoastră (regiunea UE/Ucraina sau găzduire suverană), criptate în tranzit și în repaus." },
              { q: "Cum este asigurată izolarea între clinici?", a: "Prin row-level security în baza de date, nu în codul aplicației. Fiecare clinică este un tenant separat, cu izolare strictă la nivelul bazei de date." },
              { q: "Poate fi verificată integritatea auditului?", a: "Da. Jurnalul este append-only și legat prin lanț de hash-uri; un proces nocturn de reconciliere parcurge lanțul și alertează la orice divergență. Integritatea poate fi verificată și pe pagina de verificare." },
              { q: "Ce se întâmplă cu autentificarea multi-factor?", a: "MFA este deja integrat. În prezent este dezactivat prin politica pilotului; reactivarea înseamnă o configurare plus un flux de înrolare." },
              { q: "Cine poate accesa înregistrările?", a: "Doar rolurile autorizate din cadrul instituției, pe principiul privilegiului minim; accesarea înregistrării unui coleg necesită un scop declarat." },
            ],
          cs: [
              { q: "Odesílají se data pacientů do externích AI služeb?", a: "Ne. Veškeré rozpoznávání řeči i generování poznámek běží na self-hosted modelech s otevřenými licencemi. Žádné audio, přepis ani poznámka neopouští vaše nasazení." },
              { q: "Kde jsou data pacientů uložena?", a: "V jurisdikcích dohodnutých s vaším zařízením (region EU/Ukrajina nebo suverénní hosting), šifrovaná při přenosu i při uložení." },
              { q: "Jak je zajištěna izolace mezi klinikami?", a: "Pomocí row-level security v databázi, nikoli v aplikačním kódu. Každá klinika je samostatný tenant s tvrdou izolací na úrovni databáze." },
              { q: "Lze ověřit integritu auditu?", a: "Ano. Log je append-only a hashově řetězený; noční kontrola prochází řetěz a upozorní na jakoukoli odchylku. Integritu lze ověřit i na ověřovací stránce." },
              { q: "Jak je to s vícefaktorovým ověřováním?", a: "MFA je již zabudováno. V rámci pilotní politiky je nyní vypnuto; opětovné zapnutí je otázkou konfigurace a registračního flow." },
              { q: "Kdo má přístup k záznamům?", a: "Pouze oprávněné role v rámci zařízení, podle principu nejmenších oprávnění; přístup k záznamu kolegy vyžaduje deklarovaný účel." },
            ],
          sr: [
              { q: "Da li se podaci pacijenata šalju spoljnim AI servisima?", a: "Ne. Celokupno prepoznavanje govora i generisanje beležaka rade na self-hosted modelima sa otvorenim licencama. Nijedan audio zapis, transkript ni beleška ne napuštaju vaše okruženje." },
              { q: "Gde se čuvaju podaci pacijenata?", a: "U jurisdikcijama dogovorenim sa vašom ustanovom (region EU/Ukrajina ili suvereni hosting), šifrovani tokom prenosa i u mirovanju." },
              { q: "Kako se sprovodi izolacija između klinika?", a: "Kroz row-level security u bazi podataka, a ne u kodu aplikacije. Svaka klinika je zaseban tenant sa strogom izolacijom na nivou baze podataka." },
              { q: "Da li se integritet revizije može proveriti?", a: "Da. Dnevnik je append-only i heš-lančan; noćni proces prolazi kroz lanac i upozorava na svako odstupanje. Integritet se može proveriti i na stranici za verifikaciju." },
              { q: "Šta je sa višefaktorskom autentifikacijom?", a: "MFA je već ugrađen. Trenutno je isključen politikom pilota; ponovno uključivanje je konfiguracija plus tok registracije." },
              { q: "Ko može da pristupi zapisima?", a: "Samo ovlašćene uloge u okviru ustanove, po principu najmanjih privilegija; pristup zapisu kolege zahteva deklarisanu svrhu." },
            ],
          hu: [
              { q: "Kerülnek betegadatok külső AI-szolgáltatásokhoz?", a: "Nem. A teljes beszédfelismerés és jegyzetgenerálás self-hosted, nyílt licencű modelleken fut. Semmilyen hang, átirat vagy jegyzet nem hagyja el az Ön telepítését." },
              { q: "Hol tárolódnak a betegadatok?", a: "Az intézménnyel egyeztetett joghatóságokon belül (EU/Ukrajna régió vagy szuverén hoszting), átvitel közben és tárolás alatt titkosítva." },
              { q: "Hogyan biztosított az elkülönítés a klinikák között?", a: "Row-level security révén az adatbázisban, nem az alkalmazáskódban. Minden klinika külön tenant, kemény izolációval az adatbázis szintjén." },
              { q: "Ellenőrizhető az audit integritása?", a: "Igen. A napló append-only és hash-láncolt; egy éjszakai egyeztető végigjárja a láncot, és minden eltérésre riaszt. Az integritás az ellenőrző oldalon is vizsgálható." },
              { q: "Mi a helyzet a többfaktoros hitelesítéssel?", a: "Az MFA már be van építve. A pilot szabályzata szerint jelenleg ki van kapcsolva; az újbóli bekapcsolás egy konfiguráció és egy regisztrációs folyamat." },
              { q: "Ki férhet hozzá a dokumentumokhoz?", a: "Csak az intézményen belüli jogosult szerepkörök, a legkisebb jogosultság elve alapján; egy kolléga dokumentumának megnyitásához megjelölt cél szükséges." },
            ],
          ar: [
              { q: "هل تُرسَل بيانات المرضى إلى خدمات ذكاء اصطناعي خارجية؟", a: "لا. تعمل جميع عمليات التعرّف على الكلام وتوليد الملاحظات على نماذج مستضافة ذاتيًا ومفتوحة الترخيص. ولا يغادر أي صوت أو نص منسوخ أو ملاحظة بيئة النشر لديك." },
              { q: "أين تُخزَّن بيانات المرضى؟", a: "ضمن الولايات القضائية المتفق عليها مع مؤسستك (منطقة الاتحاد الأوروبي/أوكرانيا أو استضافة سيادية)، مُشفَّرة أثناء النقل وفي حالة السكون." },
              { q: "كيف يُفرَض العزل بين العيادات؟", a: "عبر أمان مستوى الصفوف في قاعدة البيانات لا في كود التطبيق. كل عيادة مستأجر منفصل بعزل صارم على مستوى قاعدة البيانات." },
              { q: "هل يمكن التحقق من سلامة التدقيق؟", a: "نعم. السجل بالإضافة فقط ومترابط بسلسلة تجزئة؛ وتمرّ أداة مطابقة ليلية عبر السلسلة وتنبّه عند أي تباعد. كما يمكن فحص السلامة في صفحة التحقق." },
              { q: "ماذا عن المصادقة متعددة العوامل؟", a: "إن المصادقة متعددة العوامل (MFA) مدمجة بالفعل. وهي مُعطَّلة اليوم بموجب سياسة التجربة؛ وإعادة تفعيلها مسألة تهيئة إضافةً إلى مسار تسجيل." },
              { q: "من يمكنه الوصول إلى السجلات؟", a: "فقط الأدوار المصرَّح لها داخل مؤسستك، وفق مبدأ الحد الأدنى من الامتيازات؛ ويتطلب الوصول إلى سجل زميل غرضًا مُعلَنًا." },
            ],
          }) },
        cta,
      ],
    },

    /* ─────────────────────── Products ─────────────────────── */
    "product/scribe": {
      hero: {
        eyebrow: "Scribe",
        title: t({
          uk: "Амбулаторний скрайб",
          en: "Ambient scribe",
          pl: "Ambientowy skryba",
          de: "Ambient-Scribe",
          ro: "Scrib ambiental",
          cs: "Ambientní zapisovatel",
          sr: "Ambijentalni zapisničar",
          hu: "Ambiens írnok",
          ar: "المدوّن المحيطي",
        }),
        sub: t({
          uk: "Веде прийом разом з вами: фіксує розмову з пацієнтом, формує структуровану нотатку та підказує наступні кроки.",
          en: "Runs the visit with you: captures the patient conversation, builds a structured note and suggests next steps.",
          pl: "Prowadzi wizytę razem z Tobą: rejestruje rozmowę z pacjentem, tworzy ustrukturyzowaną notatkę i podpowiada kolejne kroki.",
          de: "Begleitet die Sprechstunde mit Ihnen: erfasst das Patientengespräch, erstellt eine strukturierte Notiz und schlägt nächste Schritte vor.",
          ro: "Conduce consultația împreună cu dumneavoastră: captează conversația cu pacientul, construiește o notă structurată și sugerează pașii următori.",
          cs: "Vede návštěvu s vámi: zachycuje rozhovor s pacientem, sestavuje strukturovanou poznámku a navrhuje další kroky.",
          sr: "Vodi pregled zajedno sa vama: beleži razgovor sa pacijentom, gradi strukturiranu belešku i predlaže sledeće korake.",
          hu: "Önnel együtt viszi a vizitet: rögzíti a beteggel folytatott beszélgetést, strukturált jegyzetet készít, és javaslatot tesz a következő lépésekre.",
          ar: "يدير الزيارة معك: يلتقط محادثة المريض، ويبني ملاحظة مُهيكلة، ويقترح الخطوات التالية.",
        }),
        cta: { label: t({
          uk: "Зареєструватися",
          en: "Sign up",
          pl: "Zarejestruj się",
          de: "Registrieren",
          ro: "Înregistrare",
          cs: "Zaregistrovat se",
          sr: "Registrujte se",
          hu: "Regisztráció",
          ar: "إنشاء حساب",
        }), path: "/signup" },
      },
      blocks: [
        { type: "grid", cols: 3, items: t({
          uk: [
              { icon: "check", title: "Згода та індикатор", desc: "Явна згода пацієнта та видимий індикатор запису протягом усього прийому." },
              { icon: "mic", title: "Живий транскрипт", desc: "Потокова диктація через WebSocket: частковий транскрипт з'являється під час мовлення." },
              { icon: "users", title: "Профілі пацієнтів", desc: "Картки пацієнтів і таймлайн візитів в одному місці." },
              { icon: "layers", title: "Автоструктура", desc: "Нотатка автоматично розкладається на секції шаблону." },
              { icon: "eye", title: "Підсвічування сумнівів", desc: "Слова низької впевненості виділяються для швидкої перевірки." },
              { icon: "save", title: "Автозбереження", desc: "Правки зберігаються автоматично з виявленням конфліктів між пристроями." },
            ],
          en: [
              { icon: "check", title: "Consent & indicator", desc: "Explicit patient consent and a visible recording indicator throughout the visit." },
              { icon: "mic", title: "Live transcript", desc: "Streaming dictation over WebSocket: a partial transcript appears as you speak." },
              { icon: "users", title: "Patient profiles", desc: "Patient cards and a visit timeline in one place." },
              { icon: "layers", title: "Auto-structure", desc: "The note is laid out into the template's sections automatically." },
              { icon: "eye", title: "Low-confidence flags", desc: "Words the model is unsure about are highlighted for quick review." },
              { icon: "save", title: "Autosave", desc: "Edits save automatically with cross-device conflict detection." },
            ],
          pl: [
              { icon: "check", title: "Zgoda i wskaźnik", desc: "Wyraźna zgoda pacjenta i widoczny wskaźnik nagrywania przez całą wizytę." },
              { icon: "mic", title: "Transkrypcja na żywo", desc: "Strumieniowe dyktowanie przez WebSocket: częściowa transkrypcja pojawia się w trakcie mówienia." },
              { icon: "users", title: "Profile pacjentów", desc: "Karty pacjentów i oś czasu wizyt w jednym miejscu." },
              { icon: "layers", title: "Automatyczna struktura", desc: "Notatka jest automatycznie rozkładana na sekcje szablonu." },
              { icon: "eye", title: "Oznaczanie niepewności", desc: "Słowa, których model nie jest pewien, są wyróżniane do szybkiej weryfikacji." },
              { icon: "save", title: "Autozapis", desc: "Zmiany zapisują się automatycznie z wykrywaniem konfliktów między urządzeniami." },
            ],
          de: [
              { icon: "check", title: "Einwilligung & Indikator", desc: "Ausdrückliche Einwilligung des Patienten und ein sichtbarer Aufnahmeindikator während der gesamten Sprechstunde." },
              { icon: "mic", title: "Live-Transkript", desc: "Streaming-Diktat über WebSocket: ein partielles Transkript erscheint, während Sie sprechen." },
              { icon: "users", title: "Patientenprofile", desc: "Patientenkarten und eine Zeitleiste der Besuche an einem Ort." },
              { icon: "layers", title: "Auto-Struktur", desc: "Die Notiz wird automatisch in die Abschnitte der Vorlage gegliedert." },
              { icon: "eye", title: "Markierung unsicherer Wörter", desc: "Wörter, bei denen sich das Modell unsicher ist, werden zur schnellen Prüfung hervorgehoben." },
              { icon: "save", title: "Automatisches Speichern", desc: "Änderungen werden automatisch gespeichert, mit geräteübergreifender Konflikterkennung." },
            ],
          ro: [
              { icon: "check", title: "Consimțământ și indicator", desc: "Consimțământ explicit al pacientului și un indicator vizibil de înregistrare pe toată durata consultației." },
              { icon: "mic", title: "Transcript live", desc: "Dictare în flux prin WebSocket: un transcript parțial apare în timp ce vorbiți." },
              { icon: "users", title: "Profiluri de pacienți", desc: "Fișele pacienților și cronologia vizitelor într-un singur loc." },
              { icon: "layers", title: "Structurare automată", desc: "Nota este așezată automat în secțiunile șablonului." },
              { icon: "eye", title: "Marcaje de încredere scăzută", desc: "Cuvintele de care modelul nu este sigur sunt evidențiate pentru o verificare rapidă." },
              { icon: "save", title: "Salvare automată", desc: "Modificările se salvează automat, cu detectarea conflictelor între dispozitive." },
            ],
          cs: [
              { icon: "check", title: "Souhlas a indikátor", desc: "Výslovný souhlas pacienta a viditelný indikátor nahrávání po celou dobu návštěvy." },
              { icon: "mic", title: "Živý přepis", desc: "Streamované diktování přes WebSocket: částečný přepis se objevuje už během mluvení." },
              { icon: "users", title: "Profily pacientů", desc: "Karty pacientů a časová osa návštěv na jednom místě." },
              { icon: "layers", title: "Automatická struktura", desc: "Poznámka se automaticky rozloží do sekcí šablony." },
              { icon: "eye", title: "Označení nejistoty", desc: "Slova, kterými si model není jistý, se zvýrazňují pro rychlou kontrolu." },
              { icon: "save", title: "Automatické ukládání", desc: "Úpravy se ukládají automaticky s detekcí konfliktů mezi zařízeními." },
            ],
          sr: [
              { icon: "check", title: "Saglasnost i indikator", desc: "Izričita saglasnost pacijenta i vidljiv indikator snimanja tokom celog pregleda." },
              { icon: "mic", title: "Transkript uživo", desc: "Striming diktiranje preko WebSocket veze: delimični transkript se pojavljuje dok govorite." },
              { icon: "users", title: "Profili pacijenata", desc: "Kartoni pacijenata i vremenska linija pregleda na jednom mestu." },
              { icon: "layers", title: "Automatska struktura", desc: "Beleška se automatski raspoređuje u sekcije šablona." },
              { icon: "eye", title: "Oznake niske pouzdanosti", desc: "Reči u koje model nije siguran ističu se radi brze provere." },
              { icon: "save", title: "Automatsko čuvanje", desc: "Izmene se čuvaju automatski, uz otkrivanje konflikata između uređaja." },
            ],
          hu: [
              { icon: "check", title: "Beleegyezés és jelzés", desc: "A beteg kifejezett beleegyezése és jól látható felvételjelző a vizit teljes ideje alatt." },
              { icon: "mic", title: "Élő átirat", desc: "Streaming diktálás WebSocket felett: a részleges átirat már beszéd közben megjelenik." },
              { icon: "users", title: "Betegprofilok", desc: "Betegkartonok és vizit-idővonal egy helyen." },
              { icon: "layers", title: "Automatikus struktúra", desc: "A jegyzet automatikusan a sablon szakaszaiba rendeződik." },
              { icon: "eye", title: "Bizonytalanság jelölése", desc: "A modell által bizonytalannak ítélt szavak kiemelve jelennek meg a gyors ellenőrzéshez." },
              { icon: "save", title: "Automatikus mentés", desc: "A módosítások automatikusan mentődnek, eszközök közötti ütközésfelismeréssel." },
            ],
          ar: [
              { icon: "check", title: "الموافقة والمؤشّر", desc: "موافقة صريحة من المريض ومؤشّر تسجيل مرئي طوال الزيارة." },
              { icon: "mic", title: "نص منسوخ مباشر", desc: "إملاء متدفق عبر WebSocket: يظهر نص منسوخ جزئي أثناء حديثك." },
              { icon: "users", title: "ملفات المرضى", desc: "بطاقات المرضى وخط زمني للزيارات في مكان واحد." },
              { icon: "layers", title: "هيكلة تلقائية", desc: "تُرتَّب الملاحظة في أقسام القالب تلقائيًا." },
              { icon: "eye", title: "إشارات الثقة المنخفضة", desc: "تُبرَز الكلمات التي لا يكون النموذج متأكدًا منها لمراجعة سريعة." },
              { icon: "save", title: "حفظ تلقائي", desc: "تُحفظ التعديلات تلقائيًا مع كشف التعارضات بين الأجهزة." },
            ],
          }) },
        { type: "steps", heading: t({
            uk: "Як проходить прийом",
            en: "How a visit flows",
            pl: "Jak przebiega wizyta",
            de: "So läuft eine Sprechstunde ab",
            ro: "Cum decurge o consultație",
            cs: "Jak probíhá návštěva",
            sr: "Kako teče pregled",
            hu: "Így zajlik egy vizit",
            ar: "كيف تسير الزيارة",
          }), items: t({
          uk: [
              { n: "01", title: "Згода", desc: "Зафіксуйте згоду пацієнта на екрані згоди." },
              { n: "02", title: "Розмова", desc: "Ведіть прийом — Klarnote слухає й розпізнає мову." },
              { n: "03", title: "Нотатка", desc: "Отримайте структуровану нотатку для перевірки." },
              { n: "04", title: "Підпис", desc: "Перевірте, підпишіть і збережіть у картці пацієнта." },
            ],
          en: [
              { n: "01", title: "Consent", desc: "Capture patient consent on the consent screen." },
              { n: "02", title: "Conversation", desc: "Run the visit — Klarnote listens and recognizes speech." },
              { n: "03", title: "Note", desc: "Get a structured note ready for review." },
              { n: "04", title: "Sign", desc: "Review, sign and save to the patient record." },
            ],
          pl: [
              { n: "01", title: "Zgoda", desc: "Zarejestruj zgodę pacjenta na ekranie zgody." },
              { n: "02", title: "Rozmowa", desc: "Prowadź wizytę — Klarnote słucha i rozpoznaje mowę." },
              { n: "03", title: "Notatka", desc: "Otrzymaj ustrukturyzowaną notatkę gotową do weryfikacji." },
              { n: "04", title: "Podpis", desc: "Sprawdź, podpisz i zapisz w dokumentacji pacjenta." },
            ],
          de: [
              { n: "01", title: "Einwilligung", desc: "Erfassen Sie die Einwilligung des Patienten auf dem Einwilligungsbildschirm." },
              { n: "02", title: "Gespräch", desc: "Führen Sie die Sprechstunde — Klarnote hört zu und erkennt die Sprache." },
              { n: "03", title: "Notiz", desc: "Erhalten Sie eine strukturierte Notiz zur Durchsicht." },
              { n: "04", title: "Signieren", desc: "Prüfen, signieren und in der Patientenakte speichern." },
            ],
          ro: [
              { n: "01", title: "Consimțământ", desc: "Înregistrați consimțământul pacientului pe ecranul de consimțământ." },
              { n: "02", title: "Conversație", desc: "Desfășurați consultația — Klarnote ascultă și recunoaște vorbirea." },
              { n: "03", title: "Notă", desc: "Primiți o notă structurată, pregătită pentru verificare." },
              { n: "04", title: "Semnare", desc: "Verificați, semnați și salvați în fișa pacientului." },
            ],
          cs: [
              { n: "01", title: "Souhlas", desc: "Zaznamenejte souhlas pacienta na obrazovce souhlasu." },
              { n: "02", title: "Rozhovor", desc: "Veďte návštěvu — Klarnote poslouchá a rozpoznává řeč." },
              { n: "03", title: "Poznámka", desc: "Získejte strukturovanou poznámku připravenou ke kontrole." },
              { n: "04", title: "Podpis", desc: "Zkontrolujte, podepište a uložte do karty pacienta." },
            ],
          sr: [
              { n: "01", title: "Saglasnost", desc: "Zabeležite saglasnost pacijenta na ekranu za saglasnost." },
              { n: "02", title: "Razgovor", desc: "Vodite pregled — Klarnote sluša i prepoznaje govor." },
              { n: "03", title: "Beleška", desc: "Dobijte strukturiranu belešku spremnu za pregled." },
              { n: "04", title: "Potpis", desc: "Pregledajte, potpišite i sačuvajte u karton pacijenta." },
            ],
          hu: [
              { n: "01", title: "Beleegyezés", desc: "Rögzítse a beteg beleegyezését a beleegyezési képernyőn." },
              { n: "02", title: "Beszélgetés", desc: "Vezesse a vizitet — a Klarnote figyel és felismeri a beszédet." },
              { n: "03", title: "Jegyzet", desc: "Kapjon strukturált jegyzetet, ellenőrzésre készen." },
              { n: "04", title: "Aláírás", desc: "Ellenőrizze, írja alá és mentse a beteg kartonjába." },
            ],
          ar: [
              { n: "01", title: "الموافقة", desc: "سجّل موافقة المريض على شاشة الموافقة." },
              { n: "02", title: "المحادثة", desc: "أدر الزيارة — يستمع Klarnote ويتعرّف على الكلام." },
              { n: "03", title: "الملاحظة", desc: "احصل على ملاحظة مُهيكلة جاهزة للمراجعة." },
              { n: "04", title: "التوقيع", desc: "راجِع ووقّع واحفظ في سجل المريض." },
            ],
          }) },
        cta,
      ],
    },

    "product/dictate": {
      hero: {
        eyebrow: "Dictate",
        title: t({
          uk: "Диктування звітів",
          en: "Report dictation",
          pl: "Dyktowanie raportów",
          de: "Befunddiktat",
          ro: "Dictarea rapoartelor",
          cs: "Diktování zpráv",
          sr: "Diktiranje izveštaja",
          hu: "Leletdiktálás",
          ar: "إملاء التقارير",
        }),
        sub: t({
          uk: "Класичне диктування для радіології, патології та виписок із шаблонами, голосовими командами та порівнянням версій.",
          en: "Classic dictation for radiology, pathology and discharge summaries with templates, voice commands and version diffs.",
          pl: "Klasyczne dyktowanie dla radiologii, patologii i wypisów, z szablonami, poleceniami głosowymi i porównywaniem wersji.",
          de: "Klassisches Diktat für Radiologie, Pathologie und Entlassberichte mit Vorlagen, Sprachbefehlen und Versionsvergleich.",
          ro: "Dictare clasică pentru radiologie, patologie și scrisori de externare, cu șabloane, comenzi vocale și compararea versiunilor.",
          cs: "Klasické diktování pro radiologii, patologii a propouštěcí zprávy se šablonami, hlasovými příkazy a porovnáním verzí.",
          sr: "Klasično diktiranje za radiologiju, patologiju i otpusne liste, sa šablonima, glasovnim komandama i poređenjem verzija.",
          hu: "Klasszikus diktálás radiológiához, patológiához és zárójelentésekhez, sablonokkal, hangparancsokkal és verzió-összehasonlítással.",
          ar: "إملاء كلاسيكي لطب الأشعة وعلم الأمراض وملخصات الخروج، مع القوالب والأوامر الصوتية ومقارنات الإصدارات.",
        }),
        cta: { label: t({
          uk: "Зареєструватися",
          en: "Sign up",
          pl: "Zarejestruj się",
          de: "Registrieren",
          ro: "Înregistrare",
          cs: "Zaregistrovat se",
          sr: "Registrujte se",
          hu: "Regisztráció",
          ar: "إنشاء حساب",
        }), path: "/signup" },
      },
      blocks: [
        { type: "grid", cols: 3, items: t({
          uk: [
              { icon: "layers", title: "Шаблони звітів", desc: "16 системних структур під спеціальність плюс версіоновані шаблони закладу." },
              { icon: "keyboard", title: "Голосові команди", desc: "Понад 30 інтентів для керування структурою документа голосом." },
              { icon: "inbox", title: "Пакетне завантаження", desc: "Завантажте запис, зроблений деінде, — він шифрується й транскрибується асинхронно." },
              { icon: "check", title: "Перевірка фіналізації", desc: "Перед блокуванням версії перевіряються обов'язкові секції та дійсний код МКХ-10." },
              { icon: "diff", title: "Порівняння версій", desc: "Append-only історія: бачте кожну зміну та вносьте коректні амендменти." },
              { icon: "sign", title: "Підписання", desc: "КЕП через Дія або ІІТ, підписаний PADES PDF із публічною перевіркою." },
            ],
          en: [
              { icon: "layers", title: "Report templates", desc: "16 system structures per specialty plus your tenant's versioned templates." },
              { icon: "keyboard", title: "Voice commands", desc: "30+ intents to control the document structure with your voice." },
              { icon: "inbox", title: "Batch upload", desc: "Upload audio recorded elsewhere — it's encrypted and transcribed asynchronously." },
              { icon: "check", title: "Finalization checks", desc: "Required sections and a valid ICD-10 code are validated before the version locks." },
              { icon: "diff", title: "Version diffs", desc: "Append-only history: see every change and make correct amendments." },
              { icon: "sign", title: "Signing", desc: "Qualified signature via Дія or ІІТ, a signed PADES PDF with public verification." },
            ],
          pl: [
              { icon: "layers", title: "Szablony raportów", desc: "16 struktur systemowych według specjalizacji oraz wersjonowane szablony placówki." },
              { icon: "keyboard", title: "Polecenia głosowe", desc: "Ponad 30 intencji do sterowania strukturą dokumentu głosem." },
              { icon: "inbox", title: "Wgrywanie wsadowe", desc: "Wgraj nagranie wykonane gdzie indziej — jest szyfrowane i transkrybowane asynchronicznie." },
              { icon: "check", title: "Kontrole finalizacji", desc: "Przed zablokowaniem wersji sprawdzane są wymagane sekcje i poprawny kod ICD-10." },
              { icon: "diff", title: "Porównywanie wersji", desc: "Historia append-only: widzisz każdą zmianę i wnosisz prawidłowe poprawki." },
              { icon: "sign", title: "Podpisywanie", desc: "Kwalifikowany podpis przez Дія lub ІІТ, podpisany PDF PADES z publiczną weryfikacją." },
            ],
          de: [
              { icon: "layers", title: "Berichtsvorlagen", desc: "16 Systemstrukturen je Fachrichtung plus versionierte Vorlagen Ihrer Einrichtung." },
              { icon: "keyboard", title: "Sprachbefehle", desc: "Über 30 Intents zur Steuerung der Dokumentstruktur per Stimme." },
              { icon: "inbox", title: "Batch-Upload", desc: "Laden Sie anderswo aufgenommenes Audio hoch — es wird verschlüsselt und asynchron transkribiert." },
              { icon: "check", title: "Finalisierungsprüfungen", desc: "Pflichtabschnitte und ein gültiger ICD-10-Code werden geprüft, bevor die Version gesperrt wird." },
              { icon: "diff", title: "Versionsvergleich", desc: "Append-only-Historie: Sehen Sie jede Änderung und erstellen Sie korrekte Nachträge." },
              { icon: "sign", title: "Signieren", desc: "Qualifizierte Signatur über Дія oder ІІТ, ein signiertes PADES-PDF mit öffentlicher Prüfung." },
            ],
          ro: [
              { icon: "layers", title: "Șabloane de rapoarte", desc: "16 structuri de sistem pe specialitate plus șabloanele versionate ale instituției." },
              { icon: "keyboard", title: "Comenzi vocale", desc: "Peste 30 de intenții pentru a controla structura documentului cu vocea." },
              { icon: "inbox", title: "Încărcare în lot", desc: "Încărcați audio înregistrat în altă parte — este criptat și transcris asincron." },
              { icon: "check", title: "Verificări la finalizare", desc: "Secțiunile obligatorii și un cod ICD-10 valid sunt validate înainte de blocarea versiunii." },
              { icon: "diff", title: "Compararea versiunilor", desc: "Istoric append-only: vedeți fiecare modificare și faceți amendamente corecte." },
              { icon: "sign", title: "Semnare", desc: "Semnătură calificată prin Дія sau ІІТ, un PDF PADES semnat, cu verificare publică." },
            ],
          cs: [
              { icon: "layers", title: "Šablony zpráv", desc: "16 systémových struktur podle odbornosti plus verzované šablony vašeho zařízení." },
              { icon: "keyboard", title: "Hlasové příkazy", desc: "Přes 30 intentů pro ovládání struktury dokumentu hlasem." },
              { icon: "inbox", title: "Dávkové nahrání", desc: "Nahrajte audio pořízené jinde — zašifruje se a přepíše asynchronně." },
              { icon: "check", title: "Kontroly při finalizaci", desc: "Před uzamčením verze se ověřují povinné sekce a platný kód MKN-10." },
              { icon: "diff", title: "Porovnání verzí", desc: "Append-only historie: vidíte každou změnu a vytváříte korektní dodatky." },
              { icon: "sign", title: "Podepisování", desc: "Kvalifikovaný podpis přes Дія nebo ІІТ, podepsané PADES PDF s veřejným ověřením." },
            ],
          sr: [
              { icon: "layers", title: "Šabloni izveštaja", desc: "16 sistemskih struktura po specijalnosti plus verzionisani šabloni vaše ustanove." },
              { icon: "keyboard", title: "Glasovne komande", desc: "Preko 30 intenta za upravljanje strukturom dokumenta glasom." },
              { icon: "inbox", title: "Grupno otpremanje", desc: "Otpremite audio snimljen na drugom mestu — šifruje se i transkribuje asinhrono." },
              { icon: "check", title: "Provere pri finalizaciji", desc: "Obavezne sekcije i važeći MKB-10 kod proveravaju se pre zaključavanja verzije." },
              { icon: "diff", title: "Poređenje verzija", desc: "Append-only istorija: vidite svaku izmenu i unosite ispravne amandmane." },
              { icon: "sign", title: "Potpisivanje", desc: "Kvalifikovani potpis preko Дія ili ІІТ, potpisan PADES PDF sa javnom verifikacijom." },
            ],
          hu: [
              { icon: "layers", title: "Leletsablonok", desc: "16 rendszerstruktúra szakterületenként, valamint az intézmény verziózott sablonjai." },
              { icon: "keyboard", title: "Hangparancsok", desc: "Több mint 30 intent a dokumentum szerkezetének hangvezérléséhez." },
              { icon: "inbox", title: "Kötegelt feltöltés", desc: "Töltsön fel máshol rögzített hanganyagot — titkosítva, aszinkron módon készül el az átirata." },
              { icon: "check", title: "Véglegesítési ellenőrzések", desc: "A kötelező szakaszok és az érvényes BNO-10 kód a verzió zárolása előtt kerülnek ellenőrzésre." },
              { icon: "diff", title: "Verzió-összehasonlítás", desc: "Append-only előzmények: minden változás látható, és szabályos módosítások vihetők be." },
              { icon: "sign", title: "Aláírás", desc: "Minősített aláírás Дія vagy ІІТ útján, aláírt PADES PDF nyilvános ellenőrzéssel." },
            ],
          ar: [
              { icon: "layers", title: "قوالب التقارير", desc: "16 بنية نظامية لكل تخصص إضافةً إلى قوالب مؤسستك ذات الإصدارات." },
              { icon: "keyboard", title: "الأوامر الصوتية", desc: "أكثر من 30 نيّة للتحكم في بنية المستند بصوتك." },
              { icon: "inbox", title: "الرفع الدُّفعي", desc: "ارفع صوتًا مسجَّلًا في مكان آخر — يُشفَّر ويُنسَخ نصيًا بشكل غير متزامن." },
              { icon: "check", title: "فحوصات الإنهاء", desc: "تُتحقَّق الأقسام المطلوبة ورمز ICD-10 صالح قبل قفل الإصدار." },
              { icon: "diff", title: "مقارنات الإصدارات", desc: "سجل بالإضافة فقط: شاهد كل تغيير وأجرِ التعديلات الصحيحة." },
              { icon: "sign", title: "التوقيع", desc: "توقيع مؤهَّل عبر Дія أو ІІТ، وملف PADES PDF موقَّع مع تحقق عام." },
            ],
          }) },
        cta,
      ],
    },
  };
}
