// content-company.js — Company + legal marketing pages (about, contact,
// careers, blog teaser, legal/*). Split from content.js so each content domain
// can be translated independently. Every page ends with the shared CTA block
// passed in by content.js.

export function buildCompanyLegal(lang, cta) {
  const t = (m) => m[lang] ?? m.en;
  return {
    about: {
      hero: {
        eyebrow: t({ uk: "Про Klarnote", en: "About Klarnote", pl: "O Klarnote", de: "Über Klarnote", ro: "Despre Klarnote", cs: "O Klarnote", sr: "O Klarnoteu", hu: "A Klarnote-ról" }),
        title: t({
          uk: "Ми повертаємо лікарям час для пацієнтів",
          en: "We give clinicians their time back",
          pl: "Oddajemy lekarzom ich czas",
          de: "Wir geben Ärztinnen und Ärzten ihre Zeit zurück",
          ro: "Le redăm medicilor timpul lor",
          cs: "Vracíme lékařům jejich čas",
          sr: "Vraćamo lekarima njihovo vreme",
          hu: "Visszaadjuk az orvosok idejét",
        }),
        sub: t({
          uk: "Klarnote народився з простого спостереження: лікарі витрачають години на документацію замість того, щоб лікувати. Ми будуємо голосову платформу, яка пише нотатки за них.",
          en: "Klarnote began with a simple observation: clinicians spend hours on paperwork instead of care. We build the voice platform that writes the notes for them.",
          pl: "Klarnote zaczął się od prostej obserwacji: lekarze spędzają godziny na papierologii zamiast leczyć. Budujemy głosową platformę, która pisze notatki za nich.",
          de: "Klarnote begann mit einer einfachen Beobachtung: Ärztinnen und Ärzte verbringen Stunden mit Papierkram statt mit Behandlung. Wir bauen die Sprachplattform, die die Notizen für sie schreibt.",
          ro: "Klarnote a pornit de la o observație simplă: medicii petrec ore întregi cu birocrația în loc să îngrijească pacienți. Construim platforma vocală care scrie notele în locul lor.",
          cs: "Klarnote vznikl z prostého pozorování: lékaři tráví hodiny papírováním místo péče o pacienty. Stavíme hlasovou platformu, která poznámky píše za ně.",
          sr: "Klarnote je nastao iz jednostavnog zapažanja: lekari provode sate na papirologiji umesto na lečenju. Gradimo glasovnu platformu koja beleške piše umesto njih.",
          hu: "A Klarnote egy egyszerű megfigyelésből született: az orvosok órákat töltenek papírmunkával a gyógyítás helyett. Olyan hangalapú platformot építünk, amely megírja helyettük a jegyzeteket.",
        }),
      },
      blocks: [
        { type: "stats", items: t({
          uk: [{ v: "2024", l: "рік заснування" }, { v: "98%", l: "точність розпізнавання" }, { v: "2 мови", l: "українська та англійська" }, { v: "12+", l: "клінічних спеціальностей" }],
          en: [{ v: "2024", l: "founded" }, { v: "98%", l: "recognition accuracy" }, { v: "2 langs", l: "Ukrainian & English" }, { v: "12+", l: "clinical specialties" }],
          pl: [{ v: "2024", l: "rok założenia" }, { v: "98%", l: "dokładność rozpoznawania" }, { v: "2 języki", l: "ukraiński i angielski" }, { v: "12+", l: "specjalizacji klinicznych" }],
          de: [{ v: "2024", l: "gegründet" }, { v: "98%", l: "Erkennungsgenauigkeit" }, { v: "2 Sprachen", l: "Ukrainisch & Englisch" }, { v: "12+", l: "klinische Fachrichtungen" }],
          ro: [{ v: "2024", l: "anul înființării" }, { v: "98%", l: "acuratețea recunoașterii" }, { v: "2 limbi", l: "ucraineană și engleză" }, { v: "12+", l: "specialități clinice" }],
          cs: [{ v: "2024", l: "rok založení" }, { v: "98%", l: "přesnost rozpoznávání" }, { v: "2 jazyky", l: "ukrajinština a angličtina" }, { v: "12+", l: "klinických oborů" }],
          sr: [{ v: "2024", l: "godina osnivanja" }, { v: "98%", l: "tačnost prepoznavanja" }, { v: "2 jezika", l: "ukrajinski i engleski" }, { v: "12+", l: "kliničkih specijalnosti" }],
          hu: [{ v: "2024", l: "alapítás éve" }, { v: "98%", l: "felismerési pontosság" }, { v: "2 nyelv", l: "ukrán és angol" }, { v: "12+", l: "klinikai szakterület" }],
        }) },
        { type: "prose", heading: t({ uk: "Наша місія", en: "Our mission", pl: "Nasza misja", de: "Unsere Mission", ro: "Misiunea noastră", cs: "Naše mise", sr: "Naša misija", hu: "Küldetésünk" }),
          paragraphs: t({
            uk: ["Кожна хвилина, яку лікар витрачає на друк, — це хвилина, відібрана у пацієнта. Ми хочемо, щоб документація відбувалася сама собою — точно, безпечно та зрозумілою мовою.",
                 "Klarnote поєднує потокове розпізнавання медичної мови, структуровані шаблони та електронний підпис в одному робочому процесі, створеному разом із лікарями.",
                 "Наш головний принцип незмінний: система готує чернетку, але не ставить діагноз. Жоден документ не фіналізується без лікаря — а всі моделі розпізнавання та генерації працюють на власному, self-hosted обладнанні, тож дані пацієнтів не залишають вашого розгортання."],
            en: ["Every minute a clinician spends typing is a minute taken from the patient. We want documentation to happen on its own — accurately, securely, and in plain language.",
                 "Klarnote combines streaming medical speech recognition, structured templates and e-signature into one workflow, built together with clinicians.",
                 "Our core principle never changes: the system drafts, it does not diagnose. Nothing is finalized without a clinician — and every recognition and generation model runs on self-hosted hardware, so patient data never leaves your deployment."],
            pl: ["Każda minuta, którą lekarz spędza na pisaniu, to minuta odebrana pacjentowi. Chcemy, aby dokumentacja powstawała sama — dokładnie, bezpiecznie i zrozumiałym językiem.",
                 "Klarnote łączy strumieniowe rozpoznawanie mowy medycznej, ustrukturyzowane szablony i podpis elektroniczny w jeden przepływ pracy, stworzony wspólnie z lekarzami.",
                 "Nasza podstawowa zasada się nie zmienia: system tworzy szkic, ale nie stawia diagnozy. Nic nie jest finalizowane bez lekarza — a wszystkie modele rozpoznawania i generowania działają na własnym, self-hosted sprzęcie, więc dane pacjentów nigdy nie opuszczają Twojego wdrożenia."],
            de: ["Jede Minute, die eine Ärztin oder ein Arzt mit Tippen verbringt, ist eine Minute, die dem Patienten fehlt. Wir wollen, dass Dokumentation von selbst entsteht — präzise, sicher und in klarer Sprache.",
                 "Klarnote vereint streamende medizinische Spracherkennung, strukturierte Vorlagen und elektronische Signatur in einem Workflow — gemeinsam mit Ärztinnen und Ärzten entwickelt.",
                 "Unser Grundprinzip bleibt unverändert: Das System entwirft, es diagnostiziert nicht. Nichts wird ohne Ärztin oder Arzt finalisiert — und alle Erkennungs- und Generierungsmodelle laufen auf selbst gehosteter Hardware, sodass Patientendaten Ihre Umgebung nie verlassen."],
            ro: ["Fiecare minut pe care un medic îl petrece tastând este un minut luat pacientului. Ne dorim ca documentația să se scrie de la sine — precis, sigur și într-un limbaj clar.",
                 "Klarnote combină recunoașterea vocală medicală în timp real, șabloane structurate și semnătura electronică într-un singur flux de lucru, construit împreună cu medicii.",
                 "Principiul nostru de bază nu se schimbă: sistemul redactează, nu pune diagnostice. Nimic nu este finalizat fără un medic — iar toate modelele de recunoaștere și generare rulează pe hardware self-hosted, astfel încât datele pacienților nu părăsesc niciodată infrastructura dumneavoastră."],
            cs: ["Každá minuta, kterou lékař stráví psaním, je minuta vzatá pacientovi. Chceme, aby dokumentace vznikala sama — přesně, bezpečně a srozumitelným jazykem.",
                 "Klarnote spojuje streamované rozpoznávání lékařské řeči, strukturované šablony a elektronický podpis do jednoho pracovního postupu, vytvořeného společně s lékaři.",
                 "Náš základní princip se nemění: systém vytváří koncept, nediagnostikuje. Nic není finalizováno bez lékaře — a všechny modely rozpoznávání i generování běží na vlastním, self-hosted hardwaru, takže data pacientů nikdy neopustí vaše nasazení."],
            sr: ["Svaki minut koji lekar provede kucajući jeste minut oduzet pacijentu. Želimo da dokumentacija nastaje sama od sebe — tačno, bezbedno i jasnim jezikom.",
                 "Klarnote objedinjuje strimovano prepoznavanje medicinskog govora, strukturirane šablone i elektronski potpis u jedan radni tok, izgrađen zajedno sa lekarima.",
                 "Naš osnovni princip se ne menja: sistem piše nacrt, ne postavlja dijagnozu. Ništa se ne finalizuje bez lekara — a svi modeli prepoznavanja i generisanja rade na sopstvenom, self-hosted hardveru, pa podaci pacijenata nikada ne napuštaju vaše okruženje."],
            hu: ["Minden perc, amelyet az orvos gépeléssel tölt, a betegtől elvett perc. Azt szeretnénk, hogy a dokumentáció magától készüljön el — pontosan, biztonságosan és közérthető nyelven.",
                 "A Klarnote a valós idejű orvosi beszédfelismerést, a strukturált sablonokat és az elektronikus aláírást egyetlen munkafolyamatba egyesíti, amelyet orvosokkal közösen építettünk.",
                 "Alapelvünk változatlan: a rendszer vázlatot készít, nem diagnosztizál. Semmi sem véglegesíthető orvos nélkül — és minden felismerő és generáló modell saját, self-hosted hardveren fut, így a betegadatok soha nem hagyják el az Ön környezetét."],
          }) },
        { type: "grid", heading: t({ uk: "Наші цінності", en: "Our values", pl: "Nasze wartości", de: "Unsere Werte", ro: "Valorile noastre", cs: "Naše hodnoty", sr: "Naše vrednosti", hu: "Értékeink" }), cols: 3, items: t({
          uk: [
              { icon: "heart", title: "Пацієнт понад усе", desc: "Кожне рішення оцінюємо за тим, чи дає воно лікарю більше часу з пацієнтом." },
              { icon: "shield", title: "Безпека за замовчуванням", desc: "Дані пацієнтів захищені на кожному етапі — від запису до архіву." },
              { icon: "sparkle", title: "Точність важливіша за хайп", desc: "Ми вимірюємо реальну якість розпізнавання, а не обіцянки." },
              { icon: "users", title: "Створено з лікарями", desc: "Продукт формують ті, хто щодня веде прийоми." },
              { icon: "check", title: "Прозорість", desc: "Зрозуміло, як обробляються дані та як працює модель." },
              { icon: "history", title: "Надійність", desc: "Незмінний аудит і повна історія змін кожного документа." },
            ],
          en: [
              { icon: "heart", title: "Patient first", desc: "Every decision is judged by whether it gives clinicians more time with patients." },
              { icon: "shield", title: "Secure by default", desc: "Patient data is protected at every step — from recording to archive." },
              { icon: "sparkle", title: "Accuracy over hype", desc: "We measure real recognition quality, not promises." },
              { icon: "users", title: "Built with clinicians", desc: "The product is shaped by the people running visits every day." },
              { icon: "check", title: "Transparency", desc: "Clear about how data is processed and how the model works." },
              { icon: "history", title: "Reliability", desc: "Immutable audit and a full change history for every document." },
            ],
          pl: [
              { icon: "heart", title: "Pacjent przede wszystkim", desc: "Każdą decyzję oceniamy po tym, czy daje lekarzom więcej czasu z pacjentami." },
              { icon: "shield", title: "Bezpieczeństwo domyślnie", desc: "Dane pacjentów są chronione na każdym etapie — od nagrania po archiwum." },
              { icon: "sparkle", title: "Dokładność ponad szum", desc: "Mierzymy rzeczywistą jakość rozpoznawania, a nie obietnice." },
              { icon: "users", title: "Tworzone z lekarzami", desc: "Produkt kształtują ludzie, którzy codziennie prowadzą wizyty." },
              { icon: "check", title: "Przejrzystość", desc: "Jasno mówimy, jak przetwarzane są dane i jak działa model." },
              { icon: "history", title: "Niezawodność", desc: "Niezmienny audyt i pełna historia zmian każdego dokumentu." },
            ],
          de: [
              { icon: "heart", title: "Der Patient zuerst", desc: "Jede Entscheidung wird daran gemessen, ob sie Ärztinnen und Ärzten mehr Zeit mit Patienten gibt." },
              { icon: "shield", title: "Sicher per Voreinstellung", desc: "Patientendaten sind in jedem Schritt geschützt — von der Aufnahme bis zum Archiv." },
              { icon: "sparkle", title: "Genauigkeit statt Hype", desc: "Wir messen echte Erkennungsqualität, keine Versprechen." },
              { icon: "users", title: "Mit Ärzten entwickelt", desc: "Das Produkt wird von Menschen geprägt, die täglich Sprechstunden führen." },
              { icon: "check", title: "Transparenz", desc: "Klar darüber, wie Daten verarbeitet werden und wie das Modell funktioniert." },
              { icon: "history", title: "Zuverlässigkeit", desc: "Unveränderliches Audit und vollständige Änderungshistorie für jedes Dokument." },
            ],
          ro: [
              { icon: "heart", title: "Pacientul pe primul loc", desc: "Fiecare decizie este judecată după cât timp le oferă medicilor cu pacienții." },
              { icon: "shield", title: "Securitate implicită", desc: "Datele pacienților sunt protejate la fiecare pas — de la înregistrare la arhivă." },
              { icon: "sparkle", title: "Acuratețe în locul hype-ului", desc: "Măsurăm calitatea reală a recunoașterii, nu promisiuni." },
              { icon: "users", title: "Construit cu medicii", desc: "Produsul este modelat de oamenii care fac consultații în fiecare zi." },
              { icon: "check", title: "Transparență", desc: "Explicăm clar cum sunt prelucrate datele și cum funcționează modelul." },
              { icon: "history", title: "Fiabilitate", desc: "Audit imuabil și istoric complet al modificărilor pentru fiecare document." },
            ],
          cs: [
              { icon: "heart", title: "Pacient na prvním místě", desc: "Každé rozhodnutí posuzujeme podle toho, zda dává lékařům více času s pacienty." },
              { icon: "shield", title: "Bezpečnost ve výchozím stavu", desc: "Data pacientů jsou chráněna v každém kroku — od nahrávky po archiv." },
              { icon: "sparkle", title: "Přesnost místo humbuku", desc: "Měříme skutečnou kvalitu rozpoznávání, ne sliby." },
              { icon: "users", title: "Vytvořeno s lékaři", desc: "Produkt formují lidé, kteří denně vedou vyšetření." },
              { icon: "check", title: "Transparentnost", desc: "Srozumitelně o tom, jak se zpracovávají data a jak model funguje." },
              { icon: "history", title: "Spolehlivost", desc: "Neměnný audit a úplná historie změn každého dokumentu." },
            ],
          sr: [
              { icon: "heart", title: "Pacijent na prvom mestu", desc: "Svaku odluku procenjujemo po tome da li lekarima daje više vremena sa pacijentima." },
              { icon: "shield", title: "Bezbednost podrazumevano", desc: "Podaci pacijenata zaštićeni su u svakom koraku — od snimka do arhive." },
              { icon: "sparkle", title: "Tačnost umesto pompe", desc: "Merimo stvarni kvalitet prepoznavanja, a ne obećanja." },
              { icon: "users", title: "Napravljeno sa lekarima", desc: "Proizvod oblikuju ljudi koji svakog dana vode preglede." },
              { icon: "check", title: "Transparentnost", desc: "Jasno o tome kako se obrađuju podaci i kako model radi." },
              { icon: "history", title: "Pouzdanost", desc: "Nepromenljiva revizija i potpuna istorija izmena svakog dokumenta." },
            ],
          hu: [
              { icon: "heart", title: "A beteg az első", desc: "Minden döntést az alapján ítélünk meg, hogy több időt ad-e az orvosoknak a betegeikre." },
              { icon: "shield", title: "Alapértelmezetten biztonságos", desc: "A betegadatok minden lépésben védettek — a felvételtől az archívumig." },
              { icon: "sparkle", title: "Pontosság a hype helyett", desc: "A felismerés valós minőségét mérjük, nem az ígéreteket." },
              { icon: "users", title: "Orvosokkal közösen készült", desc: "A terméket azok formálják, akik nap mint nap rendelnek." },
              { icon: "check", title: "Átláthatóság", desc: "Világosan elmondjuk, hogyan dolgozzuk fel az adatokat és hogyan működik a modell." },
              { icon: "history", title: "Megbízhatóság", desc: "Megmásíthatatlan audit és teljes változásnapló minden dokumentumhoz." },
            ],
        }) },
        { type: "prose", heading: t({ uk: "Наша історія", en: "Our story", pl: "Nasza historia", de: "Unsere Geschichte", ro: "Povestea noastră", cs: "Náš příběh", sr: "Naša priča", hu: "Történetünk" }),
          paragraphs: t({
            uk: ["Команда Klarnote складається з інженерів та лікарів, які втомилися від нескінченної паперової роботи. Ми почали з прототипу для радіологів і швидко зрозуміли, що проблема — універсальна.",
                 "Сьогодні Klarnote обслуговує амбулаторні прийоми та класичне диктування звітів, підтримує українську та англійську мови й інтегрується з електронним підписом Дія."],
            en: ["The Klarnote team is engineers and clinicians tired of endless paperwork. We started with a prototype for radiologists and quickly saw the problem was universal.",
                 "Today Klarnote powers ambient encounters and classic report dictation, supports Ukrainian and English, and integrates with the Дія e-signature."],
            pl: ["Zespół Klarnote to inżynierowie i lekarze zmęczeni niekończącą się papierologią. Zaczęliśmy od prototypu dla radiologów i szybko zobaczyliśmy, że problem jest uniwersalny.",
                 "Dziś Klarnote obsługuje wizyty w trybie ambient oraz klasyczne dyktowanie raportów, wspiera język ukraiński i angielski oraz integruje się z podpisem elektronicznym Дія (Diia)."],
            de: ["Das Klarnote-Team besteht aus Ingenieuren und Ärzten, die endlose Papierarbeit satthaben. Wir begannen mit einem Prototyp für Radiologen und sahen schnell, dass das Problem universell ist.",
                 "Heute unterstützt Klarnote Ambient-Sprechstunden und klassisches Befund-Diktat, beherrscht Ukrainisch und Englisch und integriert die elektronische Signatur Дія (Diia)."],
            ro: ["Echipa Klarnote este formată din ingineri și medici sătui de birocrația fără sfârșit. Am început cu un prototip pentru radiologi și am văzut rapid că problema este universală.",
                 "Astăzi Klarnote susține consultații ambient și dictarea clasică de rapoarte, acceptă ucraineana și engleza și se integrează cu semnătura electronică Дія (Diia)."],
            cs: ["Tým Klarnote tvoří inženýři a lékaři unavení nekonečným papírováním. Začali jsme prototypem pro radiology a rychle jsme zjistili, že problém je univerzální.",
                 "Dnes Klarnote pokrývá ambientní vyšetření i klasické diktování zpráv, podporuje ukrajinštinu a angličtinu a integruje elektronický podpis Дія (Diia)."],
            sr: ["Tim Klarnotea čine inženjeri i lekari umorni od beskrajne papirologije. Počeli smo prototipom za radiologe i brzo uvideli da je problem univerzalan.",
                 "Danas Klarnote pokreće ambijentalne preglede i klasično diktiranje izveštaja, podržava ukrajinski i engleski i integriše se sa elektronskim potpisom Дія (Diia)."],
            hu: ["A Klarnote csapata mérnökökből és orvosokból áll, akik belefáradtak a végtelen papírmunkába. Egy radiológusoknak készült prototípussal indultunk, és hamar láttuk, hogy a probléma egyetemes.",
                 "Ma a Klarnote az ambient vizitek és a klasszikus leletdiktálás motorja, támogatja az ukrán és az angol nyelvet, és integrálódik a Дія (Diia) elektronikus aláírással."],
          }) },
        cta,
      ],
    },

    contact: {
      hero: {
        eyebrow: t({ uk: "Контакти", en: "Contact", pl: "Kontakt", de: "Kontakt", ro: "Contact", cs: "Kontakt", sr: "Kontakt", hu: "Kapcsolat" }),
        title: t({ uk: "Поговоримо", en: "Let's talk", pl: "Porozmawiajmy", de: "Sprechen wir", ro: "Să vorbim", cs: "Pojďme si promluvit", sr: "Razgovarajmo", hu: "Beszéljünk" }),
        sub: t({
          uk: "Питання про продукт, демо для вашої клініки чи партнерство — ми відповідаємо швидко.",
          en: "Product questions, a demo for your clinic, or a partnership — we reply fast.",
          pl: "Pytania o produkt, demo dla Twojej kliniki czy partnerstwo — odpowiadamy szybko.",
          de: "Fragen zum Produkt, eine Demo für Ihre Klinik oder eine Partnerschaft — wir antworten schnell.",
          ro: "Întrebări despre produs, un demo pentru clinica dumneavoastră sau un parteneriat — răspundem rapid.",
          cs: "Dotazy k produktu, demo pro vaši kliniku nebo partnerství — odpovídáme rychle.",
          sr: "Pitanja o proizvodu, demo za vašu kliniku ili partnerstvo — odgovaramo brzo.",
          hu: "Kérdések a termékről, demó a klinikájának vagy partnerség — gyorsan válaszolunk.",
        }),
      },
      blocks: [
        { type: "contact", items: t({
          uk: [
              { icon: "inbox", title: "Загальні питання", value: "hello@klarnote.example", note: "Відповідаємо протягом робочого дня." },
              { icon: "users", title: "Продажі та демо", value: "sales@klarnote.example", note: "Демо для клінік і лікарень." },
              { icon: "shield", title: "Безпека та приватність", value: "security@klarnote.example", note: "Питання щодо обробки даних." },
              { icon: "help", title: "Підтримка", value: "support@klarnote.example", note: "Для наявних користувачів." },
            ],
          en: [
              { icon: "inbox", title: "General", value: "hello@klarnote.example", note: "We reply within a business day." },
              { icon: "users", title: "Sales & demos", value: "sales@klarnote.example", note: "Demos for clinics and hospitals." },
              { icon: "shield", title: "Security & privacy", value: "security@klarnote.example", note: "Data-processing questions." },
              { icon: "help", title: "Support", value: "support@klarnote.example", note: "For existing customers." },
            ],
          pl: [
              { icon: "inbox", title: "Pytania ogólne", value: "hello@klarnote.example", note: "Odpowiadamy w ciągu dnia roboczego." },
              { icon: "users", title: "Sprzedaż i dema", value: "sales@klarnote.example", note: "Dema dla klinik i szpitali." },
              { icon: "shield", title: "Bezpieczeństwo i prywatność", value: "security@klarnote.example", note: "Pytania o przetwarzanie danych." },
              { icon: "help", title: "Wsparcie", value: "support@klarnote.example", note: "Dla obecnych klientów." },
            ],
          de: [
              { icon: "inbox", title: "Allgemein", value: "hello@klarnote.example", note: "Wir antworten innerhalb eines Werktags." },
              { icon: "users", title: "Vertrieb & Demos", value: "sales@klarnote.example", note: "Demos für Kliniken und Krankenhäuser." },
              { icon: "shield", title: "Sicherheit & Datenschutz", value: "security@klarnote.example", note: "Fragen zur Datenverarbeitung." },
              { icon: "help", title: "Support", value: "support@klarnote.example", note: "Für Bestandskunden." },
            ],
          ro: [
              { icon: "inbox", title: "Întrebări generale", value: "hello@klarnote.example", note: "Răspundem în cursul unei zile lucrătoare." },
              { icon: "users", title: "Vânzări și demonstrații", value: "sales@klarnote.example", note: "Demonstrații pentru clinici și spitale." },
              { icon: "shield", title: "Securitate și confidențialitate", value: "security@klarnote.example", note: "Întrebări privind prelucrarea datelor." },
              { icon: "help", title: "Suport", value: "support@klarnote.example", note: "Pentru clienții existenți." },
            ],
          cs: [
              { icon: "inbox", title: "Obecné dotazy", value: "hello@klarnote.example", note: "Odpovídáme do jednoho pracovního dne." },
              { icon: "users", title: "Prodej a dema", value: "sales@klarnote.example", note: "Dema pro kliniky a nemocnice." },
              { icon: "shield", title: "Bezpečnost a soukromí", value: "security@klarnote.example", note: "Dotazy ke zpracování dat." },
              { icon: "help", title: "Podpora", value: "support@klarnote.example", note: "Pro stávající zákazníky." },
            ],
          sr: [
              { icon: "inbox", title: "Opšta pitanja", value: "hello@klarnote.example", note: "Odgovaramo u toku radnog dana." },
              { icon: "users", title: "Prodaja i demonstracije", value: "sales@klarnote.example", note: "Demonstracije za klinike i bolnice." },
              { icon: "shield", title: "Bezbednost i privatnost", value: "security@klarnote.example", note: "Pitanja o obradi podataka." },
              { icon: "help", title: "Podrška", value: "support@klarnote.example", note: "Za postojeće korisnike." },
            ],
          hu: [
              { icon: "inbox", title: "Általános kérdések", value: "hello@klarnote.example", note: "Egy munkanapon belül válaszolunk." },
              { icon: "users", title: "Értékesítés és demók", value: "sales@klarnote.example", note: "Demók klinikáknak és kórházaknak." },
              { icon: "shield", title: "Biztonság és adatvédelem", value: "security@klarnote.example", note: "Adatkezeléssel kapcsolatos kérdések." },
              { icon: "help", title: "Támogatás", value: "support@klarnote.example", note: "Meglévő ügyfeleinknek." },
            ],
        }) },
        { type: "form" },
        { type: "grid", heading: t({ uk: "Офіси", en: "Offices", pl: "Biura", de: "Standorte", ro: "Birouri", cs: "Kanceláře", sr: "Kancelarije", hu: "Irodák" }), cols: 2, items: t({
          uk: [
              { icon: "home", title: "Київ", desc: "вул. Хрещатик, 1 · Україна" },
              { icon: "home", title: "Львів", desc: "пл. Ринок, 1 · Україна" },
            ],
          en: [
              { icon: "home", title: "Kyiv", desc: "1 Khreshchatyk St · Ukraine" },
              { icon: "home", title: "Lviv", desc: "1 Rynok Sq · Ukraine" },
            ],
          pl: [
              { icon: "home", title: "Kijów", desc: "ul. Chreszczatyk 1 · Ukraina" },
              { icon: "home", title: "Lwów", desc: "Rynek 1 · Ukraina" },
            ],
          de: [
              { icon: "home", title: "Kiew", desc: "Chreschtschatyk-Straße 1 · Ukraine" },
              { icon: "home", title: "Lemberg", desc: "Rynok-Platz 1 · Ukraine" },
            ],
          ro: [
              { icon: "home", title: "Kiev", desc: "Str. Hreșciatik 1 · Ucraina" },
              { icon: "home", title: "Liov", desc: "Piața Rynok 1 · Ucraina" },
            ],
          cs: [
              { icon: "home", title: "Kyjev", desc: "ul. Chreščatyk 1 · Ukrajina" },
              { icon: "home", title: "Lvov", desc: "nám. Rynok 1 · Ukrajina" },
            ],
          sr: [
              { icon: "home", title: "Kijev", desc: "Ul. Hreščatik 1 · Ukrajina" },
              { icon: "home", title: "Lavov", desc: "Trg Rinok 1 · Ukrajina" },
            ],
          hu: [
              { icon: "home", title: "Kijev", desc: "Hrescsatik utca 1. · Ukrajna" },
              { icon: "home", title: "Lviv", desc: "Rinok tér 1. · Ukrajna" },
            ],
        }) },
      ],
    },

    careers: {
      hero: {
        eyebrow: t({ uk: "Кар'єра", en: "Careers", pl: "Kariera", de: "Karriere", ro: "Cariere", cs: "Kariéra", sr: "Karijera", hu: "Karrier" }),
        title: t({
          uk: "Будуйте майбутнє медичної документації",
          en: "Build the future of medical documentation",
          pl: "Buduj przyszłość dokumentacji medycznej",
          de: "Gestalten Sie die Zukunft der medizinischen Dokumentation",
          ro: "Construiește viitorul documentației medicale",
          cs: "Budujte budoucnost lékařské dokumentace",
          sr: "Gradite budućnost medicinske dokumentacije",
          hu: "Építsd velünk az orvosi dokumentáció jövőjét",
        }),
        sub: t({
          uk: "Ми невелика команда з великою місією. Якщо вам близька ідея повернути лікарям час — приєднуйтесь.",
          en: "We're a small team with a big mission. If giving clinicians their time back resonates with you — join us.",
          pl: "Jesteśmy małym zespołem z wielką misją. Jeśli idea oddania lekarzom ich czasu jest Ci bliska — dołącz do nas.",
          de: "Wir sind ein kleines Team mit einer großen Mission. Wenn es Sie anspricht, Ärztinnen und Ärzten ihre Zeit zurückzugeben — kommen Sie zu uns.",
          ro: "Suntem o echipă mică, cu o misiune mare. Dacă ideea de a le reda medicilor timpul rezonează cu tine — alătură-te nouă.",
          cs: "Jsme malý tým s velkou misí. Pokud vám myšlenka vrátit lékařům čas dává smysl — přidejte se k nám.",
          sr: "Mali smo tim sa velikom misijom. Ako vam je bliska ideja da lekarima vratimo vreme — pridružite nam se.",
          hu: "Kis csapat vagyunk nagy küldetéssel. Ha közel áll hozzád a gondolat, hogy visszaadjuk az orvosok idejét — csatlakozz hozzánk.",
        }),
      },
      blocks: [
        { type: "grid", heading: t({ uk: "Чому Klarnote", en: "Why Klarnote", pl: "Dlaczego Klarnote", de: "Warum Klarnote", ro: "De ce Klarnote", cs: "Proč Klarnote", sr: "Zašto Klarnote", hu: "Miért a Klarnote" }), cols: 3, items: t({
          uk: [
              { icon: "heart", title: "Реальний вплив", desc: "Ваша робота щодня економить години лікарям." },
              { icon: "home", title: "Віддалено", desc: "Гнучкий графік і робота з будь-якої точки." },
              { icon: "sparkle", title: "Сучасний стек", desc: "Передові моделі розпізнавання мови та чистий код." },
              { icon: "book", title: "Навчання", desc: "Бюджет на конференції, книги та курси." },
              { icon: "calendar", title: "Відпустка", desc: "Достатньо часу, щоб відновитися." },
              { icon: "users", title: "Сильна команда", desc: "Інженери та лікарі, які поважають одне одного." },
            ],
          en: [
              { icon: "heart", title: "Real impact", desc: "Your work saves clinicians hours every day." },
              { icon: "home", title: "Remote-first", desc: "Flexible hours and work from anywhere." },
              { icon: "sparkle", title: "Modern stack", desc: "State-of-the-art speech models and clean code." },
              { icon: "book", title: "Learning", desc: "Budget for conferences, books and courses." },
              { icon: "calendar", title: "Time off", desc: "Enough time to actually recharge." },
              { icon: "users", title: "Great team", desc: "Engineers and clinicians who respect each other." },
            ],
          pl: [
              { icon: "heart", title: "Realny wpływ", desc: "Twoja praca codziennie oszczędza lekarzom godziny." },
              { icon: "home", title: "Praca zdalna", desc: "Elastyczne godziny i praca z dowolnego miejsca." },
              { icon: "sparkle", title: "Nowoczesny stack", desc: "Najnowocześniejsze modele rozpoznawania mowy i czysty kod." },
              { icon: "book", title: "Rozwój", desc: "Budżet na konferencje, książki i kursy." },
              { icon: "calendar", title: "Urlop", desc: "Wystarczająco czasu, żeby naprawdę odpocząć." },
              { icon: "users", title: "Świetny zespół", desc: "Inżynierowie i lekarze, którzy się nawzajem szanują." },
            ],
          de: [
              { icon: "heart", title: "Echte Wirkung", desc: "Ihre Arbeit spart Ärztinnen und Ärzten täglich Stunden." },
              { icon: "home", title: "Remote-first", desc: "Flexible Arbeitszeiten und Arbeit von überall." },
              { icon: "sparkle", title: "Moderner Stack", desc: "Modernste Sprachmodelle und sauberer Code." },
              { icon: "book", title: "Weiterbildung", desc: "Budget für Konferenzen, Bücher und Kurse." },
              { icon: "calendar", title: "Urlaub", desc: "Genug Zeit, um wirklich aufzutanken." },
              { icon: "users", title: "Starkes Team", desc: "Ingenieure und Ärzte, die einander respektieren." },
            ],
          ro: [
              { icon: "heart", title: "Impact real", desc: "Munca ta le economisește medicilor ore în fiecare zi." },
              { icon: "home", title: "Remote-first", desc: "Program flexibil și lucru de oriunde." },
              { icon: "sparkle", title: "Stack modern", desc: "Modele de vorbire de ultimă generație și cod curat." },
              { icon: "book", title: "Învățare", desc: "Buget pentru conferințe, cărți și cursuri." },
              { icon: "calendar", title: "Concediu", desc: "Suficient timp ca să te refaci cu adevărat." },
              { icon: "users", title: "Echipă excelentă", desc: "Ingineri și medici care se respectă reciproc." },
            ],
          cs: [
              { icon: "heart", title: "Skutečný dopad", desc: "Vaše práce denně šetří lékařům hodiny." },
              { icon: "home", title: "Remote-first", desc: "Flexibilní pracovní doba a práce odkudkoli." },
              { icon: "sparkle", title: "Moderní stack", desc: "Špičkové modely rozpoznávání řeči a čistý kód." },
              { icon: "book", title: "Vzdělávání", desc: "Rozpočet na konference, knihy a kurzy." },
              { icon: "calendar", title: "Dovolená", desc: "Dost času na skutečný odpočinek." },
              { icon: "users", title: "Skvělý tým", desc: "Inženýři a lékaři, kteří se navzájem respektují." },
            ],
          sr: [
              { icon: "heart", title: "Stvaran uticaj", desc: "Vaš rad svakog dana štedi lekarima sate." },
              { icon: "home", title: "Remote-first", desc: "Fleksibilno radno vreme i rad sa bilo kog mesta." },
              { icon: "sparkle", title: "Moderan stek", desc: "Najsavremeniji modeli prepoznavanja govora i čist kod." },
              { icon: "book", title: "Učenje", desc: "Budžet za konferencije, knjige i kurseve." },
              { icon: "calendar", title: "Odmor", desc: "Dovoljno vremena za pravi oporavak." },
              { icon: "users", title: "Sjajan tim", desc: "Inženjeri i lekari koji poštuju jedni druge." },
            ],
          hu: [
              { icon: "heart", title: "Valódi hatás", desc: "A munkád naponta órákat spórol az orvosoknak." },
              { icon: "home", title: "Remote-first", desc: "Rugalmas munkaidő, munka bárhonnan." },
              { icon: "sparkle", title: "Modern stack", desc: "Élvonalbeli beszédfelismerő modellek és tiszta kód." },
              { icon: "book", title: "Tanulás", desc: "Keret konferenciákra, könyvekre és kurzusokra." },
              { icon: "calendar", title: "Szabadság", desc: "Elég idő az igazi feltöltődéshez." },
              { icon: "users", title: "Remek csapat", desc: "Mérnökök és orvosok, akik tisztelik egymást." },
            ],
        }) },
        { type: "roles", heading: t({ uk: "Відкриті вакансії", en: "Open roles", pl: "Otwarte stanowiska", de: "Offene Stellen", ro: "Poziții deschise", cs: "Otevřené pozice", sr: "Otvorene pozicije", hu: "Nyitott pozíciók" }), items: t({
          uk: [
              { title: "Senior ML Engineer (Speech)", team: "Дослідження", location: "Віддалено", type: "Повна зайнятість" },
              { title: "Full-Stack Engineer (React)", team: "Продукт", location: "Київ / Віддалено", type: "Повна зайнятість" },
              { title: "Clinical Product Specialist", team: "Продукт", location: "Віддалено", type: "Повна зайнятість" },
              { title: "Security Engineer", team: "Платформа", location: "Віддалено", type: "Повна зайнятість" },
            ],
          en: [
              { title: "Senior ML Engineer (Speech)", team: "Research", location: "Remote", type: "Full-time" },
              { title: "Full-Stack Engineer (React)", team: "Product", location: "Kyiv / Remote", type: "Full-time" },
              { title: "Clinical Product Specialist", team: "Product", location: "Remote", type: "Full-time" },
              { title: "Security Engineer", team: "Platform", location: "Remote", type: "Full-time" },
            ],
          pl: [
              { title: "Senior ML Engineer (Speech)", team: "Badania", location: "Zdalnie", type: "Pełny etat" },
              { title: "Full-Stack Engineer (React)", team: "Produkt", location: "Kijów / Zdalnie", type: "Pełny etat" },
              { title: "Clinical Product Specialist", team: "Produkt", location: "Zdalnie", type: "Pełny etat" },
              { title: "Security Engineer", team: "Platforma", location: "Zdalnie", type: "Pełny etat" },
            ],
          de: [
              { title: "Senior ML Engineer (Speech)", team: "Forschung", location: "Remote", type: "Vollzeit" },
              { title: "Full-Stack Engineer (React)", team: "Produkt", location: "Kiew / Remote", type: "Vollzeit" },
              { title: "Clinical Product Specialist", team: "Produkt", location: "Remote", type: "Vollzeit" },
              { title: "Security Engineer", team: "Plattform", location: "Remote", type: "Vollzeit" },
            ],
          ro: [
              { title: "Senior ML Engineer (Speech)", team: "Cercetare", location: "Remote", type: "Normă întreagă" },
              { title: "Full-Stack Engineer (React)", team: "Produs", location: "Kiev / Remote", type: "Normă întreagă" },
              { title: "Clinical Product Specialist", team: "Produs", location: "Remote", type: "Normă întreagă" },
              { title: "Security Engineer", team: "Platformă", location: "Remote", type: "Normă întreagă" },
            ],
          cs: [
              { title: "Senior ML Engineer (Speech)", team: "Výzkum", location: "Vzdáleně", type: "Plný úvazek" },
              { title: "Full-Stack Engineer (React)", team: "Produkt", location: "Kyjev / Vzdáleně", type: "Plný úvazek" },
              { title: "Clinical Product Specialist", team: "Produkt", location: "Vzdáleně", type: "Plný úvazek" },
              { title: "Security Engineer", team: "Platforma", location: "Vzdáleně", type: "Plný úvazek" },
            ],
          sr: [
              { title: "Senior ML Engineer (Speech)", team: "Istraživanje", location: "Na daljinu", type: "Puno radno vreme" },
              { title: "Full-Stack Engineer (React)", team: "Proizvod", location: "Kijev / Na daljinu", type: "Puno radno vreme" },
              { title: "Clinical Product Specialist", team: "Proizvod", location: "Na daljinu", type: "Puno radno vreme" },
              { title: "Security Engineer", team: "Platforma", location: "Na daljinu", type: "Puno radno vreme" },
            ],
          hu: [
              { title: "Senior ML Engineer (Speech)", team: "Kutatás", location: "Távmunka", type: "Teljes munkaidő" },
              { title: "Full-Stack Engineer (React)", team: "Termék", location: "Kijev / Távmunka", type: "Teljes munkaidő" },
              { title: "Clinical Product Specialist", team: "Termék", location: "Távmunka", type: "Teljes munkaidő" },
              { title: "Security Engineer", team: "Platform", location: "Távmunka", type: "Teljes munkaidő" },
            ],
        }) },
        { type: "prose", heading: t({ uk: "Не бачите своєї ролі?", en: "Don't see your role?", pl: "Nie widzisz swojej roli?", de: "Ihre Rolle ist nicht dabei?", ro: "Nu îți găsești rolul?", cs: "Nevidíte svou roli?", sr: "Ne vidite svoju ulogu?", hu: "Nem találod a szerepkörödet?" }),
          paragraphs: t({
            uk: ["Ми завжди раді талановитим людям. Напишіть нам на careers@klarnote.example — розкажіть, чим хочете займатися."],
            en: ["We're always glad to meet talented people. Write to careers@klarnote.example and tell us what you'd love to work on."],
            pl: ["Zawsze chętnie poznajemy utalentowanych ludzi. Napisz na careers@klarnote.example i opowiedz, czym chcesz się zajmować."],
            de: ["Wir freuen uns immer über talentierte Menschen. Schreiben Sie an careers@klarnote.example und erzählen Sie uns, woran Sie gern arbeiten möchten."],
            ro: ["Ne bucurăm mereu să cunoaștem oameni talentați. Scrie-ne la careers@klarnote.example și spune-ne la ce ți-ar plăcea să lucrezi."],
            cs: ["Talentované lidi rádi poznáme kdykoli. Napište nám na careers@klarnote.example a řekněte, čemu byste se chtěli věnovat."],
            sr: ["Uvek nam je drago da upoznamo talentovane ljude. Pišite nam na careers@klarnote.example i recite nam na čemu biste voleli da radite."],
            hu: ["Mindig örülünk a tehetséges embereknek. Írj a careers@klarnote.example címre, és meséld el, min dolgoznál szívesen."],
          }) },
        cta,
      ],
    },

    blog: {
      hero: {
        eyebrow: t({ uk: "Блог", en: "Blog", pl: "Blog", de: "Blog", ro: "Blog", cs: "Blog", sr: "Blog", hu: "Blog" }),
        title: t({
          uk: "Ідеї, оновлення та дослідження",
          en: "Ideas, updates and research",
          pl: "Pomysły, aktualności i badania",
          de: "Ideen, Updates und Forschung",
          ro: "Idei, noutăți și cercetare",
          cs: "Nápady, novinky a výzkum",
          sr: "Ideje, novosti i istraživanja",
          hu: "Ötletek, hírek és kutatás",
        }),
        sub: t({
          uk: "Як ми будуємо голосову документацію для медицини — без води.",
          en: "How we build voice documentation for healthcare — no fluff.",
          pl: "Jak budujemy głosową dokumentację dla medycyny — bez lania wody.",
          de: "Wie wir Sprachdokumentation für das Gesundheitswesen bauen — ohne Floskeln.",
          ro: "Cum construim documentația vocală pentru sănătate — fără vorbe goale.",
          cs: "Jak stavíme hlasovou dokumentaci pro zdravotnictví — bez omáčky.",
          sr: "Kako gradimo glasovnu dokumentaciju za zdravstvo — bez praznih priča.",
          hu: "Így építünk hangalapú dokumentációt az egészségügynek — felesleges körítés nélkül.",
        }),
      },
      blocks: [
        { type: "posts", items: t({
          uk: [
              { tag: "Продукт", title: "Як амбулаторний скрайб змінює прийом", excerpt: "Розбираємо, що відбувається від першого слова пацієнта до структурованої нотатки.", date: "12 трав. 2026", read: "6 хв" },
              { tag: "Дослідження", title: "Чому ми підсвічуємо слова низької впевненості", excerpt: "Прозорість моделі робить перевірку швидшою та безпечнішою.", date: "28 квіт. 2026", read: "8 хв" },
              { tag: "Безпека", title: "Незмінний аудит на практиці", excerpt: "Як ми гарантуємо цілісність кожного запису в журналі подій.", date: "9 квіт. 2026", read: "5 хв" },
              { tag: "Інженерія", title: "Потокове ASR із низькою затримкою", excerpt: "Архітектура, що дає розпізнавання в реальному часі без втрати точності.", date: "21 бер. 2026", read: "10 хв" },
              { tag: "Продукт", title: "Шаблони, які економлять години", excerpt: "Як структури нотаток адаптуються під спеціальність.", date: "3 бер. 2026", read: "4 хв" },
              { tag: "Компанія", title: "Чому ми починали з радіології", excerpt: "Історія першого прототипу Klarnote і чому він спрацював.", date: "15 лют. 2026", read: "7 хв" },
            ],
          en: [
              { tag: "Product", title: "How the ambient scribe changes a visit", excerpt: "What happens from the patient's first word to a structured note.", date: "May 12, 2026", read: "6 min" },
              { tag: "Research", title: "Why we highlight low-confidence words", excerpt: "Model transparency makes review faster and safer.", date: "Apr 28, 2026", read: "8 min" },
              { tag: "Security", title: "Immutable audit in practice", excerpt: "How we guarantee the integrity of every entry in the event log.", date: "Apr 9, 2026", read: "5 min" },
              { tag: "Engineering", title: "Low-latency streaming ASR", excerpt: "The architecture behind real-time recognition without losing accuracy.", date: "Mar 21, 2026", read: "10 min" },
              { tag: "Product", title: "Templates that save hours", excerpt: "How note structures adapt to your specialty.", date: "Mar 3, 2026", read: "4 min" },
              { tag: "Company", title: "Why we started with radiology", excerpt: "The story of Klarnote's first prototype and why it worked.", date: "Feb 15, 2026", read: "7 min" },
            ],
          pl: [
              { tag: "Produkt", title: "Jak ambient scribe zmienia wizytę", excerpt: "Co dzieje się od pierwszego słowa pacjenta do ustrukturyzowanej notatki.", date: "12 maja 2026", read: "6 min" },
              { tag: "Badania", title: "Dlaczego podświetlamy słowa o niskiej pewności", excerpt: "Przejrzystość modelu sprawia, że weryfikacja jest szybsza i bezpieczniejsza.", date: "28 kwietnia 2026", read: "8 min" },
              { tag: "Bezpieczeństwo", title: "Niezmienny audyt w praktyce", excerpt: "Jak gwarantujemy integralność każdego wpisu w dzienniku zdarzeń.", date: "9 kwietnia 2026", read: "5 min" },
              { tag: "Inżynieria", title: "Strumieniowe ASR o niskiej latencji", excerpt: "Architektura rozpoznawania w czasie rzeczywistym bez utraty dokładności.", date: "21 marca 2026", read: "10 min" },
              { tag: "Produkt", title: "Szablony, które oszczędzają godziny", excerpt: "Jak struktury notatek dopasowują się do Twojej specjalizacji.", date: "3 marca 2026", read: "4 min" },
              { tag: "Firma", title: "Dlaczego zaczęliśmy od radiologii", excerpt: "Historia pierwszego prototypu Klarnote i tego, dlaczego zadziałał.", date: "15 lutego 2026", read: "7 min" },
            ],
          de: [
              { tag: "Produkt", title: "Wie der Ambient Scribe die Sprechstunde verändert", excerpt: "Was vom ersten Wort des Patienten bis zur strukturierten Notiz passiert.", date: "12. Mai 2026", read: "6 Min." },
              { tag: "Forschung", title: "Warum wir Wörter mit niedriger Konfidenz hervorheben", excerpt: "Modelltransparenz macht die Durchsicht schneller und sicherer.", date: "28. April 2026", read: "8 Min." },
              { tag: "Sicherheit", title: "Unveränderliches Audit in der Praxis", excerpt: "Wie wir die Integrität jedes Eintrags im Ereignisprotokoll garantieren.", date: "9. April 2026", read: "5 Min." },
              { tag: "Engineering", title: "Streaming-ASR mit niedriger Latenz", excerpt: "Die Architektur hinter Echtzeit-Erkennung ohne Genauigkeitsverlust.", date: "21. März 2026", read: "10 Min." },
              { tag: "Produkt", title: "Vorlagen, die Stunden sparen", excerpt: "Wie sich Notizstrukturen an Ihre Fachrichtung anpassen.", date: "3. März 2026", read: "4 Min." },
              { tag: "Unternehmen", title: "Warum wir mit der Radiologie begonnen haben", excerpt: "Die Geschichte des ersten Klarnote-Prototyps und warum er funktionierte.", date: "15. Februar 2026", read: "7 Min." },
            ],
          ro: [
              { tag: "Produs", title: "Cum schimbă scribul ambient o consultație", excerpt: "Ce se întâmplă de la primul cuvânt al pacientului până la o notă structurată.", date: "12 mai 2026", read: "6 min" },
              { tag: "Cercetare", title: "De ce evidențiem cuvintele cu încredere scăzută", excerpt: "Transparența modelului face verificarea mai rapidă și mai sigură.", date: "28 aprilie 2026", read: "8 min" },
              { tag: "Securitate", title: "Auditul imuabil în practică", excerpt: "Cum garantăm integritatea fiecărei intrări din jurnalul de evenimente.", date: "9 aprilie 2026", read: "5 min" },
              { tag: "Inginerie", title: "ASR în flux cu latență redusă", excerpt: "Arhitectura din spatele recunoașterii în timp real, fără pierdere de acuratețe.", date: "21 martie 2026", read: "10 min" },
              { tag: "Produs", title: "Șabloane care economisesc ore", excerpt: "Cum se adaptează structurile notelor la specialitatea ta.", date: "3 martie 2026", read: "4 min" },
              { tag: "Companie", title: "De ce am început cu radiologia", excerpt: "Povestea primului prototip Klarnote și de ce a funcționat.", date: "15 februarie 2026", read: "7 min" },
            ],
          cs: [
              { tag: "Produkt", title: "Jak ambientní scribe mění vyšetření", excerpt: "Co se děje od prvního slova pacienta po strukturovanou poznámku.", date: "12. května 2026", read: "6 min" },
              { tag: "Výzkum", title: "Proč zvýrazňujeme slova s nízkou jistotou", excerpt: "Díky transparentnosti modelu je kontrola rychlejší a bezpečnější.", date: "28. dubna 2026", read: "8 min" },
              { tag: "Bezpečnost", title: "Neměnný audit v praxi", excerpt: "Jak garantujeme integritu každého záznamu v protokolu událostí.", date: "9. dubna 2026", read: "5 min" },
              { tag: "Inženýrství", title: "Streamované ASR s nízkou latencí", excerpt: "Architektura rozpoznávání v reálném čase bez ztráty přesnosti.", date: "21. března 2026", read: "10 min" },
              { tag: "Produkt", title: "Šablony, které šetří hodiny", excerpt: "Jak se struktury poznámek přizpůsobují vašemu oboru.", date: "3. března 2026", read: "4 min" },
              { tag: "Firma", title: "Proč jsme začali radiologií", excerpt: "Příběh prvního prototypu Klarnote a proč fungoval.", date: "15. února 2026", read: "7 min" },
            ],
          sr: [
              { tag: "Proizvod", title: "Kako ambijentalni skrajb menja pregled", excerpt: "Šta se dešava od prve reči pacijenta do strukturirane beleške.", date: "12. maj 2026.", read: "6 min" },
              { tag: "Istraživanje", title: "Zašto ističemo reči niske pouzdanosti", excerpt: "Transparentnost modela čini proveru bržom i bezbednijom.", date: "28. april 2026.", read: "8 min" },
              { tag: "Bezbednost", title: "Nepromenljiva revizija u praksi", excerpt: "Kako garantujemo integritet svakog unosa u dnevniku događaja.", date: "9. april 2026.", read: "5 min" },
              { tag: "Inženjering", title: "Strimovani ASR niske latencije", excerpt: "Arhitektura koja omogućava prepoznavanje u realnom vremenu bez gubitka tačnosti.", date: "21. mart 2026.", read: "10 min" },
              { tag: "Proizvod", title: "Šabloni koji štede sate", excerpt: "Kako se strukture beležaka prilagođavaju vašoj specijalnosti.", date: "3. mart 2026.", read: "4 min" },
              { tag: "Kompanija", title: "Zašto smo počeli od radiologije", excerpt: "Priča o prvom prototipu Klarnotea i zašto je uspeo.", date: "15. februar 2026.", read: "7 min" },
            ],
          hu: [
              { tag: "Termék", title: "Hogyan alakítja át a vizitet az ambient scribe", excerpt: "Mi történik a beteg első szavától a strukturált jegyzetig.", date: "2026. máj. 12.", read: "6 perc" },
              { tag: "Kutatás", title: "Miért emeljük ki az alacsony megbízhatóságú szavakat", excerpt: "A modell átláthatósága gyorsabbá és biztonságosabbá teszi az ellenőrzést.", date: "2026. ápr. 28.", read: "8 perc" },
              { tag: "Biztonság", title: "Megmásíthatatlan audit a gyakorlatban", excerpt: "Így garantáljuk az eseménynapló minden bejegyzésének sértetlenségét.", date: "2026. ápr. 9.", read: "5 perc" },
              { tag: "Mérnökség", title: "Alacsony késleltetésű streaming ASR", excerpt: "A valós idejű felismerés architektúrája pontosságvesztés nélkül.", date: "2026. márc. 21.", read: "10 perc" },
              { tag: "Termék", title: "Sablonok, amelyek órákat spórolnak", excerpt: "Hogyan igazodnak a jegyzetstruktúrák a szakterületedhez.", date: "2026. márc. 3.", read: "4 perc" },
              { tag: "Cég", title: "Miért a radiológiával kezdtük", excerpt: "A Klarnote első prototípusának története, és hogy miért működött.", date: "2026. febr. 15.", read: "7 perc" },
            ],
        }) },
      ],
    },

    /* ───────────────────────── Legal ───────────────────────── */
    "legal/privacy": {
      hero: {
        eyebrow: t({ uk: "Правове", en: "Legal", pl: "Informacje prawne", de: "Rechtliches", ro: "Legal", cs: "Právní informace", sr: "Pravno", hu: "Jogi információk" }),
        title: t({ uk: "Політика конфіденційності", en: "Privacy Policy", pl: "Polityka prywatności", de: "Datenschutzerklärung", ro: "Politica de confidențialitate", cs: "Zásady ochrany osobních údajů", sr: "Politika privatnosti", hu: "Adatvédelmi szabályzat" }),
        sub: t({
          uk: "Як Klarnote збирає, використовує та захищає дані.",
          en: "How Klarnote collects, uses and protects data.",
          pl: "Jak Klarnote zbiera, wykorzystuje i chroni dane.",
          de: "Wie Klarnote Daten erhebt, nutzt und schützt.",
          ro: "Cum colectează, utilizează și protejează Klarnote datele.",
          cs: "Jak Klarnote shromažďuje, používá a chrání data.",
          sr: "Kako Klarnote prikuplja, koristi i štiti podatke.",
          hu: "Hogyan gyűjti, használja és védi az adatokat a Klarnote.",
        }),
        updated: t({ uk: "Оновлено: 1 червня 2026", en: "Last updated: June 1, 2026", pl: "Ostatnia aktualizacja: 1 czerwca 2026", de: "Zuletzt aktualisiert: 1. Juni 2026", ro: "Ultima actualizare: 1 iunie 2026", cs: "Poslední aktualizace: 1. června 2026", sr: "Poslednje ažuriranje: 1. jun 2026.", hu: "Utolsó frissítés: 2026. június 1." }),
      },
      blocks: [
        { type: "prose", heading: t({ uk: "1. Які дані ми обробляємо", en: "1. Data we process", pl: "1. Jakie dane przetwarzamy", de: "1. Welche Daten wir verarbeiten", ro: "1. Ce date prelucrăm", cs: "1. Jaká data zpracováváme", sr: "1. Koje podatke obrađujemo", hu: "1. Milyen adatokat kezelünk" }),
          paragraphs: t({
            uk: ["Klarnote обробляє аудіозаписи прийомів, транскрипти, структуровані медичні нотатки та облікові дані користувачів. Дані пацієнтів обробляються виключно за дорученням медичного закладу."],
            en: ["Klarnote processes encounter audio, transcripts, structured medical notes and user account data. Patient data is processed solely on behalf of the healthcare organization."],
            pl: ["Klarnote przetwarza nagrania audio wizyt, transkrypty, ustrukturyzowane notatki medyczne oraz dane kont użytkowników. Dane pacjentów są przetwarzane wyłącznie w imieniu placówki medycznej."],
            de: ["Klarnote verarbeitet Audioaufnahmen von Sprechstunden, Transkripte, strukturierte medizinische Notizen und Nutzerkontodaten. Patientendaten werden ausschließlich im Auftrag der Gesundheitseinrichtung verarbeitet."],
            ro: ["Klarnote prelucrează înregistrările audio ale consultațiilor, transcrieri, note medicale structurate și datele conturilor de utilizator. Datele pacienților sunt prelucrate exclusiv în numele instituției medicale."],
            cs: ["Klarnote zpracovává audiozáznamy vyšetření, přepisy, strukturované lékařské poznámky a údaje uživatelských účtů. Data pacientů jsou zpracovávána výhradně z pověření zdravotnického zařízení."],
            sr: ["Klarnote obrađuje audio-snimke pregleda, transkripte, strukturirane medicinske beleške i podatke korisničkih naloga. Podaci pacijenata obrađuju se isključivo u ime zdravstvene ustanove."],
            hu: ["A Klarnote a vizitek hangfelvételeit, átiratokat, strukturált orvosi jegyzeteket és felhasználói fiókadatokat kezel. A betegadatokat kizárólag az egészségügyi intézmény megbízásából dolgozzuk fel."],
          }) },
        { type: "prose", heading: t({ uk: "2. Мета обробки", en: "2. Purpose", pl: "2. Cel przetwarzania", de: "2. Zweck", ro: "2. Scopul prelucrării", cs: "2. Účel zpracování", sr: "2. Svrha obrade", hu: "2. Az adatkezelés célja" }),
          bullets: t({
            uk: ["Перетворення мови на структуровані нотатки", "Зберігання та пошук документів", "Аудит дій та забезпечення безпеки", "Покращення якості розпізнавання у знеособленому вигляді"],
            en: ["Turning speech into structured notes", "Storing and retrieving documents", "Auditing actions and ensuring security", "Improving recognition quality in de-identified form"],
            pl: ["Zamiana mowy na ustrukturyzowane notatki", "Przechowywanie i wyszukiwanie dokumentów", "Audyt działań i zapewnienie bezpieczeństwa", "Poprawa jakości rozpoznawania na danych zanonimizowanych"],
            de: ["Umwandlung von Sprache in strukturierte Notizen", "Speicherung und Abruf von Dokumenten", "Prüfung von Aktionen und Gewährleistung der Sicherheit", "Verbesserung der Erkennungsqualität in de-identifizierter Form"],
            ro: ["Transformarea vorbirii în note structurate", "Stocarea și regăsirea documentelor", "Auditarea acțiunilor și asigurarea securității", "Îmbunătățirea calității recunoașterii în formă anonimizată"],
            cs: ["Převod řeči na strukturované poznámky", "Ukládání a vyhledávání dokumentů", "Audit akcí a zajištění bezpečnosti", "Zlepšování kvality rozpoznávání v anonymizované podobě"],
            sr: ["Pretvaranje govora u strukturirane beleške", "Čuvanje i pretraga dokumenata", "Revizija radnji i obezbeđivanje sigurnosti", "Poboljšanje kvaliteta prepoznavanja u anonimizovanom obliku"],
            hu: ["A beszéd strukturált jegyzetekké alakítása", "Dokumentumok tárolása és visszakeresése", "A műveletek auditálása és a biztonság garantálása", "A felismerés minőségének javítása anonimizált formában"],
          }) },
        { type: "prose", heading: t({ uk: "3. Правова підстава", en: "3. Legal basis", pl: "3. Podstawa prawna", de: "3. Rechtsgrundlage", ro: "3. Temeiul legal", cs: "3. Právní základ", sr: "3. Pravni osnov", hu: "3. Jogalap" }),
          paragraphs: t({
            uk: ["Обробка здійснюється на підставі договору з медичним закладом та згоди пацієнта, отриманої перед записом."],
            en: ["Processing is based on the agreement with the healthcare organization and the patient consent captured before recording."],
            pl: ["Przetwarzanie odbywa się na podstawie umowy z placówką medyczną oraz zgody pacjenta uzyskanej przed nagraniem."],
            de: ["Die Verarbeitung erfolgt auf Grundlage des Vertrags mit der Gesundheitseinrichtung und der vor der Aufnahme eingeholten Einwilligung des Patienten."],
            ro: ["Prelucrarea se face în baza contractului cu instituția medicală și a consimțământului pacientului obținut înainte de înregistrare."],
            cs: ["Zpracování probíhá na základě smlouvy se zdravotnickým zařízením a souhlasu pacienta získaného před nahráváním."],
            sr: ["Obrada se vrši na osnovu ugovora sa zdravstvenom ustanovom i saglasnosti pacijenta pribavljene pre snimanja."],
            hu: ["Az adatkezelés az egészségügyi intézménnyel kötött szerződésen és a felvétel előtt rögzített betegbeleegyezésen alapul."],
          }) },
        { type: "prose", heading: t({ uk: "4. Зберігання та видалення", en: "4. Retention & deletion", pl: "4. Przechowywanie i usuwanie", de: "4. Aufbewahrung & Löschung", ro: "4. Păstrarea și ștergerea datelor", cs: "4. Uchovávání a mazání", sr: "4. Čuvanje i brisanje", hu: "4. Megőrzés és törlés" }),
          paragraphs: t({
            uk: ["Дані зберігаються стільки, скільки вимагає медичний заклад або законодавство. Ви можете запросити видалення даних, що не підпадають під обов'язкове зберігання."],
            en: ["Data is retained for as long as the organization or law requires. You can request deletion of data not subject to mandatory retention."],
            pl: ["Dane są przechowywane tak długo, jak wymaga tego placówka lub przepisy prawa. Możesz zażądać usunięcia danych, które nie podlegają obowiązkowemu przechowywaniu."],
            de: ["Daten werden so lange aufbewahrt, wie es die Einrichtung oder das Gesetz verlangt. Sie können die Löschung von Daten verlangen, die keiner gesetzlichen Aufbewahrungspflicht unterliegen."],
            ro: ["Datele sunt păstrate atât timp cât o cere instituția sau legislația. Puteți solicita ștergerea datelor care nu fac obiectul păstrării obligatorii."],
            cs: ["Data jsou uchovávána tak dlouho, jak vyžaduje zařízení nebo zákon. Můžete požádat o smazání dat, na která se nevztahuje povinné uchovávání."],
            sr: ["Podaci se čuvaju onoliko dugo koliko to zahteva ustanova ili zakon. Možete zatražiti brisanje podataka koji ne podležu obaveznom čuvanju."],
            hu: ["Az adatokat addig őrizzük meg, ameddig az intézmény vagy a jogszabály előírja. Kérheti azon adatok törlését, amelyekre nem vonatkozik kötelező megőrzés."],
          }) },
        { type: "prose", heading: t({ uk: "5. Ваші права", en: "5. Your rights", pl: "5. Twoje prawa", de: "5. Ihre Rechte", ro: "5. Drepturile dumneavoastră", cs: "5. Vaše práva", sr: "5. Vaša prava", hu: "5. Az Ön jogai" }),
          bullets: t({
            uk: ["Доступ до своїх даних", "Виправлення неточних даних", "Видалення там, де це дозволено", "Перенесення даних", "Скарга до наглядового органу"],
            en: ["Access your data", "Correct inaccurate data", "Deletion where permitted", "Data portability", "Complaint to a supervisory authority"],
            pl: ["Dostęp do swoich danych", "Sprostowanie nieprawidłowych danych", "Usunięcie tam, gdzie jest to dozwolone", "Przenoszenie danych", "Skarga do organu nadzorczego"],
            de: ["Auskunft über Ihre Daten", "Berichtigung unrichtiger Daten", "Löschung, soweit zulässig", "Datenübertragbarkeit", "Beschwerde bei einer Aufsichtsbehörde"],
            ro: ["Acces la datele proprii", "Rectificarea datelor inexacte", "Ștergere acolo unde este permisă", "Portabilitatea datelor", "Plângere la autoritatea de supraveghere"],
            cs: ["Přístup ke svým datům", "Oprava nepřesných dat", "Výmaz tam, kde je to povoleno", "Přenositelnost dat", "Stížnost u dozorového úřadu"],
            sr: ["Pristup svojim podacima", "Ispravka netačnih podataka", "Brisanje tamo gde je dozvoljeno", "Prenosivost podataka", "Pritužba nadzornom organu"],
            hu: ["Hozzáférés a saját adataihoz", "A pontatlan adatok helyesbítése", "Törlés, ahol megengedett", "Adathordozhatóság", "Panasz a felügyeleti hatóságnál"],
          }) },
        { type: "prose", heading: t({ uk: "6. Контакт", en: "6. Contact", pl: "6. Kontakt", de: "6. Kontakt", ro: "6. Contact", cs: "6. Kontakt", sr: "6. Kontakt", hu: "6. Kapcsolat" }),
          paragraphs: t({
            uk: ["З питань конфіденційності пишіть на privacy@klarnote.example."],
            en: ["For privacy questions write to privacy@klarnote.example."],
            pl: ["W sprawach prywatności napisz na privacy@klarnote.example."],
            de: ["Bei Datenschutzfragen schreiben Sie an privacy@klarnote.example."],
            ro: ["Pentru întrebări legate de confidențialitate scrieți la privacy@klarnote.example."],
            cs: ["S dotazy k ochraně osobních údajů pište na privacy@klarnote.example."],
            sr: ["Za pitanja o privatnosti pišite na privacy@klarnote.example."],
            hu: ["Adatvédelmi kérdésekben írjon a privacy@klarnote.example címre."],
          }) },
      ],
    },

    "legal/terms": {
      hero: {
        eyebrow: t({ uk: "Правове", en: "Legal", pl: "Informacje prawne", de: "Rechtliches", ro: "Legal", cs: "Právní informace", sr: "Pravno", hu: "Jogi információk" }),
        title: t({ uk: "Умови використання", en: "Terms of Service", pl: "Warunki korzystania z usługi", de: "Nutzungsbedingungen", ro: "Termeni și condiții", cs: "Podmínky služby", sr: "Uslovi korišćenja", hu: "Felhasználási feltételek" }),
        sub: t({
          uk: "Правила користування платформою Klarnote.",
          en: "The rules for using the Klarnote platform.",
          pl: "Zasady korzystania z platformy Klarnote.",
          de: "Die Regeln für die Nutzung der Klarnote-Plattform.",
          ro: "Regulile de utilizare a platformei Klarnote.",
          cs: "Pravidla používání platformy Klarnote.",
          sr: "Pravila korišćenja platforme Klarnote.",
          hu: "A Klarnote platform használatának szabályai.",
        }),
        updated: t({ uk: "Оновлено: 1 червня 2026", en: "Last updated: June 1, 2026", pl: "Ostatnia aktualizacja: 1 czerwca 2026", de: "Zuletzt aktualisiert: 1. Juni 2026", ro: "Ultima actualizare: 1 iunie 2026", cs: "Poslední aktualizace: 1. června 2026", sr: "Poslednje ažuriranje: 1. jun 2026.", hu: "Utolsó frissítés: 2026. június 1." }),
      },
      blocks: [
        { type: "prose", heading: t({ uk: "1. Прийняття умов", en: "1. Acceptance", pl: "1. Akceptacja warunków", de: "1. Zustimmung", ro: "1. Acceptarea condițiilor", cs: "1. Přijetí podmínek", sr: "1. Prihvatanje uslova", hu: "1. A feltételek elfogadása" }),
          paragraphs: t({
            uk: ["Користуючись Klarnote, ви погоджуєтеся з цими умовами. Якщо ви не згодні — не використовуйте сервіс."],
            en: ["By using Klarnote you agree to these terms. If you do not agree, do not use the service."],
            pl: ["Korzystając z Klarnote, akceptujesz niniejsze warunki. Jeśli się z nimi nie zgadzasz — nie korzystaj z usługi."],
            de: ["Mit der Nutzung von Klarnote stimmen Sie diesen Bedingungen zu. Wenn Sie nicht einverstanden sind, nutzen Sie den Dienst nicht."],
            ro: ["Prin utilizarea Klarnote acceptați acești termeni. Dacă nu sunteți de acord, nu utilizați serviciul."],
            cs: ["Používáním Klarnote souhlasíte s těmito podmínkami. Pokud nesouhlasíte, službu nepoužívejte."],
            sr: ["Korišćenjem Klarnotea prihvatate ove uslove. Ako se ne slažete, nemojte koristiti uslugu."],
            hu: ["A Klarnote használatával elfogadja ezeket a feltételeket. Ha nem ért egyet velük, ne használja a szolgáltatást."],
          }) },
        { type: "prose", heading: t({ uk: "2. Обліковий запис", en: "2. Accounts", pl: "2. Konta", de: "2. Konten", ro: "2. Conturi", cs: "2. Účty", sr: "2. Nalozi", hu: "2. Fiókok" }),
          paragraphs: t({
            uk: ["Доступ надається через запрошення адміністратора закладу. Ви відповідаєте за збереження своїх облікових даних."],
            en: ["Access is granted by your organization's admin via invitation. You are responsible for safeguarding your credentials."],
            pl: ["Dostęp jest przyznawany przez administratora placówki na podstawie zaproszenia. Odpowiadasz za ochronę swoich danych logowania."],
            de: ["Der Zugang wird vom Administrator Ihrer Einrichtung per Einladung gewährt. Sie sind für den Schutz Ihrer Zugangsdaten verantwortlich."],
            ro: ["Accesul este acordat de administratorul instituției prin invitație. Sunteți responsabil de protejarea datelor de autentificare."],
            cs: ["Přístup uděluje administrátor vašeho zařízení prostřednictvím pozvánky. Za ochranu svých přihlašovacích údajů odpovídáte vy."],
            sr: ["Pristup dodeljuje administrator vaše ustanove putem pozivnice. Vi ste odgovorni za čuvanje svojih pristupnih podataka."],
            hu: ["A hozzáférést az intézmény adminisztrátora biztosítja meghívással. A belépési adatai megőrzéséért Ön felel."],
          }) },
        { type: "prose", heading: t({ uk: "3. Допустиме використання", en: "3. Acceptable use", pl: "3. Dozwolone użycie", de: "3. Zulässige Nutzung", ro: "3. Utilizare acceptabilă", cs: "3. Přijatelné použití", sr: "3. Dozvoljena upotreba", hu: "3. Megengedett használat" }),
          bullets: t({
            uk: ["Використовуйте сервіс лише в законних медичних цілях", "Не намагайтеся обійти контроль доступу", "Не завантажуйте шкідливий код", "Поважайте права пацієнтів і колег"],
            en: ["Use the service only for lawful medical purposes", "Do not attempt to bypass access controls", "Do not upload malicious code", "Respect the rights of patients and colleagues"],
            pl: ["Korzystaj z usługi wyłącznie w zgodnych z prawem celach medycznych", "Nie próbuj obchodzić kontroli dostępu", "Nie przesyłaj złośliwego kodu", "Szanuj prawa pacjentów i współpracowników"],
            de: ["Nutzen Sie den Dienst nur für rechtmäßige medizinische Zwecke", "Versuchen Sie nicht, Zugriffskontrollen zu umgehen", "Laden Sie keinen Schadcode hoch", "Respektieren Sie die Rechte von Patienten und Kollegen"],
            ro: ["Utilizați serviciul doar în scopuri medicale legale", "Nu încercați să ocoliți controalele de acces", "Nu încărcați cod malițios", "Respectați drepturile pacienților și ale colegilor"],
            cs: ["Používejte službu pouze k zákonným lékařským účelům", "Nepokoušejte se obcházet řízení přístupu", "Nenahrávejte škodlivý kód", "Respektujte práva pacientů a kolegů"],
            sr: ["Koristite uslugu samo u zakonite medicinske svrhe", "Ne pokušavajte da zaobiđete kontrolu pristupa", "Ne otpremajte zlonamerni kod", "Poštujte prava pacijenata i kolega"],
            hu: ["A szolgáltatást kizárólag jogszerű orvosi célokra használja", "Ne próbálja megkerülni a hozzáférés-vezérlést", "Ne töltsön fel rosszindulatú kódot", "Tartsa tiszteletben a betegek és a kollégák jogait"],
          }) },
        { type: "prose", heading: t({ uk: "4. Доступність сервісу", en: "4. Service availability", pl: "4. Dostępność usługi", de: "4. Verfügbarkeit des Dienstes", ro: "4. Disponibilitatea serviciului", cs: "4. Dostupnost služby", sr: "4. Dostupnost usluge", hu: "4. A szolgáltatás rendelkezésre állása" }),
          paragraphs: t({
            uk: ["Ми прагнемо до високої доступності, але не гарантуємо безперебійну роботу. Планові роботи анонсуються заздалегідь."],
            en: ["We aim for high availability but do not guarantee uninterrupted operation. Planned maintenance is announced in advance."],
            pl: ["Dążymy do wysokiej dostępności, ale nie gwarantujemy nieprzerwanego działania. Planowane prace są ogłaszane z wyprzedzeniem."],
            de: ["Wir streben eine hohe Verfügbarkeit an, garantieren jedoch keinen unterbrechungsfreien Betrieb. Geplante Wartungen werden im Voraus angekündigt."],
            ro: ["Urmărim o disponibilitate ridicată, dar nu garantăm funcționarea neîntreruptă. Lucrările planificate sunt anunțate în avans."],
            cs: ["Usilujeme o vysokou dostupnost, ale nezaručujeme nepřetržitý provoz. Plánovaná údržba je oznamována předem."],
            sr: ["Težimo visokoj dostupnosti, ali ne garantujemo neprekidan rad. Planirani radovi se najavljuju unapred."],
            hu: ["Magas rendelkezésre állásra törekszünk, de nem garantáljuk a megszakítás nélküli működést. A tervezett karbantartást előre bejelentjük."],
          }) },
        { type: "prose", heading: t({ uk: "5. Відповідальність", en: "5. Liability", pl: "5. Odpowiedzialność", de: "5. Haftung", ro: "5. Răspunderea", cs: "5. Odpovědnost", sr: "5. Odgovornost", hu: "5. Felelősség" }),
          paragraphs: t({
            uk: ["Klarnote — інструмент підтримки документації. Остаточна відповідальність за зміст медичних записів лежить на лікарі."],
            en: ["Klarnote is a documentation support tool. Final responsibility for the content of medical records rests with the clinician."],
            pl: ["Klarnote to narzędzie wspierające dokumentację. Ostateczna odpowiedzialność za treść dokumentacji medycznej spoczywa na lekarzu."],
            de: ["Klarnote ist ein Werkzeug zur Dokumentationsunterstützung. Die letzte Verantwortung für den Inhalt medizinischer Aufzeichnungen liegt bei der Ärztin oder dem Arzt."],
            ro: ["Klarnote este un instrument de sprijin pentru documentație. Responsabilitatea finală pentru conținutul documentelor medicale îi revine medicului."],
            cs: ["Klarnote je nástroj na podporu dokumentace. Konečnou odpovědnost za obsah zdravotnických záznamů nese lékař."],
            sr: ["Klarnote je alat za podršku dokumentaciji. Krajnja odgovornost za sadržaj medicinske dokumentacije leži na lekaru."],
            hu: ["A Klarnote a dokumentációt támogató eszköz. Az orvosi feljegyzések tartalmáért a végső felelősség az orvost terheli."],
          }) },
        { type: "prose", heading: t({ uk: "6. Зміни умов", en: "6. Changes", pl: "6. Zmiany warunków", de: "6. Änderungen", ro: "6. Modificări", cs: "6. Změny podmínek", sr: "6. Izmene uslova", hu: "6. A feltételek módosítása" }),
          paragraphs: t({
            uk: ["Ми можемо оновлювати ці умови; про суттєві зміни повідомимо заздалегідь."],
            en: ["We may update these terms; we will notify you of material changes in advance."],
            pl: ["Możemy aktualizować niniejsze warunki; o istotnych zmianach poinformujemy z wyprzedzeniem."],
            de: ["Wir können diese Bedingungen aktualisieren; über wesentliche Änderungen informieren wir im Voraus."],
            ro: ["Putem actualiza acești termeni; vă vom anunța în avans despre modificările importante."],
            cs: ["Tyto podmínky můžeme aktualizovat; o podstatných změnách vás budeme informovat předem."],
            sr: ["Možemo ažurirati ove uslove; o bitnim izmenama obavestićemo vas unapred."],
            hu: ["Ezeket a feltételeket frissíthetjük; a lényeges változásokról előre értesítjük."],
          }) },
      ],
    },

    "legal/data": {
      hero: {
        eyebrow: t({ uk: "Правове", en: "Legal", pl: "Informacje prawne", de: "Rechtliches", ro: "Legal", cs: "Právní informace", sr: "Pravno", hu: "Jogi információk" }),
        title: t({ uk: "Обробка даних", en: "Data Processing", pl: "Przetwarzanie danych", de: "Datenverarbeitung", ro: "Prelucrarea datelor", cs: "Zpracování dat", sr: "Obrada podataka", hu: "Adatfeldolgozás" }),
        sub: t({
          uk: "Як ми діємо як обробник даних для медичних закладів.",
          en: "How we act as a data processor for healthcare organizations.",
          pl: "Jak działamy jako podmiot przetwarzający dane dla placówek medycznych.",
          de: "Wie wir als Auftragsverarbeiter für Gesundheitseinrichtungen handeln.",
          ro: "Cum acționăm ca persoană împuternicită de operator pentru instituțiile medicale.",
          cs: "Jak působíme jako zpracovatel dat pro zdravotnická zařízení.",
          sr: "Kako postupamo kao obrađivač podataka za zdravstvene ustanove.",
          hu: "Hogyan járunk el adatfeldolgozóként egészségügyi intézmények számára.",
        }),
        updated: t({ uk: "Оновлено: 1 червня 2026", en: "Last updated: June 1, 2026", pl: "Ostatnia aktualizacja: 1 czerwca 2026", de: "Zuletzt aktualisiert: 1. Juni 2026", ro: "Ultima actualizare: 1 iunie 2026", cs: "Poslední aktualizace: 1. června 2026", sr: "Poslednje ažuriranje: 1. jun 2026.", hu: "Utolsó frissítés: 2026. június 1." }),
      },
      blocks: [
        { type: "prose", heading: t({ uk: "Ролі сторін", en: "Roles", pl: "Role stron", de: "Rollen der Parteien", ro: "Rolurile părților", cs: "Role stran", sr: "Uloge strana", hu: "A felek szerepei" }),
          paragraphs: t({
            uk: ["Медичний заклад є контролером даних. Klarnote діє як обробник і обробляє дані виключно за документованими інструкціями закладу."],
            en: ["The healthcare organization is the data controller. Klarnote acts as a processor and processes data only on the organization's documented instructions."],
            pl: ["Placówka medyczna jest administratorem danych. Klarnote działa jako podmiot przetwarzający i przetwarza dane wyłącznie zgodnie z udokumentowanymi poleceniami placówki."],
            de: ["Die Gesundheitseinrichtung ist der Verantwortliche. Klarnote handelt als Auftragsverarbeiter und verarbeitet Daten ausschließlich nach den dokumentierten Weisungen der Einrichtung."],
            ro: ["Instituția medicală este operatorul de date. Klarnote acționează ca persoană împuternicită și prelucrează datele exclusiv conform instrucțiunilor documentate ale instituției."],
            cs: ["Zdravotnické zařízení je správcem dat. Klarnote působí jako zpracovatel a zpracovává data výhradně podle dokumentovaných pokynů zařízení."],
            sr: ["Zdravstvena ustanova je rukovalac podacima. Klarnote deluje kao obrađivač i obrađuje podatke isključivo prema dokumentovanim uputstvima ustanove."],
            hu: ["Az egészségügyi intézmény az adatkezelő. A Klarnote adatfeldolgozóként jár el, és az adatokat kizárólag az intézmény dokumentált utasításai szerint dolgozza fel."],
          }) },
        { type: "grid", heading: t({ uk: "Заходи захисту", en: "Safeguards", pl: "Środki ochrony", de: "Schutzmaßnahmen", ro: "Măsuri de protecție", cs: "Ochranná opatření", sr: "Mere zaštite", hu: "Védelmi intézkedések" }), cols: 3, items: t({
          uk: [
              { icon: "shield", title: "Шифрування", desc: "Дані шифруються під час передачі та зберігання." },
              { icon: "users", title: "Рольовий доступ", desc: "Доступ за принципом найменших привілеїв." },
              { icon: "history", title: "Аудит", desc: "Кожна дія з даними фіксується незмінно." },
              { icon: "archive", title: "Резервні копії", desc: "Регулярне резервне копіювання з контролем цілісності." },
              { icon: "scan", title: "Знеособлення", desc: "Дані для покращення моделі знеособлюються." },
              { icon: "check", title: "Субобробники", desc: "Перелік субобробників доступний за запитом." },
            ],
          en: [
              { icon: "shield", title: "Encryption", desc: "Data is encrypted in transit and at rest." },
              { icon: "users", title: "Role-based access", desc: "Least-privilege access throughout." },
              { icon: "history", title: "Audit", desc: "Every data action is logged immutably." },
              { icon: "archive", title: "Backups", desc: "Regular backups with integrity checks." },
              { icon: "scan", title: "De-identification", desc: "Data used to improve the model is de-identified." },
              { icon: "check", title: "Sub-processors", desc: "A list of sub-processors is available on request." },
            ],
          pl: [
              { icon: "shield", title: "Szyfrowanie", desc: "Dane są szyfrowane podczas przesyłania i przechowywania." },
              { icon: "users", title: "Dostęp oparty na rolach", desc: "Dostęp według zasady najmniejszych uprawnień." },
              { icon: "history", title: "Audyt", desc: "Każda operacja na danych jest rejestrowana w sposób niezmienny." },
              { icon: "archive", title: "Kopie zapasowe", desc: "Regularne kopie zapasowe z kontrolą integralności." },
              { icon: "scan", title: "Anonimizacja", desc: "Dane używane do ulepszania modelu są anonimizowane." },
              { icon: "check", title: "Podprocesorzy", desc: "Lista podprocesorów dostępna na żądanie." },
            ],
          de: [
              { icon: "shield", title: "Verschlüsselung", desc: "Daten werden bei Übertragung und Speicherung verschlüsselt." },
              { icon: "users", title: "Rollenbasierter Zugriff", desc: "Durchgehend Least-Privilege-Zugriff." },
              { icon: "history", title: "Audit", desc: "Jede Datenaktion wird unveränderlich protokolliert." },
              { icon: "archive", title: "Backups", desc: "Regelmäßige Backups mit Integritätsprüfungen." },
              { icon: "scan", title: "De-Identifikation", desc: "Daten zur Modellverbesserung werden de-identifiziert." },
              { icon: "check", title: "Unterauftragsverarbeiter", desc: "Eine Liste der Unterauftragsverarbeiter ist auf Anfrage erhältlich." },
            ],
          ro: [
              { icon: "shield", title: "Criptare", desc: "Datele sunt criptate în tranzit și în repaus." },
              { icon: "users", title: "Acces bazat pe roluri", desc: "Acces pe principiul privilegiilor minime." },
              { icon: "history", title: "Audit", desc: "Fiecare acțiune asupra datelor este consemnată imuabil." },
              { icon: "archive", title: "Copii de rezervă", desc: "Copii de rezervă regulate, cu verificarea integrității." },
              { icon: "scan", title: "Anonimizare", desc: "Datele folosite pentru îmbunătățirea modelului sunt anonimizate." },
              { icon: "check", title: "Subîmputerniciți", desc: "Lista subîmputerniciților este disponibilă la cerere." },
            ],
          cs: [
              { icon: "shield", title: "Šifrování", desc: "Data jsou šifrována při přenosu i v klidu." },
              { icon: "users", title: "Přístup podle rolí", desc: "Přístup podle zásady nejnižších oprávnění." },
              { icon: "history", title: "Audit", desc: "Každá akce s daty je neměnně zaznamenána." },
              { icon: "archive", title: "Zálohy", desc: "Pravidelné zálohy s kontrolou integrity." },
              { icon: "scan", title: "Anonymizace", desc: "Data pro zlepšování modelu jsou anonymizována." },
              { icon: "check", title: "Subzpracovatelé", desc: "Seznam subzpracovatelů je k dispozici na vyžádání." },
            ],
          sr: [
              { icon: "shield", title: "Šifrovanje", desc: "Podaci se šifruju tokom prenosa i skladištenja." },
              { icon: "users", title: "Pristup po ulogama", desc: "Pristup po principu najmanjih privilegija." },
              { icon: "history", title: "Revizija", desc: "Svaka radnja nad podacima beleži se nepromenljivo." },
              { icon: "archive", title: "Rezervne kopije", desc: "Redovne rezervne kopije uz proveru integriteta." },
              { icon: "scan", title: "Anonimizacija", desc: "Podaci za poboljšanje modela se anonimizuju." },
              { icon: "check", title: "Podobrađivači", desc: "Spisak podobrađivača dostupan je na zahtev." },
            ],
          hu: [
              { icon: "shield", title: "Titkosítás", desc: "Az adatok átvitel közben és tároláskor is titkosítottak." },
              { icon: "users", title: "Szerepkör-alapú hozzáférés", desc: "Hozzáférés a legkisebb jogosultság elve szerint." },
              { icon: "history", title: "Audit", desc: "Minden adatművelet megmásíthatatlanul naplózott." },
              { icon: "archive", title: "Biztonsági mentések", desc: "Rendszeres mentések integritás-ellenőrzéssel." },
              { icon: "scan", title: "Anonimizálás", desc: "A modell fejlesztéséhez használt adatokat anonimizáljuk." },
              { icon: "check", title: "Al-adatfeldolgozók", desc: "Az al-adatfeldolgozók listája kérésre elérhető." },
            ],
        }) },
        { type: "prose", heading: t({ uk: "Передача даних", en: "Data transfers", pl: "Przekazywanie danych", de: "Datenübermittlungen", ro: "Transferuri de date", cs: "Předávání dat", sr: "Prenos podataka", hu: "Adattovábbítás" }),
          paragraphs: t({
            uk: ["Дані обробляються в межах узгоджених юрисдикцій. Будь-яка транскордонна передача супроводжується належними гарантіями."],
            en: ["Data is processed within agreed jurisdictions. Any cross-border transfer is covered by appropriate safeguards."],
            pl: ["Dane są przetwarzane w uzgodnionych jurysdykcjach. Każde transgraniczne przekazanie objęte jest odpowiednimi zabezpieczeniami."],
            de: ["Daten werden innerhalb vereinbarter Jurisdiktionen verarbeitet. Jede grenzüberschreitende Übermittlung ist durch geeignete Garantien abgesichert."],
            ro: ["Datele sunt prelucrate în jurisdicțiile convenite. Orice transfer transfrontalier este acoperit de garanții adecvate."],
            cs: ["Data jsou zpracovávána v dohodnutých jurisdikcích. Každé přeshraniční předání je kryto vhodnými zárukami."],
            sr: ["Podaci se obrađuju u okviru dogovorenih jurisdikcija. Svaki prekogranični prenos prate odgovarajuće mere zaštite."],
            hu: ["Az adatokat a megállapodás szerinti joghatóságokon belül dolgozzuk fel. Minden határon átnyúló továbbítást megfelelő garanciák kísérnek."],
          }) },
        { type: "prose", heading: t({ uk: "Інциденти", en: "Incidents", pl: "Incydenty", de: "Vorfälle", ro: "Incidente", cs: "Incidenty", sr: "Incidenti", hu: "Incidensek" }),
          paragraphs: t({
            uk: ["У разі інциденту безпеки ми повідомляємо заклад без невиправданих затримок і надаємо інформацію для оцінки впливу."],
            en: ["In the event of a security incident we notify the organization without undue delay and provide information to assess impact."],
            pl: ["W razie incydentu bezpieczeństwa powiadamiamy placówkę bez zbędnej zwłoki i przekazujemy informacje potrzebne do oceny skutków."],
            de: ["Bei einem Sicherheitsvorfall benachrichtigen wir die Einrichtung ohne unangemessene Verzögerung und stellen Informationen zur Bewertung der Auswirkungen bereit."],
            ro: ["În cazul unui incident de securitate, notificăm instituția fără întârzieri nejustificate și oferim informații pentru evaluarea impactului."],
            cs: ["V případě bezpečnostního incidentu informujeme zařízení bez zbytečného odkladu a poskytneme informace pro posouzení dopadu."],
            sr: ["U slučaju bezbednosnog incidenta obaveštavamo ustanovu bez nepotrebnog odlaganja i pružamo informacije za procenu uticaja."],
            hu: ["Biztonsági incidens esetén indokolatlan késedelem nélkül értesítjük az intézményt, és információt adunk a hatás felméréséhez."],
          }) },
      ],
    },

    "legal/consent": {
      hero: {
        eyebrow: t({ uk: "Правове", en: "Legal", pl: "Informacje prawne", de: "Rechtliches", ro: "Legal", cs: "Právní informace", sr: "Pravno", hu: "Jogi információk" }),
        title: t({ uk: "Згода пацієнта", en: "Patient Consent", pl: "Zgoda pacjenta", de: "Patienteneinwilligung", ro: "Consimțământul pacientului", cs: "Souhlas pacienta", sr: "Saglasnost pacijenta", hu: "Betegbeleegyezés" }),
        sub: t({
          uk: "Як Klarnote фіксує та поважає згоду перед записом.",
          en: "How Klarnote captures and respects consent before recording.",
          pl: "Jak Klarnote rejestruje i respektuje zgodę przed nagraniem.",
          de: "Wie Klarnote die Einwilligung vor der Aufnahme erfasst und respektiert.",
          ro: "Cum înregistrează și respectă Klarnote consimțământul înainte de înregistrare.",
          cs: "Jak Klarnote zaznamenává a respektuje souhlas před nahráváním.",
          sr: "Kako Klarnote beleži i poštuje saglasnost pre snimanja.",
          hu: "Hogyan rögzíti és tartja tiszteletben a Klarnote a beleegyezést a felvétel előtt.",
        }),
        updated: t({ uk: "Оновлено: 1 червня 2026", en: "Last updated: June 1, 2026", pl: "Ostatnia aktualizacja: 1 czerwca 2026", de: "Zuletzt aktualisiert: 1. Juni 2026", ro: "Ultima actualizare: 1 iunie 2026", cs: "Poslední aktualizace: 1. června 2026", sr: "Poslednje ažuriranje: 1. jun 2026.", hu: "Utolsó frissítés: 2026. június 1." }),
      },
      blocks: [
        { type: "prose", heading: t({ uk: "Згода перед записом", en: "Consent before recording", pl: "Zgoda przed nagraniem", de: "Einwilligung vor der Aufnahme", ro: "Consimțământ înainte de înregistrare", cs: "Souhlas před nahráváním", sr: "Saglasnost pre snimanja", hu: "Beleegyezés a felvétel előtt" }),
          paragraphs: t({
            uk: ["Жоден запис не починається без явної згоди пацієнта. Лікар фіксує згоду на екрані згоди, а прозорий індикатор показує стан запису протягом усього прийому."],
            en: ["No recording starts without the patient's explicit consent. The clinician captures consent on the consent screen, and a transparent indicator shows the recording state throughout the visit."],
            pl: ["Żadne nagranie nie rozpoczyna się bez wyraźnej zgody pacjenta. Lekarz rejestruje zgodę na ekranie zgody, a przejrzysty wskaźnik pokazuje stan nagrywania przez całą wizytę."],
            de: ["Keine Aufnahme beginnt ohne die ausdrückliche Einwilligung des Patienten. Die Ärztin oder der Arzt erfasst die Einwilligung auf dem Einwilligungsbildschirm, und ein transparenter Indikator zeigt den Aufnahmestatus während der gesamten Sprechstunde."],
            ro: ["Nicio înregistrare nu începe fără consimțământul explicit al pacientului. Medicul înregistrează consimțământul pe ecranul dedicat, iar un indicator transparent arată starea înregistrării pe toată durata consultației."],
            cs: ["Žádné nahrávání nezačne bez výslovného souhlasu pacienta. Lékař zaznamená souhlas na obrazovce souhlasu a transparentní indikátor ukazuje stav nahrávání po celou dobu vyšetření."],
            sr: ["Nijedno snimanje ne počinje bez izričite saglasnosti pacijenta. Lekar beleži saglasnost na ekranu za saglasnost, a transparentni indikator prikazuje status snimanja tokom celog pregleda."],
            hu: ["Egyetlen felvétel sem indul a beteg kifejezett beleegyezése nélkül. Az orvos a beleegyezést a beleegyezési képernyőn rögzíti, és egy jól látható jelző mutatja a felvétel állapotát a vizit teljes ideje alatt."],
          }) },
        { type: "steps", heading: t({ uk: "Як це працює", en: "How it works", pl: "Jak to działa", de: "So funktioniert es", ro: "Cum funcționează", cs: "Jak to funguje", sr: "Kako funkcioniše", hu: "Így működik" }), items: t({
          uk: [
              { n: "01", title: "Пояснення", desc: "Лікар пояснює, що прийом записуватиметься для документації." },
              { n: "02", title: "Згода", desc: "Пацієнт надає згоду, яка фіксується разом із часом." },
              { n: "03", title: "Індикатор", desc: "Видимий індикатор показує, що триває запис." },
              { n: "04", title: "Відкликання", desc: "Пацієнт може відкликати згоду будь-коли — запис зупиняється." },
            ],
          en: [
              { n: "01", title: "Explain", desc: "The clinician explains the visit will be recorded for documentation." },
              { n: "02", title: "Consent", desc: "The patient grants consent, captured with a timestamp." },
              { n: "03", title: "Indicator", desc: "A visible indicator shows recording is in progress." },
              { n: "04", title: "Withdraw", desc: "The patient can withdraw consent at any time — recording stops." },
            ],
          pl: [
              { n: "01", title: "Wyjaśnienie", desc: "Lekarz wyjaśnia, że wizyta będzie nagrywana na potrzeby dokumentacji." },
              { n: "02", title: "Zgoda", desc: "Pacjent udziela zgody, która jest rejestrowana wraz ze znacznikiem czasu." },
              { n: "03", title: "Wskaźnik", desc: "Widoczny wskaźnik pokazuje, że trwa nagrywanie." },
              { n: "04", title: "Wycofanie", desc: "Pacjent może wycofać zgodę w dowolnym momencie — nagrywanie się zatrzymuje." },
            ],
          de: [
              { n: "01", title: "Erklären", desc: "Die Ärztin oder der Arzt erklärt, dass die Sprechstunde zur Dokumentation aufgezeichnet wird." },
              { n: "02", title: "Einwilligen", desc: "Der Patient erteilt die Einwilligung, die mit Zeitstempel erfasst wird." },
              { n: "03", title: "Indikator", desc: "Ein sichtbarer Indikator zeigt, dass eine Aufnahme läuft." },
              { n: "04", title: "Widerrufen", desc: "Der Patient kann die Einwilligung jederzeit widerrufen — die Aufnahme stoppt." },
            ],
          ro: [
              { n: "01", title: "Explicare", desc: "Medicul explică faptul că consultația va fi înregistrată pentru documentație." },
              { n: "02", title: "Consimțământ", desc: "Pacientul își dă consimțământul, înregistrat cu marcaj de timp." },
              { n: "03", title: "Indicator", desc: "Un indicator vizibil arată că înregistrarea este în curs." },
              { n: "04", title: "Retragere", desc: "Pacientul își poate retrage consimțământul oricând — înregistrarea se oprește." },
            ],
          cs: [
              { n: "01", title: "Vysvětlení", desc: "Lékař vysvětlí, že vyšetření bude nahráváno pro účely dokumentace." },
              { n: "02", title: "Souhlas", desc: "Pacient udělí souhlas, který je zaznamenán s časovým razítkem." },
              { n: "03", title: "Indikátor", desc: "Viditelný indikátor ukazuje, že probíhá nahrávání." },
              { n: "04", title: "Odvolání", desc: "Pacient může souhlas kdykoli odvolat — nahrávání se zastaví." },
            ],
          sr: [
              { n: "01", title: "Objašnjenje", desc: "Lekar objašnjava da će pregled biti snimljen radi dokumentacije." },
              { n: "02", title: "Saglasnost", desc: "Pacijent daje saglasnost, koja se beleži sa vremenskom oznakom." },
              { n: "03", title: "Indikator", desc: "Vidljiv indikator pokazuje da je snimanje u toku." },
              { n: "04", title: "Povlačenje", desc: "Pacijent može povući saglasnost u bilo kom trenutku — snimanje se zaustavlja." },
            ],
          hu: [
              { n: "01", title: "Tájékoztatás", desc: "Az orvos elmagyarázza, hogy a vizitet dokumentációs célból rögzítik." },
              { n: "02", title: "Beleegyezés", desc: "A beteg beleegyezését adja, amelyet időbélyeggel rögzítünk." },
              { n: "03", title: "Jelzés", desc: "Jól látható jelző mutatja, hogy felvétel van folyamatban." },
              { n: "04", title: "Visszavonás", desc: "A beteg bármikor visszavonhatja a beleegyezését — a felvétel leáll." },
            ],
        }) },
        { type: "prose", heading: t({ uk: "Зберігання згоди", en: "Consent records", pl: "Przechowywanie zgody", de: "Einwilligungsnachweise", ro: "Evidența consimțământului", cs: "Záznamy o souhlasu", sr: "Evidencija saglasnosti", hu: "A beleegyezés nyilvántartása" }),
          paragraphs: t({
            uk: ["Факт згоди зберігається разом із нотаткою та фіксується в незмінному журналі аудиту."],
            en: ["The fact of consent is stored alongside the note and recorded in the immutable audit log."],
            pl: ["Fakt udzielenia zgody jest przechowywany razem z notatką i zapisywany w niezmiennym dzienniku audytu."],
            de: ["Die erteilte Einwilligung wird zusammen mit der Notiz gespeichert und im unveränderlichen Audit-Protokoll festgehalten."],
            ro: ["Faptul consimțământului este stocat împreună cu nota și consemnat în jurnalul de audit imuabil."],
            cs: ["Udělený souhlas je uložen spolu s poznámkou a zaznamenán v neměnném auditním protokolu."],
            sr: ["Činjenica saglasnosti čuva se uz belešku i beleži u nepromenljivom dnevniku revizije."],
            hu: ["A beleegyezés tényét a jegyzettel együtt tároljuk, és a megmásíthatatlan auditnaplóban rögzítjük."],
          }) },
      ],
    },
  };
}
