import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import { resolveServices } from './src/api/services.js'
import { infraOrigins } from './src/company/infra.js'
import { leadOrigins } from './src/api/leads.js'
import { securityHeaders, cspModeFrom, cspDirectives, serializeCsp } from './src/security/csp.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(resolve(__dirname, 'package.json'), 'utf8'))

const PORT = 5173

// A FIXED dev nonce (sprint 16). Vite's dev server does two things a strict
// policy forbids: it injects the react-refresh preamble as an inline <script>,
// and it delivers every stylesheet by creating a <style> element and setting
// its textContent. Both are Vite's own code, not ours, and neither exists in a
// production build.
//
// The alternative to a nonce would be `'unsafe-inline'` in dev — which would
// mean the whole Playwright suite runs under a policy weaker than the one
// production enforces, i.e. the suite would stop being evidence. So instead we
// hand Vite a nonce (`html.cspNonce`), it stamps every tag it injects with it
// (including its own dev client's styles), and the dev policy stays otherwise
// identical to production's.
//
// The value being constant is not a weakness worth fixing: a nonce defends
// against injected markup in a SERVER-RENDERED response, and this dev server
// renders one static file for one developer on loopback. It is never emitted
// into a production build — `html.cspNonce` is set only for `command:
// 'serve'`, and check-prod-bundle.mjs fails the build if a nonce ever reaches
// dist/index.html.
const DEV_NONCE = 'mdx-dev-nonce'

// Deployment-config emitters. The built artifact carries the exact policy the
// bundle was built for, in the two formats a static SPA is actually fronted by
// — because a CSP that lives only in a dev-server middleware is a CSP that
// never reaches a clinic.
function renderNetlifyHeaders(headers) {
  const lines = ['# GENERATED by vite.config.js (sprint 16) — do not edit.',
    '# Netlify / Cloudflare Pages `_headers` format. Values are derived from',
    '# the SAME service map and VITE_CSP_MODE this bundle was built with, so',
    '# shipping dist/ ships its own policy.',
    '/*']
  for (const [k, v] of Object.entries(headers)) lines.push(`  ${k}: ${v}`)
  return lines.join('\n') + '\n'
}

function renderNginxHeaders(headers) {
  const lines = ['# GENERATED by vite.config.js (sprint 16) — do not edit.',
    '# `include` this from the server block that serves dist/. `always` matters:',
    '# without it nginx drops the headers on error responses, and a 404 page is',
    '# exactly where an injected script would like to run.']
  for (const [k, v] of Object.entries(headers)) {
    lines.push(`add_header ${k} "${v.replace(/"/g, '\\"')}" always;`)
  }
  return lines.join('\n') + '\n'
}

/**
 * Serve, and emit, the sprint-16 security headers.
 *
 * Dev and preview both get them so that every local run — and the entire
 * Playwright suite, which drives the dev server — executes under the policy.
 * A violation therefore fails a test instead of waiting to be discovered in
 * production.
 */
function securityHeadersPlugin({ services, mode, reportUri, extraConnect }) {
  const base = securityHeaders({ services, mode, reportUri, extraConnect })

  // Dev-only widenings, each with a reason:
  //   · the nonce, for Vite's injected preamble and its style elements;
  //   · the HMR socket, which is same-origin but a ws: scheme.
  const devHeaders = () => {
    if (mode === 'off') return base
    const d = cspDirectives(services, { reportUri, extraConnect })
    d['script-src'] = [...d['script-src'], `'nonce-${DEV_NONCE}'`]
    d['style-src'] = [...d['style-src'], `'nonce-${DEV_NONCE}'`]
    d['connect-src'] = [...d['connect-src'], `ws://localhost:${PORT}`]
    const name = mode === 'report-only'
      ? 'Content-Security-Policy-Report-Only'
      : 'Content-Security-Policy'
    return { ...base, [name]: serializeCsp(d) }
  }

  // Only HTML responses need these — stamping a header onto every .woff2 is
  // noise. The dev server has no extension on "/" or "/index.html" rewrites,
  // so key off the accept header the way a browser navigation looks.
  const middlewareFor = (headers) => (req, res, next) => {
    const accept = req.headers.accept || ''
    if (accept.includes('text/html') || accept === '' || accept === '*/*') {
      for (const [k, v] of Object.entries(headers)) res.setHeader(k, v)
    }
    next()
  }

  return {
    name: 'mdx:security-headers',
    // `vite dev` — the policy plus the two Vite-shaped widenings.
    configureServer(server) {
      server.middlewares.use(middlewareFor(devHeaders()))
    },
    // `vite preview` — the built artifact, and therefore the EXACT production
    // policy, nonce-free. This is the server e2e/csp.spec.js drives, so what
    // that spec proves is what a clinic will run, not a dev approximation.
    configurePreviewServer(server) {
      server.middlewares.use(middlewareFor(base))
    },
    closeBundle() {
      // The emitted configs describe a real deployment, which is https —
      // hence hsts, which the dev/preview middleware must never send.
      const prod = securityHeaders({ services, mode, reportUri, extraConnect, hsts: true })
      writeFileSync(resolve(__dirname, 'dist/_headers'), renderNetlifyHeaders(prod))
      writeFileSync(resolve(__dirname, 'dist/security-headers.nginx.conf'), renderNginxHeaders(prod))
    },
  }
}

export default defineConfig(({ command, mode }) => {
  // '' prefix: read every var, not just VITE_*, so an operator can set
  // VITE_CSP_MODE the same way they set anything else.
  const env = loadEnv(mode, __dirname, '')
  const services = resolveServices(env)
  const cspMode = cspModeFrom(env)
  const reportUri = env.VITE_CSP_REPORT_URI || ''
  // The owner console's infrastructure reachability probe (Grafana, Prometheus,
  // Jaeger, Loki, MinIO, Mailpit, Keycloak, the OTel collector, public-edge).
  // These are cross-origin `no-cors` fetches whose only signal is "did the
  // promise resolve" — so a policy that omits them does not just block the
  // probe, it makes the console report healthy containers as dead. Same
  // registry the console links to (src/company/infra.js), same env overrides.
  // …plus HubSpot, when the public signup form is wired to a portal: the lead
  // submission is a cross-origin POST from the browser (src/api/leads.js), and
  // a policy that omits it does not degrade the form — it blocks every lead,
  // silently, with nothing but a console entry to say so. `leadOrigins` returns
  // nothing when no portal is configured, so an unconfigured deployment does
  // not advertise an origin it never talks to.
  const extraConnect = [...infraOrigins(env), ...leadOrigins(env)]
  const dev = command === 'serve'

  return {
    plugins: [
      react(),
      securityHeadersPlugin({ services, mode: cspMode, reportUri, extraConnect }),
    ],
    // Dev only — see DEV_NONCE. A build must not stamp a constant nonce into
    // index.html: it would be a permanent, published bypass of script-src.
    html: dev ? { cspNonce: DEV_NONCE } : {},
    // The app must always be served from 5173 — playwright.config.js, the
    // backend CORS allow-list and the OIDC redirect URIs all hard-code it.
    // strictPort makes vite fail loudly instead of silently sliding to 5174.
    server: {
      port: PORT,
      strictPort: true,
    },
    preview: {
      port: PORT,
      strictPort: true,
    },
    define: {
      __APP_VERSION__: JSON.stringify(pkg.version || '0.0.0'),
    },
  }
})
