/* AUTO-GENERATED by scripts/contracts-typegen.mjs — DO NOT EDIT.
 * Source: evidence-backend/docs/api/evidence-contracts (contracts v1).
 * Regenerate: npm run typegen:evidence */

/* ── answer_envelope.v1.schema.json ────────────────────────────── */

export type AnswerId = string;
export type DbVersion = string | null;
export type Engine = string;
export type Entities = string[];
export type Narrative = string | null;
export type CheckOutcome = "passed" | "warning" | "failed" | "not_applicable";
export type RuleId = string;
export type FlagSeverity = "info" | "warning" | "critical";
export type Checks = CheckResult[];
export type ContractVersion = string;
export type PassageId = string | null;
export type Quote = string | null;
export type SourceId = string;
export type Citations = Citation[];
export type Id = string;
/**
 * The six segment kinds of rule FE7/RC2. Final; changes go through v2 + ADR.
 */
export type SegmentKind = "evidence" | "patient_fact" | "interpretation" | "uncertainty" | "missing_info" | "next_step";
export type PatientFactRefs = string[];
/**
 * Fixed evidence-strength scale per rule SC2.
 */
export type EvidenceTier = "guideline" | "systematic_review" | "rct" | "observational" | "other";
export type Text = string;
export type DetailSegments = Segment[];
export type Code = string;
export type Message = string;
export type RequiresAck = boolean;
export type Flags = Flag[];
export type FollowUpAnswerType = "boolean" | "choice" | "number" | "quantity" | "text";
export type Blocking = boolean;
export type Choices = string[] | null;
export type Id1 = string;
export type FollowUpPriority = "high" | "medium" | "low";
export type Question = string;
export type Unit = string | null;
export type WhyNeeded = string;
export type Followups = FollowUp[];
export type ProvenanceRef = string;
export type DocumentVersionId = string | null;
export type Id2 = string;
export type SourceKind = "corpus" | "web" | "drug";
/**
 * Authority precedence per rule RR3 (tenant > national > international > primary literature).
 */
export type SourceAuthority = "tenant" | "national" | "international" | "primary_literature" | "other";
export type Title = string;
export type AccessedAt = string;
export type Domain = string;
export type SnapshotRef = string | null;
export type WebTrustTier = "government" | "professional_society" | "guideline_registry" | "journal" | "other";
export type Url = string;
export type Sources = SourceRef[];
export type AnswerStatus = "ok" | "insufficient_basis" | "deflected";
export type SummarySegments = Segment[];

export interface AnswerEnvelope {
  answer_id: AnswerId;
  checks?: Checks;
  contract_version?: ContractVersion;
  detail_segments?: DetailSegments;
  flags?: Flags;
  followups?: Followups;
  provenance_ref: ProvenanceRef;
  sources?: Sources;
  status: AnswerStatus;
  summary_segments?: SummarySegments;
}
/**
 * Result of one deterministic check (rule CS1); computed by code, never a model.
 */
export interface CheckResult {
  db_version?: DbVersion;
  engine: Engine;
  entities?: Entities;
  narrative?: Narrative;
  outcome: CheckOutcome;
  rule_id: RuleId;
  severity: FlagSeverity;
}
export interface Segment {
  citations?: Citations;
  id: Id;
  kind: SegmentKind;
  patient_fact_refs?: PatientFactRefs;
  strength?: EvidenceTier | null;
  text: Text;
}
export interface Citation {
  passage_id?: PassageId;
  quote?: Quote;
  source_id: SourceId;
}
export interface Flag {
  code: Code;
  message: Message;
  requires_ack?: RequiresAck;
  severity: FlagSeverity;
}
export interface FollowUp {
  answer_type: FollowUpAnswerType;
  blocking?: Blocking;
  choices?: Choices;
  id: Id1;
  priority: FollowUpPriority;
  question: Question;
  unit?: Unit;
  why_needed: WhyNeeded;
}
/**
 * An entry of the envelope's sources[] panel; citations point at these.
 */
export interface SourceRef {
  document_version_id?: DocumentVersionId;
  evidence_tier?: EvidenceTier | null;
  id: Id2;
  kind: SourceKind;
  source_authority?: SourceAuthority | null;
  title: Title;
  web?: WebSourceRef | null;
}
export interface WebSourceRef {
  accessed_at: AccessedAt;
  domain: Domain;
  snapshot_ref?: SnapshotRef;
  trust_tier: WebTrustTier;
  url: Url;
}

/* ── answer_provenance.v1.schema.json ──────────────────────────── */

export type BuildVersion = string;
export type Connectors = string[];
export type ConsumedFields = string[];
export type CorpusSnapshotId = string | null;
export type CreatedAt = string;
export type PassageIds = string[];
export type PipelineVersion = string;
export type QuestionRef = string;
export type SnapshotHash = string | null;
export type WebRefs = WebSourceRef[];

export interface AnswerProvenance {
  answer_id: AnswerId;
  build_version: BuildVersion;
  connectors?: Connectors;
  consumed_fields?: ConsumedFields;
  contract_version?: ContractVersion;
  corpus_snapshot_id?: CorpusSnapshotId;
  created_at: CreatedAt;
  model_pins?: ModelPins;
  passage_ids?: PassageIds;
  pipeline_version: PipelineVersion;
  prompt_versions?: PromptVersions;
  question_ref: QuestionRef;
  snapshot_hash?: SnapshotHash;
  web_refs?: WebRefs;
}
export interface ModelPins {
  [k: string]: string;
}
export interface PromptVersions {
  [k: string]: string;
}
/* ── chunk.v1.schema.json ──────────────────────────────────────── */

export type CharEnd = number;
export type CharStart = number;
export type SectionPath = string | null;
export interface Chunk {
  char_end: CharEnd;
  char_start: CharStart;
  document_version_id: DocumentVersionId;
  id: Id;
  section_path?: SectionPath;
  text: Text;
}

/* ── clinical_intent.v1.schema.json ────────────────────────────── */

export type Display = string | null;
export type System = string;
export type Coding = Coding1[];
export type Concepts = ClinicalConcept[];
export type Negations = string[];
export type Population = string | null;
export type QuestionType =
  | "diagnosis"
  | "therapy"
  | "dosing"
  | "interaction"
  | "contraindication"
  | "prognosis"
  | "etiology"
  | "prevention"
  | "other";

export interface ClinicalIntent {
  concepts?: Concepts;
  contract_version?: ContractVersion;
  negations?: Negations;
  population?: Population;
  question_type: QuestionType;
}
export interface ClinicalConcept {
  coding?: Coding;
  text: Text;
}
/**
 * A code in a terminology system (ICD-10, ATC, SNOMED, LOINC, ...).
 */
export interface Coding1 {
  code: Code;
  display?: Display;
  system: System;
}

/* ── connector_descriptor.v1.schema.json ───────────────────────── */

/**
 * Authority precedence per rule RR3 (tenant > national > international > primary literature).
 */
export type DisplayName = string;
export type Enabled = boolean;
export type ConnectorKind = "local_corpus" | "tenant_corpus" | "pubmed" | "guideline_registry" | "web" | "drug";
export type NeedsEgress = boolean;
export type TenantFlaggable = boolean;
export type TimeoutMs = number;
export type Version = string;

export interface ConnectorDescriptor {
  authority_default?: SourceAuthority | null;
  display_name: DisplayName;
  enabled?: Enabled;
  id: Id;
  kind: ConnectorKind;
  needs_egress?: NeedsEgress;
  tenant_flaggable?: TenantFlaggable;
  timeout_ms?: TimeoutMs;
  version: Version;
}

/* ── corpus_snapshot.v1.schema.json ────────────────────────────── */

export type FrozenAt = string;
export type Label = string;
export type MemberVersionIds = string[];

export interface CorpusSnapshot {
  frozen_at: FrozenAt;
  id: Id;
  label: Label;
  member_version_ids: MemberVersionIds;
}

/* ── document.v1.schema.json ───────────────────────────────────── */

export type CanonicalId = string;
/**
 * Fixed evidence-strength scale per rule SC2.
 */
export type Jurisdiction = string | null;
export type LicenseClass =
  "public_domain" | "open_license" | "licensed_redistributable" | "licensed_internal" | "restricted";
export type PublishedAt = string | null;
export type Retracted = boolean;
/**
 * Authority precedence per rule RR3 (tenant > national > international > primary literature).
 */
export type Specialty = string[];
export type ValidUntil = string | null;

export interface Document {
  canonical_id: CanonicalId;
  evidence_tier: EvidenceTier;
  id: Id;
  jurisdiction?: Jurisdiction;
  license_class: LicenseClass;
  published_at?: PublishedAt;
  retracted?: Retracted;
  source_authority: SourceAuthority;
  specialty?: Specialty;
  title: Title;
  valid_until?: ValidUntil;
}

/* ── document_version.v1.schema.json ───────────────────────────── */

export type Checksum = string;
export type ContentRef = string;
export type DocumentId = string;
export type ParsedRef = string | null;
export interface DocumentVersion {
  checksum: Checksum;
  content_ref: ContentRef;
  document_id: DocumentId;
  id: Id;
  parsed_ref?: ParsedRef;
  version: Version;
}

/* ── evidence_passage.v1.schema.json ───────────────────────────── */

export type ChunkId = string | null;
export type ConnectorId = string;
export type Score = number | null;
export type Dense = number | null;
export type Final = number | null;
export type Fused = number | null;
export type Lexical = number | null;
export type Rerank = number | null;
export interface EvidencePassage {
  char_end?: CharEnd;
  char_start?: CharStart;
  chunk_id?: ChunkId;
  connector_id: ConnectorId;
  document_id?: DocumentId;
  document_version_id?: DocumentVersionId;
  evidence_tier?: EvidenceTier | null;
  id: Id;
  license_class?: LicenseClass | null;
  published_at?: PublishedAt;
  retracted?: Retracted;
  score?: Score;
  scores?: PassageScores | null;
  section_path?: SectionPath;
  source_authority?: SourceAuthority | null;
  source_kind?: ConnectorKind | null;
  text: Text;
  web_ref?: WebSourceRef | null;
}
/**
 * Per-stage score retention (S03): every stage's contribution stays
 * visible for provenance and eval ablations.
 */
export interface PassageScores {
  dense?: Dense;
  final?: Final;
  fused?: Fused;
  lexical?: Lexical;
  rerank?: Rerank;
}
/* ── patient_snapshot.v1.schema.json ───────────────────────────── */

export type EncounterRef = string | null;
export type DeidRequired = boolean;
export type FieldPath = string;
export type FactOriginKind =
  "patient" | "encounter" | "anamnesis" | "note" | "report" | "consent" | "act" | "user" | "host";
export type OriginRef = string;
export type RecordedAt = string | null;
export type Value = number;
export type Unit1 = string;
export type Value1 = number;
export type FactSource = "chart" | "act" | "user_reported" | "host_reported";
export type FactStatus = "coded" | "uncoded" | "conflict";
export type Value2 = string | null;
export type Facts = PatientFact[];
export type PatientRef = string;
export type SnapshotId = string;
export type TakenAt = string;

export interface PatientSnapshot {
  contract_version?: ContractVersion;
  encounter_ref?: EncounterRef;
  facts?: Facts;
  patient_ref: PatientRef;
  snapshot_hash: SnapshotHash;
  snapshot_id: SnapshotId;
  taken_at: TakenAt;
}
export interface PatientFact {
  coding?: Coding;
  deid_required?: DeidRequired;
  field_path: FieldPath;
  id: Id;
  label: Label;
  provenance: FactProvenance;
  quantity?: Quantity | null;
  source: FactSource;
  status: FactStatus;
  value?: Value2;
}
/**
 * A code in a terminology system (ICD-10, ATC, SNOMED, LOINC, ...).
 */
export interface FactProvenance {
  origin_kind: FactOriginKind;
  origin_ref: OriginRef;
  recorded_at?: RecordedAt;
}
export interface Quantity {
  normalized?: NormalizedQuantity | null;
  unit: Unit1;
  value: Value1;
}
/**
 * A quantity converted to the canonical unit for its dimension.
 */
export interface NormalizedQuantity {
  unit: Unit;
  value: Value;
}

/* ── retrieve_response.v1.schema.json ──────────────────────────── */

export type Count = number;
export type LatencyMs = number;
export type ConnectorStatus = "ok" | "degraded" | "unavailable";
export type ConnectorMeta = ConnectorMeta1[];
export type Degraded = boolean;
export type LexiconVersion = string;
export type ConnectorId1 = string;
export type Passages = EvidencePassage[];
export interface RetrieveResponse {
  connector_meta?: ConnectorMeta;
  contract_version?: ContractVersion;
  degraded?: Degraded;
  lexicon_version?: LexiconVersion;
  passages?: Passages;
  snapshot_id?: SnapshotId;
}
export interface ConnectorMeta1 {
  connector_id: ConnectorId;
  count: Count;
  kind: ConnectorKind;
  latency_ms: LatencyMs;
  status: ConnectorStatus;
}
/**
 * A retrieval result, whatever connector produced it.
 */
/* ── stage_trace.v1.schema.json ────────────────────────────────── */

export type EndedAt = string;
export type StageOutcome = "ok" | "retried" | "failed" | "skipped";
export type Stage = string;
export type StartedAt = string;

export interface StageTrace {
  ended_at: EndedAt;
  meta?: Meta;
  outcome: StageOutcome;
  stage: Stage;
  started_at: StartedAt;
}
export interface Meta {
  [k: string]: string;
}
