#!/usr/bin/env node
// EVA-S01: generate src/types/evidence.d.ts from the evidence-backend contract
// schemas (docs/api/evidence-contracts/*.schema.json).
//
// Source of truth is the backend export; this script NEVER stale-compiles: a
// missing/empty schema dir is a hard failure (rule: typegen fails loudly).
//
// Usage: npm run typegen:evidence
//   EVIDENCE_CONTRACTS_DIR overrides the default sibling-checkout path.

import { compile } from "json-schema-to-typescript";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsDir =
  process.env.EVIDENCE_CONTRACTS_DIR ??
  path.resolve(here, "../../dictate/evidence-backend/docs/api/evidence-contracts");
const outFile = path.resolve(here, "../src/types/evidence.d.ts");

let files;
try {
  files = (await readdir(contractsDir)).filter((f) => f.endsWith(".schema.json")).sort();
} catch (err) {
  console.error(`contracts dir unreadable: ${contractsDir}\n${err.message}`);
  process.exit(1);
}
if (files.length === 0) {
  console.error(`no *.schema.json in ${contractsDir} — refusing to emit an empty d.ts`);
  process.exit(1);
}

const banner = [
  "/* AUTO-GENERATED by scripts/contracts-typegen.mjs — DO NOT EDIT.",
  " * Source: evidence-backend/docs/api/evidence-contracts (contracts v1).",
  " * Regenerate: npm run typegen:evidence */",
  "",
].join("\n");

const seen = new Set();
const parts = [banner];
for (const file of files) {
  const schema = JSON.parse(await readFile(path.join(contractsDir, file), "utf8"));
  const ts = await compile(schema, schema.title ?? file, {
    bannerComment: "",
    additionalProperties: false,
  });
  // Contracts share $defs (Segment appears in AnswerEnvelope and standalone);
  // keep the first occurrence of each declared type, drop duplicates.
  const kept = [];
  for (const block of ts.split(/\n(?=export )/)) {
    const m = block.match(/^export (?:interface|type) (\w+)/);
    if (m) {
      if (seen.has(m[1])) continue;
      seen.add(m[1]);
    }
    kept.push(block);
  }
  if (kept.length) parts.push(`/* ── ${file} ${"─".repeat(Math.max(2, 60 - file.length))} */\n\n${kept.join("\n")}`);
}

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, parts.join("\n"));
console.log(`wrote ${outFile} (${seen.size} types from ${files.length} contracts)`);
